### ISSUE TITLE
Document XFORCIBLE

### ISSUE THREAD

**Issue by aidanPB** [fuzzball-muck/fuzzball#111]
The `XFORCIBLE` flag is mentioned in the documentation for `@set` and `@force`, but the documentation for the flag itself seems to have gotten lost at some point. Additionally, I don't think its use on exits/actions (displayed as `XPRESS`) was ever documented anywhere.

**Comment by wyld-sw** [comment]
Preliminary documentation for XFORCIBLE|XPRESS is now available in-server.
