### ISSUE TITLE
MUF code outside of any word should at least be a warning

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#115]
In a MUF file one can have code outside of any word like:`: x ; foreach repeat`. (Not surprisingly, I've found some bugs in how this code is handled.) This code is unreachable but still part of the compiled program instruction list. Probably this should be an error (if we aren't concerned about this kind of backwards-compatibility) or a warning.

**Comment by wyld-sw** [comment]
Fixed by #116.
