### ISSUE TITLE
various memory leaks and other errors found via fuzzing

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#126]
Here are some memory leaks and buffer over/underflows from fuzz testing:

- ~~`@tune oTest=here` leaks at tune.c:810 (strdup into oldvalue)~~
- ~~`@act toTest=here`, then `@lock toTest=#3&` performs an out-of-bounds stack read (underflow) at boolexp.c:193 (parse_boolexp_F)~~
- ~~`@find o[^x]` on a database containing an object named "Two" performs an out-of-bounds access in `smatch` when performing `smatch` for `o` and `o[^x]*`~~
- ~~`@act toTest=here` then `@fail toTest={&propdirs-example:r}` then `toTest` will perform an out-of-bounds write to cmdbuf at msgparse.c line 770.~~
- ~~`@act toTest=here` then `@fail toTest={le:rgo,\` then `toTest` will leak from the malloc at msgparse line 686 (for argv[argv]).~~
- ~~the MPI `{list:,me}` performs an out-of-bounds access at msgparse.c:250 (listname[len-1]); there appears to be a similar problem with {select:...}  at msgparse.c:190~~
- ~~the MPI `{NULL:{WHILE:1,{NULL:x}{NULL}{NULL:{NULL:{NULL}}}}}}}}}}}}}}` leaks from msgparse.c line 903 (`argv[i] = (char *) realloc(....` in the `mfun_list[s].parsep` case)~~
- ~~the MPI ```{filter:b,a,{in`valid}}}}}``` leaks from msgparse.c:686~~
- ~~the malformed MUF `: main FOR IF BREAK` leaks (when compiled) from add_loop_exit() around compile.c:3134~~
- ~~the MUF `"" NEWPROGRAM` performs a null pointer dereference~~
- ~~the MUF `NEXTENTRANCE` doesn't check for stack underflow~~
- ~~the MUF `"" 0.0 0.0 0.0 DIFF3` when run on an empty stack triggers an assertion failure on a MUCK built with --enable-debug~~
- ~~the MUF program `: x 0 forcedby_array array_notify_secure ;` causes an assertion failure on a MUCK built with --enable-debug~~
- ~~the MUF program `: main pop "" 0 over main and and ;` causes an assertion failure on a MUCK built with --enable-debug~~

**Comment by woggle** [comment]
Here are some memory leaks from fuzz testing:

- `@tune oTest=here` leaks at tune.c:810 (strdup into oldvalue)
- `@act toTest=here`, then `@lock toTest=#3&` performs an out-of-bounds stack read (underflow) at boolexp.c:193 (parse_boolexp_F)
- `@find o[^x]` on a database containing an object named "Two" performs an out-of-bounds access in `smatch` when performing `smatch` for `o` and `o[^x]*`
- `@act toTest=here` then `@fail toTest={&propdirs-example:r}` then `toTest` will perform an out-of-bounds write to cmdbuf at msgparse.c line 770.

**Comment by wyld-sw** [comment]
Striking through items when I think they're fixed.
