### ISSUE TITLE
PREEMPT primitive generates MUF compiler error

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#145]
On SPR, we have the following object:

```
whengraph.muf(#7335FLAVM3)  Owner: SPR
Type: PROGRAM  Flags: LINK_OK MUCKER3 VIEWABLE AUTOSTART
A scroll containing a spell called whengraph.muf
Created:  Sat Jul 29 13:19:00 UTC 1995
Modified: Sun Apr 23 23:18:47 UTC 2017
Lastused: Sun Apr 23 23:29:00 UTC 2017
Usecount: 9653831     Instances: 0
[ Use 'examine <object>=/' to list root properties. ]
Memory used: 3342 bytes
Program not compiled.
```

When I attempt to compile/use the program, I receive the following error:

`Program not compilable. Cannot run.`

The following is recorded in `logs/muf-errors`:

`2017-04-23T23:46:13: SPR(#9104) [whengraph.muf(#7335)] SPR(#9104) Error in line 2: Number outside procedure.`

Nothing was changed aside from pulling the latest (as of this date) code changes and recompiling on our sandbox system.

Output of `@list #7335=1-10`:

```
(WhenGraph - Another W* Program by Riss! 6/6/95)
PREEMPT
var CC
var scale
var dif
: dohelp
 "WhenGraph - By Riss - Ver 1.2" .tell
 " WG       - Displays a graph of the last 24 hours low and" .tell
 "             counts of connections to the server. " .tell
 " WG #dif  - Same display but with differential graph." .tell
10 lines displayed.
```

Is there an issue with the `PREEMPT` primitive that's generating this error? Is `PREEMPT` now required to be used within a MUF word rather than outside?

**Comment by aidanPB** [comment]
My understanding is that `PREEMPT` has always been meant to be used within definitions. It's a built-in define for `PR_MODE SETMODE`, and `PR_MODE` is a built-in define for a number, and you're no longer allowed to have numbers outside of definitions, which is where the compiler error is coming from.

I'm not sure it ever actually did what you wanted it to, anyway. If you want to ensure that all words in the program run in preempt mode, set it `BOUND`. (Also, the `AUTOSTART` flag only works if the program also has a wizbit.)

**Comment by wyld-sw** [comment]
An upcoming commit will promote PREEMPT and other internal macros to primitives to avoid confusion and reclaim a few instructions. 

And, my understanding is that for AUTOSTART to function, the program needs to be owned by a Wizard, not set W.
