### ISSUE TITLE
TLS connections broken on latest build?

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#188]
As of this date and time, I'm unable to connect to our testing server after pulling the latest code and performing a rebuild. The socket connects, but no welcome message is printed, and if I try to send any text (such as to log in), the connection immediately drops. Nothing out of the ordinary displayed in the logs. Unsecure connections continue to function normally. Let me know what additional data you need.

**Comment by wyld-sw** [comment]
I've been able to connect securely on Darwin and Linux using the latest build. Windows and Ubuntu (via WSL) were working as well earlier in the week.

The only change I can see in the last couple months dealing with SSL was 17a6cef - where the sockets are closed if SSL can't be configured initially - before the fix, it would just crash. I'm unsure if this would cause the symptoms you're seeing, but I know I could be wrong.

I'll keep investigating this, and trying it in different environments.

**Comment by sypherspace** [comment]
Let me know if I can provide any additional data to help.

**Comment by sypherspace** [comment]
This appears to have been a fluke. SPR is now running the latest code with no SSL issues.
