### ISSUE TITLE
Global scope (room zero) exit is taking priority over a local scope exit when exit priorities are equal.

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#190]
We use the {flag:} function in our obv-exits macro. Previously, this worked fine. Now it's throwing a permissions error. Can I ask what changed?

Updated: Local exit "spoof" and room zero-linked "spoof" were conflicting. For some reason, when the {flags:} function tried to look at the local "spoof" exit by name, it was getting room zero's copy instead, which was causing a permissions failure. Had to set M3 on the local exit to get the precedence to work right. Same behavior noted with "examine." "ex spoof" was giving me the global version, instead of the local one. What caused this change in behavior?

**Comment by sypherspace** [comment]
Confirmed. The local scope action is selected when trying to execute the command, but anything involving name matching is selecting the global scope action whenever the priority values are equal.

**Comment by wyld-sw** [comment]
Could be an unintended side effect of commit bc98723. I’m not by a computer today, so if you’re in a position to revert the commit, I’d appreciate the testing! Either way, I’ll be able to look at it sometime tomorrow. 

If I remember correctly, SPR’s previous compile date was July 6? If that’s right, that commit seems to be the only one affecting matching. But I only looked briefly. 

Sorry for the inconvenience :(

**Comment by sypherspace** [comment]
That appears to have partially solved the issue, but this gets a little more strange now.

With that commit reverted, if I try to examine anything that has a name that conflicts with a global scope exit, I will either get the global scope exit, or the local thing, and it's random as to which one I get.

**Comment by sypherspace** [comment]
Apparently, this issue has existed for quite some time. So not as critical.

**Comment by wyld-sw** [comment]
Great. I’ll officially revert that commit tomorrow. I ran into the same issue, on mucks with the “delimiter” command: by repeatedly issuing the “;” command, it was random what would actually execute.

Thanks for reminding me of it. The matching routine for exits and contents DOES randomly choose one if there are two equally named choices. If there’s not much more to it, perhaps it should favor a local exit.

**Comment by wyld-sw** [comment]
More specifically, choose_thing() needs to choose the more local before tossing a coin.

**Comment by sypherspace** [comment]
That was my thinking. In our case, the player was the local thing for "examine," and it would select the local player or the global exit randomly. Thanks!

**Comment by wyld-sw** [comment]
Commit reverted. Locality check should be in an upcoming fix.
