### ISSUE TITLE
MATCH not correctly matching in certain cases

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#193]
Player named "Test" is contained in "Room A." An action named "Test" is located on room zero, Room A's parent room. `"Test" match` is returning the action, not the player, even when executed in Room A. I believe the player should be matched in this case, as it is the more local object.

Note: I have replicated this issue on FurryMUCK as well as SPR, indicating that this has existed for some time.

**Comment by wyld-sw** [comment]
Corrected with previous locality fix.
