### ISSUE TITLE
Expose TLS cipher modes in status log on connect

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#196]
In my ongoing attempt to improve the security posture of MUCK servers and their clients, I'm trying to collect data on what TLS mode is being negotiated with each client as it connects in order to determine what clients will be affected by security configuration changes, such as the one motivated by the [ROBOT attack](https://robotattack.org/). 

That information is currently only presented to the client, and only for those clients lucky enough to use software that even bothers to report that data. Can we add data to the status log that indicates what cipher suite is used when a connection is established?

**Comment by wyld-sw** [comment]
Added cipher name to the status log. A future improvement would be to also list the TLS version.
