### ISSUE TITLE
"Only programmers are allowed to @list."

### ISSUE THREAD

**Issue by hyperlumic** [fuzzball-muck/fuzzball#205]
I'm not sure if this was an intentional change. In many cases, publicly-usable programs have implementation instructions buried in the MUF body itself, which needs to be `@list`ed to see, often by non-`MUCKER` users. This also goes directly against the documented functionality of the `VIEWABLE` flag, as shown here:

> When VEHICLE is set on a program, it is called VIEWABLE, and enables the program to be `@list`ed.

Same with `@list` documentation:

> Lists lines in a program, provided you control it or it is VIEWABLE.

`@version` output from SPR, where this behavior was confirmed:

```
Version: Muck2.2fb7.00b1(3) Compiled on: Fri Feb 23 2018 at 01:38:34 UTC
Options: GODPRIV IPV6 MCP RESOLVER SSL
```

**Comment by wyld-sw** [comment]
Definitely an oversight. Fixed with latest commit.
