### ISSUE TITLE
Compile-time option to have @shutdown and @restart generate different process exit codes

### ISSUE THREAD

**Issue by hyperlumic** [fuzzball-muck/fuzzball#207]
Our MUCK is currently managed as a systemd service. Per `man systemd.service`, systemd has the capability to restart a service on a non-zero process exit code (`Restart=on-failure`), or on ANY process termination (`Restart=always`).

Currently, `@shutdown` and `@restart` both end the process with exit code 0. This leads to an undesirable behavior where both commands either shut the MUCK down or restart it, depending on the service unit configuration.

I propose having a compile time option (`include/config.h` most likely) that causes the process to exit with code 0 on `@shutdown` and something non-zero (perhaps configurable) on `@restart`.

**Comment by kittykitty71** [comment]
I agree.  Would allow for hooking actual restart functions, and even better if it were configurable, since that would provide easy functionality for any custom situational restart need that may arise.

Aside from the fact that it really isn't necessary to have two commands do identical things, whole idea just sounds like good sense and good coding IMO.

**Comment by hyperlumic** [comment]
I didn't check to see if `@armageddon` also generates a zero exit code. If so, I would definitely suggest lumping that in with the above.

**Comment by wyld-sw** [comment]
This is a good idea. It prompted me to review exit codes for the main server. The main ones seem to be:

code 1:
 invalid syntax or inconsistent options
 cannot spawn resolver
 cannot set socket options
 `@armageddon`

code 2:
 problem loading database

code 3:
 output file the same as input file (with DISKBASE on)
 cannot create socket

code 4:
 cannot cd to game directory
 cannot bind socket

code 7:
 signal received - bailout

So, compile-time options RESTART_EXIT_CODE (default 0) and ARMAGEDDON_EXIT_CODE (default 1) seem appropriate. Any other option or standardization recommended? It would seem that exit codes 2-4 could just use code 1, but there may be a good reason for the way it is.

**Comment by hyperlumic** [comment]
I am hesitant to change any existing behaviors. Perhaps assign an unused exit code to `@restart`, and leave `@shutdown` as 0?

**Comment by wyld-sw** [comment]
Yeah, `@shutdown` would remain 0. I can change the default for RESTART_EXIT_CODE to 5.

**Comment by wyld-sw** [comment]
Per our conversation on SPR, I'll proceed with compile-time options RESTART_EXIT_CODE (default 0) and ARMAGEDDON_EXIT_CODE (default 1). Look for those soon.

**Comment by wyld-sw** [comment]
Compile-time options RESTART_EXIT_CODE (default 0) and ARMAGEDDON_EXIT_CODE (default 1) have been added to include/config.h .
