### ISSUE TITLE
Documentation reports it's for version 6.00

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#227]
The documentation in game/data/ says it's for version 6.00
I haven't learnt autoconf yet, but: wouldn't it be possible to create .in files for those, and have GNU autoconf replace some variable sorta thing with the version number?
Or is that better to do by hand with a sh/ed script?

**Comment by wyld-sw** [comment]
Documentation (in-game and in-package) is certainly on the list before the initial release of fb7. I've committed an approach that uses the VERSION define, but converting to another documentation format is an option.

**Comment by nyanster** [comment]
It's more about the version numbers all over the place than the documentation.  But I see! :D
On the topic of converting to another documentation format, I'm reworking much of prochelp.c right now, I've nearly gotten the HTML output to be valid HTML.
