### ISSUE TITLE
The strcpyn function

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#233]
While examining prochelp.c again, I saw a function defined called strcpyn.  It's used in a lot of files.  In fbstrings.c and resolver.c there's a comment explaining
"Like strncpy, except it guarantees null termination of the result string."
(the comment has a typo in resolver.c but is otherwise the same)
I find it confusing that strcpyn is defined and used when strncpy already exists, and strncpy is already in the C standard.  It's much easier, documentation-wise, to use standard functions, since I was able to read a man page on strncpy.  This is something I value as a C newb though, with my own needs.  But there's quite possibly a valid reason for strcpyn to exist, and I'm just not seeing it.  So I want to know what you guys think.
[demodiff.txt](https://github.com/fuzzball-muck/fuzzball/files/2632380/demodiff.txt)
I've attached a demonstration diff that shows it really does behave the same.  prochelp still worked after this diff.
Should strcpyn be replaced with the strncpy line + null termination line when it occurs in code?
Or should it be left as is?  If left as is, should it be left with its own implementation, or should its implementation be replaced in the way my demonstration diff shows?

**Comment by nyanster** [comment]
I now see similar with strcatn/strncat too.

**Comment by nyanster** [comment]
If we keep the current self-made implementation of strcpyn, int pos should be replaced by size_t pos by the way, since it's only compared with size_t bufsize.

**Comment by hyperlumic** [comment]
Just so you're aware, `sizeof()` is misused in your diff. `sizeof(char*)` will always return 4 on a 32-bit system, or 8 on a 64-bit system. As a result, `buf[sizeof(buf) - 1] = '\0';` will always place a `NUL` at the fourth or eighth byte in `buf`, no matter what the length or content of `buf` actually is.

```
$ cat test.c
#include <stdio.h>
#include <string.h>

int main()
{
        char *test1 = "This sentence is 36 characters long.";
        char *test2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        char *test3 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

        printf("strlen(test1): %lu\n", strlen(test1));
        printf("sizeof(test1): %lu\n", sizeof(test1));

        printf("strlen(test2): %lu\n", strlen(test2));
        printf("sizeof(test2): %lu\n", sizeof(test2));

        printf("strlen(test3): %lu\n", strlen(test3));
        printf("sizeof(test3): %lu\n", sizeof(test3));

        return 0;

}
```

```
$ cc test.c && ./a.out
strlen(test1): 36
sizeof(test1): 8
strlen(test2): 62
sizeof(test2): 8
strlen(test3): 186
sizeof(test3): 8
```

**Comment by nyanster** [comment]
Oh. >w<  Good thing to know.  Thank you so much!!
I was inappropriately copying part of an example in the strncpy manual page, then:
https://www.freebsd.org/cgi/man.cgi?query=strncpy
I applied similar printf lines to prochelp.c's strcpyn and found the same results you show. I wonder what I'm misunderstanding about the man page's example...
I see though. It's good to know about strlen.

**Comment by nyanster** [comment]
ah, pointers and arrays really are different
(sorry for blogposting all over you guys!)

That said, I'm still interested in what people think about strcpyn vs strncpy(3)

**Comment by nyanster** [comment]
Why was this closed?

**Comment by wyld-sw** [comment]
Closing this, but please feel free to comment further if there are questions.
