### ISSUE TITLE
.tell and other MUF macros

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#239]
While learning MUF by reading MINK (I'll read the official docs too, later!) I noticed something interesting about 'tell', in MUF.
tell is available as .tell from the macros file for both basedb and advancedb.  However, both the MUF manual, and the prim_tell function in p_strings.c seem to show that tell has been incorporated into Fuzzball itself since that time period.
However, tell also remains as a macro. (functionally identical from what I can tell by testing it myself, other than showing up as fewer steps in the Debug viewer, by not having to swap, etc, before notifying)
Should the macros files be updated by removing tell from the macros files?  If they are, .tell will have to be changed into tell wherever it is still used in MUF files.  Of course, that'd also mean any MUCK upgrading from fb6 to fb7 would have to do the same for all their MUF files, too.  (though that should be as simple and easy as 1,$s/.tell/tell/g)

Found the relevant commit:
https://github.com/fuzzball-muck/fuzzball/commit/1356041d78efc4edf23faf7a5fc27ff9575fa5bf

**Comment by wyld-sw** [comment]
One other idea would be to use a hook on game setup that changes older syntax to newer syntax in MUF programs, and summarize those actions for the admin.

**Comment by nyanster** [comment]
Ahh, you're right, it makes sense to keep .tell at least in the first nonbeta release of 7.  True!
Is there any 'todo' list for future things to do with fb so we don't forget?  (or are these github issues the most appropriate todo list, and should we just keep this issue open?)

**Comment by tanabi** [comment]
A lot of "third party" MUFs rely on these old macro's, so I'm not sure there's any benefit to removing them altogether.  But I suppose it could be up to the individual users to set up the macro's as they need 'em.  Just 2 cents from a random repo watcher.

**Comment by wyld-sw** [comment]
Exactly. I believe “me @ swap notify” is optimized to “tell” at this point. And I could see scanning existing MUFs at the time of muck setup and offering to manage undefined macros.

**Comment by nyanster** [comment]
It probably doesn't need to be, but from what I understood in a program's Debug output, that doesn't get optimized.  Just noticing a little detail.

**Comment by wyld-sw** [comment]
Optimizations like this, especially for something as common as output, can help the programmer of a complex MUF with avoiding the instruction limit.
