### ISSUE TITLE
HTML help files for Windows

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#243]
Right now, along with the .raw files that the other help formats are generated from, .txt files are included in the repository.  Should the HTML files be included too, so Windows users get them in their .zip file?
By the way, the download for fb7 for Windows here https://www.fuzzball.org/ doesn't work.  I get "Blob Not Found: The specified blob does not exist." along with other XML stuff.

**Comment by wyld-sw** [comment]
HTML files now live in game/data/, and can be installed to share/fbmuck/ .
