### ISSUE TITLE
Unexpected Parent Room Behavior

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#244]
Hey there;

We're running Muck2.2fb7.00b1

There is a zone with a parent room that is not set ABODE -- there are no flags on the parent room whatsoever.  However, when another (non-wizard, non-owner) character @dig's a room while being located in that zone, they get the zone's parent room even though they should not.  The zone's parent parent room is set A, so the player's room should have been parented there instead.

Maybe there's some new FB7 setting that changes parent room behavior?  Or maybe this is a bug?  Or maybe I'm just mis-remembering how its supposed to work :)

Thanks!

**Comment by wyld-sw** [comment]
The following code seems like it should do what you describe:

```
    newparent = LOCATION(LOCATION(player));
    while ((newparent != NOTHING) && !(FLAGS(newparent) & ABODE))
        newparent = LOCATION(newparent);
    if (newparent == NOTHING)
        newparent = tp_default_room_parent;
```

But I'm still digging (no pun intended). In the meantime, do you have access to a FB6 instance where you can test your exact commands? I'd also be happy to stop by your MUCK to see if we can reason this out.

**Comment by tanabi** [comment]
The MUCK in question is Hope Island, here: hope.mjspi.com 2048   (secure port)

You'd want to talk to Sheridan / Isidore, he owns the MUCK.  I'm just the player that found the bug :)  But he knows I filed the bug and would be happy to work with you.

I do have access to an FB6 MUCK so I will try to reproduce there.

**Comment by wyld-sw** [comment]
Hmm. I'm not seeing that behavior unfortunately (I do get the ABODE room as a parent, skipping a non-ABODE room), but I will get a character on Hope Island to check the situation. Could the Owlhaven Parent Room be set as the MUCK's default parent room by any chance?

**Comment by tanabi** [comment]
Nope -- Owlhaven is on Furry, I'm sure that's not the global parent :D It's a zone there.  Though furry may have its own custom code.  Website is: http://hope.mjspi.com/hope   you can put in the character request there and get it tonight.  We'll be happy to show you.  I've already given the owner a heads up.

**Comment by aidanPB** [comment]
Huh. [MINK](http://www.rdwarf.com/users/mink/muckman/rooms1.html) suggests that ABODE controls room parenting, but Fuzzball's own documentation is (as far as I can tell) silent on the subject. I _thought_ that a player who controls a room could use it as a parent regardless of its flags, but I'm not sure where I got that idea. (You wouldn't happen to be a Wizard, Realm-Wizard, or owner of Owlhaven, would you?)

**Comment by tanabi** [comment]
This turned out to be dumb :)  We had an @dig program that was overriding the server default (in order to do quota) and it wasn't respecting parent room behavior.  I guess FurryMUCK has the same problem.  This isn't a server issue, sorry for the run-around and props to @wyld-sw for being crazy responsive and helpful. :)
