### ISSUE TITLE
Add SECURE_SYSVARS primitive

### ISSUE THREAD

**Issue by kyanha** [fuzzball-muck/fuzzball#25]
Library functions that manipulate the database (especially on behalf of lesser-privileged programs) require the following prologue in order to secure their sysvars from inappropriate actions that the invoker would not be able to perform:

    "me" match me ! me @ location loc ! trig trigger !

This prologue takes 8 instructions (push a literal, MATCH, store-to-me, get-from-me, LOCATION, store-to-loc, TRIG, store-to-trigger).  This means that library calls can be expensive in terms of instructions used, just to ensure that they are not misused.

SECURE_SYSVARS is a verb to set me @, loc @, and trigger @ to the correct values in one instruction.

**Comment by wyld-sw** [comment]
Accepted, and implemented.

**Comment by kyanha** [comment]
Erm... you forgot to set the variable types there.  See the initialization in interp.c:interp() for more info.

fr->variables[0].type = PROG_OBJECT;
fr->variables[1].type = PROG_OBJECT;
fr->variables[2].type = PROG_OBJECT;

**Comment by wyld-sw** [comment]
Good catch. I assumed that they retained their original type. Fix incoming.

**Comment by kyanha** [comment]
(sorry for opening this up again!) It also looks like you need to CLEAR the previous values, so that e.g. the struct shared_string can have its reference count properly decremented.  See prim_bang() for examples.

**Comment by wyld-sw** [comment]
Sheesh. If someone assigned a string to those variables, I can see that. Thanks.
