### ISSUE TITLE
Possible evasion of compiler warnings

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#258]
When making my most recent pull request, I saw that in the IPv4 version of a function, the compiler warning I saw in the IPv6 version was silenced by a cast.
But, this cast was possibly inappropriate, (it shrunk a variable!) and only served to silence a compiler warning, I assume.
Since Fuzzball has been developed for decades, isn't it possible there's a lot of this?  Obfuscation to make compiler warnings go away.

Probably not much that can be done, but I want to know what you think.

**Comment by wyld-sw** [comment]
I agree that there’s probably a lot of this. We should probably document the cases we find and search for solutions that don’t involve downcasting.

**Comment by nyanster** [comment]
Closing this since the issue doesn't really do much, especially not in terms of short-term goals. (but it can be re-opened if anyone wants it as a reminder!)
