### ISSUE TITLE
OSX won't compile without pcre

### ISSUE THREAD

**Issue by foxbird** [fuzzball-muck/fuzzball#27]
Reported to me by Puck of HLM:

The OS X build environment does not include pcre by default.  FB's configure script has an option for --without-pcre which it accepts.  However the actual make still fails with 'pcre.h not found' so either it needs to be specified that pcre is required (it can be added to OS X, it's just not there by default) or the configure/make stuff needs to be fixed to be able to correctly build without pcre.

**Comment by wyld-sw** [comment]
The configure process now aborts if the PCRE directory is not discovered - by way of --without-pcre or --with-pcre=no. Previously it would only abort if no PCRE option was specified.

The search paths for PCRE and SSL also now contain /opt/local in addition to /opt.
