### ISSUE TITLE
MAXINT vs INT_MAX

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#290]
https://github.com/fuzzball-muck/fuzzball/blob/4af70647362eddc34d6f8c621b01538c54e2e42d/include/fbmath.h#L36
I'm not 100% sure how the math in these defines work, but they seem to just be fb-exclusive versions of INT_MAX and INT_MIN from the standard limits.h header.  We already include limits.h, and already use INT_MIN in p_stack.c
Is my understanding correct?  If it is, this is a simple find and replace to fix.  (this needs to be fixed in the documentation too...)

Don't close this until I fix this. :3  So I remember to do it.

Unrelatedly, advancedb 86.m manually defines MAXINT to 2147483647 which sounds like it might be a bad idea on some architectures.

**Comment by nyanster** [comment]
https://github.com/fuzzball-muck/fuzzball/blob/master/dbs/advancedb/muf/86.m#L110

**Comment by wyld-sw** [comment]
The local INT_* defines came before my time, but your assumption seems correct. Testing is certainly good, but I don't see a lot of downside to using the system defines. Perhaps we should also expose these values to MUF at the end of compile.c:include_internal_defs()

**Comment by nyanster** [comment]
Fixed (except for the MUF!) here:
https://github.com/fuzzball-muck/fuzzball/commit/1970c534fee5bf41e22ed23e75cd534c085ab422
https://github.com/fuzzball-muck/fuzzball/pull/291
