### ISSUE TITLE
Travis isn't building stuff anymore

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#293]
AppVeyor and Cirrus CI still are, though.
I noticed this when making a pull request, but master isn't being build by Travis either, for some reason.
This is probably something for Wyld to check by logging into Github and Travis. (whether with the Wyld or fuzzball-muck account, not sure)

**Comment by nyanster** [comment]
https://travis-ci.org/fuzzball-muck/fuzzball
"This is not an active repository
You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself."

**Comment by wyld-sw** [comment]
I had to re-link the account for whatever reason. Should be good now.
