### ISSUE TITLE
cmd-sweep lets any player of dbref 1026 sweep EVERYONE EVERYWHERE

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#297]
A leftover from whatever MUCK cmd-sweep was originally written on, sweep allows any player with the dbref 1026 to sweep others.

https://github.com/fuzzball-muck/fuzzball/blob/master/dbs/basedb/muf/34.m#L227
https://github.com/fuzzball-muck/fuzzball/blob/master/dbs/advancedb/muf/75.m#L230
https://github.com/fuzzball-muck/fuzzball-muf/blob/master/cmd-sweep.muf#L230

Tested this myself in basedb: it really does do this.  (though I changed the dbref to 55 for easier testing)

Unrelatedly, I think the editor commands and set commands in cmd-sweep.muf in fuzzball-muf should be put into comments, put between parentheses, so that they're still readable, but not something the MUF interpreter will read.  I can do that diff myself though.

**Comment by wyld-sw** [comment]
The editor and set commands are there so the files can be quoted in via a program like tinyfugue, or pasted in. I would recommend leaving those the way they are for now. I do agree with removing references to specific player dbrefs.

**Comment by nyanster** [comment]
> The editor and set commands are there so the files can be quoted in via a program like tinyfugue, or pasted in. I would recommend leaving those the way they are for now. I do agree with removing references to specific player dbrefs.

True, I did realise that's what they're for, but in effect, those commands make cmd-sweep.muf a text file rather than a MUF file, though.  But it has .muf at the end of its filename.  But the file as it is now can't be copied into game/muf/ by a MUCK's admin.
I DO think the information above and below the program is useful though, for sure.

**Comment by wyld-sw** [comment]
It is a bit counterintuitive, but they aren’t meant to be copied via the server - but as a script to be sent to the MUCK, as object creation and setup. A future game setup script would hopefully streamline this process. In this way, a “.muf” file can be seen as all the commands needed to set up the object. 

It looks like cmd-@sweep is the only one with #1026 in it; feel free to remove that line and it’s comment with your next pull request, if it’s not removed by then.

**Comment by wyld-sw** [comment]
cmd-sweep addressed in latest commits to fuzzball and fuzzball-muf.
