### ISSUE TITLE
MCP Doesn't Work - or I'm doing it wrong

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#300]
Hello fellow fuzzballians ...

So I'm working on a Python library that will allow easy manipulation of a MUCK through python script.  Part of this is I'm working on MCP support.

However, MCP isn't working as I expect it to ... and truth be told there's not really a lot of examples out there (that I have found).  I've seen ups-notify.sh which is most of what I've been using as a model, but ups-notify just *assumes* whatever it is doing is acceptable to the MUCK and doesn't actually verify.  Its very UDP-ish, fire and forget, hope it works :)  With my python, I want to enable 2 way conversations.

Here's what I have worked out so far.  One starts the party by setting an auth token.  This token has nothing to do with actually authorizing anything other than to make each MCP line distinct (i.e. it has nothing to do with logging in).  All of this works on the MUCK welcome screen, making logging in to use MCP unnecessary ... which is the magic of the ups-notify script, which has a corresponding MUF that listens to an event and handles its own authentication separately from logging in as a user.

Auth token is set thusly:
``#$#mcp authentication-key: "whatever" version: "2.1" to: "2.1"``
where the version is captured from the MUCK's welcome screen header (... though I suppose my library should pick a version it supports and stick with it).

When greeted with an authentication token, the server produces a catalog of available 'packages'.  This looks something like:

```
#$#mcp-negotiate-can whatever package: "mcp-negotiate" min-version: "1.0" max-version: "2.0"
#$#mcp-negotiate-can whatever package: "org-fuzzball-help" min-version: "1.0" max-version: "1.0"
#$#mcp-negotiate-can whatever package: "org-fuzzball-languages" min-version: "1.0" max-version: "1.0"
#$#mcp-negotiate-end whatever
```

Where 'whatever' is your auth key.  You notify the server of which packages you support by echoing back similar lines.  mcp-negotiate appears to be required.  So let's say we want mcp-negotiate and org-fuzzball-help, we would send to the server:

```
#$#mcp-negotiate-can whatever package: "mcp-negotiate" min-version: "1.0" max-version: "2.0"
#$#mcp-negotiate-can whatever package: "org-fuzzball-help" min-version: "1.0" max-version: "1.0"
#$#mcp-negotiate-end whatever
```

So far so good, this all seems to work.  To run a package, you do it thusly:

``#$#package-name whatever param1: "value" param2: "value"``

Where package-name is one of the packages, whatever is your auth key, and the parameters are whatever the package wants.

Now here is where it gets weird.  From my reading of the C code, it looks like org-fuzzball-help supports a 'topic' and a 'type' parameter.  So something like this:

``#$#org-fuzzball-help whatever topic: "dbref" type: "man"``

should give me the man page for 'dbref'.  However, I get nothing.  Doesn't matter if I am logged in or not.  I've tried several of the MCP packages (help, languages, and the extern package used by ups-notify) and none of them give me any response whatsoever.  I'm aware of the _data-tag wrinkle which allows for multi-line parameters ... but providing that or not seems to have no effect.

Is there some magic thing I'm missing or is this just broken?  I'm sifting through the MCP code now to see if I can get answers myself, though I figure someone out there in TV land might know how this works and can help me along (or confirm if its broken).

**Comment by nyanster** [comment]
I haven't gotten ups-notify to work before.  At least, not in fb7 master, which is the only fb I tested it on.

**Comment by tanabi** [comment]
> I haven't gotten ups-notify to work before. At least, not in fb7 master, which is the only fb I tested it on.

I think my MUCK head-wiz has gotten that script to work, so I think on some level it works, but I don't think MCP is sending output back to the descriptor.  I'm kind of at the point where I'd need to gdb the MUCK to see what's going on, which I will do if nobody else knows what is wrong.

**Comment by tanabi** [comment]
If anyone is curious to see it, I've checked in what I have so far.  It is very incomplete.  But the base works great.

**Comment by wyld-sw** [comment]
No clue on this yet. @mcpprogram and @mcpedit used to work, but I so far can't get Trebuchet woking in my current environment to test. I have to imagine it worked when we added the org-fuzzball-languages package. Hmm, I don't know what could have been done to cause this, but I may have modified a line of code that I shouldn't have. I'll keep digging...

**Comment by wyld-sw** [comment]
I do remember changing some pointer types relating to MCP a bit ago. Maybe that's it?

**Comment by nyanster** [comment]
> I do remember changing some pointer types relating to MCP a bit ago. Maybe that's it?

Probably not, if those changes were recent.  I tested some of this stuff on fb7alpha1 and it didn't work either, at least when trying to do the same stuff @tanabi was doing.  But I haven't tried on fb6 yet.

**Comment by nyanster** [comment]
> > I do remember changing some pointer types relating to MCP a bit ago. Maybe that's it?
> 
> Probably not, if those changes were recent. I tested some of this stuff on fb7alpha1 and it didn't work either, at least when trying to do the same stuff @tanabi was doing. But I haven't tried on fb6 yet.

Now that I think of it, I've successfully run 'guitest' on HLM before, and HLM runs fb7.

**Comment by tanabi** [comment]
Just 'for fun' I tried running the MCP commands on Furry (fb 6.11) while logged in.  I was able to negotiate, but org-fuzzball-help didn't work.

This is leading me to think I'm doing something wrong in the protocol itself.

**Comment by nyanster** [comment]
> This is leading me to think I'm doing something wrong in the protocol itself.

Yeah, these experiences, both yours and mine, make me think.  Either:
1. I'm doing MCP wrong and you're doing MCP wrong
2. Maybe Fuzzball has been doing MCP wrong for a long time and the clients that do work with it are doing MCP wrong too

For context, every time I've tried MCP with Fuzzball and have had it working, it's only been in a single client: Trebuchet.

**Comment by tanabi** [comment]
So I'm looking at trebuchet's code ... I've never done TCL before, so I really in particular don't know what's going on with the MCPInfo "object" ? (it is only referred to in mcpmgr.tcl where it is some kind of global)

https://github.com/revarbat/trebuchet/blob/master/lib/mcpmgr.tcl

The magic appears to happen in mcp_output_mesg.  I am honestly not 100% sure what its doing, but from my reading it looks like its doing what we're trying to do.

mcppkg_mcp handles the negotiation aspect, which appears to be the same as what I'm doing.

I'm not sure if its possible to verbose dump trebuchet's MCP messages but it seems like that's the best way to go now.  It must be doing some little special wiggle that we're not accounting for.

**Comment by tanabi** [comment]
I figured it out :)

The magic is here in trebuchet's code:

```
    if {$mesg == {}} {
        set mesg "$pkg"
    } else {
        set mesg "$pkg-$mesg"
    }
set out "#\$#$mesg"
```

If you look at the corresponding C, and/or put Trebuchet in debug mode (I did both in this case), you can see there's something referred to as the "mesg" which is suffixed to the package and is like an RPC method call.  in the case of org-fuzzball-help, the "mesg" called "request" is supported which you magically divine by looking at the C code.  The following block of MCP works:

```
#$#mcp authentication-key: "whatever" version: "2.1" to: "2.1"
#$#mcp-negotiate-can whatever package: "mcp-negotiate" min-version: "1.0" max-version: "2.0"
#$#mcp-negotiate-can whatever package: "org-fuzzball-help" min-version: "1.0" max-version: "1.0"
#$#mcp-negotiate-end whatever
#$#org-fuzzball-help-request whatever topic: "dbref" type: "man"
```

and it generates an expected response.

**Comment by wyld-sw** [comment]
Excellent. At the very least this will lead to better documentation.

Well done!

**Comment by nyanster** [comment]
> If you look at the corresponding C, and/or put Trebuchet in debug mode (I did both in this case), you can see there's something referred to as the "mesg" which is suffixed to the package and is like an RPC method call. in the case of org-fuzzball-help, the "mesg" called "request" is supported which you magically divine by looking at the C code. The following block of MCP works:

Ah yeah, the MCP standard (which I should go read, since I haven't read it yet) refers to these as messages: it very distinctly does so in an example here:
https://www.moo.mud.org/mcp/simpleedit.html

**Comment by tanabi** [comment]
Oh hey, I didn't even know there was a standard.  I was so engulfed in digging around fuzzball's docs that it didn't occur to me there might be a larger standard at play.
