### ISSUE TITLE
Mirror MINK?

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#301]
Hey guys;

I was poking around the various documentation pages looking for any MCP hints (per my other ticket) and I noticed that MINK was/is run by Jessy at FurryMUCK.  Jessy hasn't been on Furry in almost 3 years now (141 weeks at the time of this post) which tends to indicate this person probably isn't active in the community any more.

Should we make an effort to 'back up' Mink in some way and mirror it just in case it decides to disappear?  Mirroring it would also allow us to potentially update it, as it seems like the owner parked it back in 2004 and hasn't done much.

We could maybe import it into github's 'wiki', or make a separate repo and just wget the HTML into it if any of these options sound appealing ...

**Comment by nyanster** [comment]
Yessss, I keep poking @wyld-sw to mirror the MINK tarball:
http://www.rdwarf.com/users/mink/downloads/muckman.tar.gz
on:
https://www.fuzzball.org/

You don't even need to use wget.  And MINK specifically gives permission to do pretty much whatever you want with it.

**Comment by wyld-sw** [comment]
Ok, I've got a local copy linked from fuzzball.org - I also store the tarball.

We should definitely include this in the documentation review.
