### ISSUE TITLE
Segfault and Oddities when working with Autostart MCP MUF

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#306]
Okay ... so this is a little hard to quantify, I'm still sorting out the bug.

We are running mcp-extern (which comes in the fuzzball MUFs).  Typically, when the MUCK is running after a clean start, @ ps looks like:

```
**       167   4m  15m      0  0.0     #41 cmd-@doing Sheridan     SLEEPING
**       234   --   3m      0  0.0    #652 mcp-extern HopeIsland   EVENT_WAITFOR
```

When you edit an autorun program and then compile it, it restarts the program.  In our case, its making weird duplicate processes:

```
**       PID Next  Run  KInst %CPU   Prog# ProgName   Player       
**       228   1m   5m      0  0.0    #652 mcp-extern Ikkyo        SLEEPING
**       167   3m  16m      0  0.0     #41 cmd-@doing Sheridan     SLEEPING
**       234   --   5m      0  0.0    #652 mcp-extern HopeIsland   EVENT_WAITFOR
3 events.
```

I don't know what PID 228 is.  Ikkyo is definitely not running mcp-extern, there's no way possible for him to trigger it -- I think his process used to be either a wf process or cmd-@doing, not sure which, but he had something that 'turned into' mcp-extern.  At one point, I had managed to get a total of 3 mcp-extern's on @ ps but I'm not sure how I did that.  When I @ kill'd one of the duplicate mcp-externs, it crashed the MUCK.  So this is a fun one :)

I will try to investigate this more on my test MUCK but there is something buggy happening here.

**Comment by tanabi** [comment]
By the way, eventually Ikkyo's mcp-extern disappeared ...  So I guess it cleaned itself up, or the other process that was really running completed.

**Comment by tanabi** [comment]
Oh, but mcp-extern turned into cmd-pose somehow:

```
**       PID Next  Run  KInst %CPU   Prog# ProgName   Player       
**       258   --  40s      0  0.0     #60 cmd-pose.m HopeIsland   EVENT_WAITFOR
1 events.
```

Something is getting mixed up, pointer wise, and I think the MUCK will inevitably crash.

**Comment by tanabi** [comment]
When I open mcp-extern and recompile it, now I have 2 of these guys:

```
**       PID Next  Run  KInst %CPU   Prog# ProgName   Player       
**       258   --   2m      0  0.0     #60 cmd-pose.m HopeIsland   EVENT_WAITFOR
**       261   --  30s      0  0.0    #652 mcp-extern HopeIsland   EVENT_WAITFOR
2 events.
```

**Comment by wyld-sw** [comment]
That definitely is odd. I would wonder it's always #60. That could point to MCP incorrectly spawning a process with that specific number.

**Comment by tanabi** [comment]
MCP doesn't spawn a process; the extern process runs all the time and waits for connections with a MUF event wait call that runs in an infinite loop. Whatever internal process "restarts" auto run processes on compile may be buggy or causing some pointer error.  It does look like its usually # 60

**Comment by tanabi** [comment]
Oh, and BTW, the MUCK did eventually crash again "on its own".  Probably a segmentation fault.

**Comment by tanabi** [comment]
So I can reliably make this happen.

Install the attached mcp-extern.mf file -- set it A for autostart.  Restart the MUCK so it starts.
Log in both as the wizard that can edit mcp-extern.mf and another user (doesn't matter who).  At this point, @ ps should show cmd-watchfor sleeping for both characters and mcp-extern running.

@ edit mcp-extern and just compile it -- press 'c'.  Then do @ ps -- you will see some number of cmd-watchfor's have turned into clones of mcp-extern.mf

On a more active MUCK you'll see more chaotic results.

Note that I have tested this same thing with a MUF that just does a begin 1 sleep repeat loop and recompiling it doesn't cause a problem -- it seems to be a combination of autorun + MCP as far as I can tell.  I haven't yet gotten the MUCK to crash on demand due to this bug, but the MUCK will eventually crash on its own because something gets corrupted.

**Comment by tanabi** [comment]
As a point of interest, once cmd-watchfor gets 'overwritten' by test.muf, it crashes:

```
Programmer Error.  Please tell Keeper what you typed, and the following message.
cmd-watchfor.muf(#80), line 73; SV2:ctx !: Stack Underflow.
```
This doesn't seem to happen if I haven't triggered the bug (on my test MUCK).

**Comment by tanabi** [comment]
I can make the MUCK segfault with the following steps:

1. Do the above process first.
2. Wait for the watchfor processes to clear -- at this point @ ps should just show mcp-extern
3. @ kill the mcp-extern process
4. Link an action to mcp-extern.  Run it.  At this point, your connection will hang and @ Q will not quit the process.  Disconnect from the MUCK.
5. Log back in. @ ps probably won't show anything running at this point.
6. @ edit mcp-extern
7. Compile it several times
8. @ ps will now show a bunch of mcp-extern
9. Start @ killing them until the MUCK segfaults.

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555558c92d in RCLEAR (oper=oper@entry=0x5555559272b0, 
    file=file@entry=0x5555556306fb "array.c", line=line@entry=447)
    at interp.c:278
278		PROGRAM_DEC_INSTANCES(oper->data.addr->progref);
```

Backtrace:

```
(gdb) bt
#0  0x000055555558c92d in RCLEAR (oper=oper@entry=0x5555559272b0, 
    file=file@entry=0x5555556306fb "array.c", line=line@entry=447)
    at interp.c:278
#1  0x000055555556629b in array_tree_free_node (p=0x555555927290)
    at array.c:447
#2  0x00005555555663ba in array_tree_delete_all (p=<optimized out>)
    at array.c:550
#3  array_tree_delete_all (p=0x555555921a60) at array.c:554
#4  0x00005555555663ef in array_tree_delete_all (p=<optimized out>)
    at array.c:550
#5  array_free (arr=0x55555592b810) at array.c:782
#6  0x000055555556662d in array_free (arr=<optimized out>) at array.c:794
#7  0x000055555558c881 in RCLEAR (oper=oper@entry=0x5555559000d8, 
    file=file@entry=0x55555562d040 "interp.c", line=line@entry=734)
    at interp.c:299
#8  0x000055555558d54f in prog_clean (fr=0x5555558fc0c0) at interp.c:734
#9  0x00005555555b0ac5 in muf_event_process_free (ptr=0x55555592b750)
    at mufevent.c:49
#10 0x00005555555b1998 in muf_event_process () at mufevent.c:594
#11 0x000055555558ad0d in shovechars () at interface.c:2300
#12 0x0000555555565594 in main (argc=<optimized out>, argv=<optimized out>)
    at interface.c:4453
```

Looking at oper its kind of a mess in there:

```
(gdb) print *oper
$2 = {type = 12, line = 69, data = {string = 0x55555592cea0, 
    lock = 0x55555592cea0, number = 1435684512, 
    fnumber = 4.6355707376032019e-310, objref = 1435684512, 
    array = 0x55555592cea0, call = 0x55555592cea0, addr = 0x55555592cea0, 
    mufproc = 0x55555592cea0}}
(gdb) print *oper->data
Attempt to take contents of a non-pointer value.
(gdb) print oper->data
$3 = {string = 0x55555592cea0, lock = 0x55555592cea0, number = 1435684512, 
  fnumber = 4.6355707376032019e-310, objref = 1435684512, 
  array = 0x55555592cea0, call = 0x55555592cea0, addr = 0x55555592cea0, 
  mufproc = 0x55555592cea0}
(gdb) print oper->data.addr
$4 = (struct prog_addr *) 0x55555592cea0
(gdb) print *oper->data.addr
$5 = {links = 1435761568, progref = 21845, 
  data = 0x7ffff77bfcb0 <main_arena+112>}
```

**Comment by tanabi** [comment]
This is deep in the realm of stuff I don't know much about.  I hope some of this is diagnostically relevant.  Maybe tomorrow I'll try to trace this more.

**Comment by nyanster** [comment]
I'm probably stating the obvious, but, even though I don't understand any of this, seeing "optimized out" reminds me:
don't forget to remove -O2 from src/Makefile after doing ./configure in order to not optimize Fuzzball, for debugging.

**Comment by wyld-sw** [comment]
I think this may be related to events, and not specifically MCP.

I was able to see the "pid replacement" glitch with this wiz-owned autostart program:

`: main
 { "foo" }array
 event_waitfor
;`

Still hard to track down, but it may give us a clue.

**Comment by tanabi** [comment]
Something to try: does @ kill-ing an auto-start process, then compiling it to restart it, cause the same issue?

If not, then maybe we can have compile run the @ kill code.  As I recall, compile does its own little version of @ kill that is a separate code block.  It's possible when events were added, cleanup was added to kill but not compile.

Or they both might be screwed up :)

**Comment by tanabi** [comment]
As a random note -- event_waitfor completely kills any attempt at input -- you can't @ Q out of it.  Thusly, it should probably be something that either forces the program into BACKGROUND or raises an error that EVENT_WAITFOR only works for BACKGROUND processes.  Is there a reason to allow EVENT_WAITFOR to hang the foreground?  It looks like MCP-GUI may be a reason, so before doing this change we should probably check how MCP-GUI MUFs are written to see if they seem to rely on a foregrounded EVENT_WAITFOR ... if they don't, then let's do this change.  I'll split this into a separate ticket.

**Comment by tanabi** [comment]
@wyld-sw BIG NEWS : I can't reproduce this bug when I @ kill before I edit / compile!!  So I think the bug is with compile's route through killing processes.  Could you please give it a try as well to verify?

**Comment by wyld-sw** [comment]
Verified! Good thinking.

**Comment by tanabi** [comment]
@ kill follows a different code path than ... basically everything else that dequeues a process.  It calls muf_event_dequeue_pid which appears to do the necessary cleanup, and it looks like @ kill is the only places in the entire codebase that uses it.

Compile (and many, many other things) use dequeue_prog, which is a define that calls dequeue_prog_real in timequeue.c  Probably the best thing to do is to make sure dequeue_prog_real calls muf_event_dequeue_pid in a correct fashion.

I'll try to make a PR for this, which will (finally!) resolve this nasty bug.

**Comment by tanabi** [comment]
lol okay I found the real bug. So dequeue_prog_real (the underpinnings of dequeue_prog define) was  written really shitty.  It has a double loop; there's one loop to handle  if we are dequeue-ing the head of the timequeue, then a second loop to  handle the rest of the queue. Whomever added events didn't look very carefully at this function,  and assumed the second loop was the only one -- which is totally  logical, because having this as 2 loops is super stupid.  So the cleanup  was in place for the second loop, but not the first one. I'm fixing the call to be just 1 loop and everything should get cleaned up right.

**Comment by wyld-sw** [comment]
Closing this since it seems to be fixed.
