### ISSUE TITLE
Port Relevant Issues from SourceForge

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#308]
This task is to port relevant issues from source forge to github.

Relevant is defined as "still a problem" and "makes sense to do".

https://sourceforge.net/p/fbmuck/feature-requests/?limit=50
https://sourceforge.net/p/fbmuck/bugs/?limit=50

I would recommend clearing out the current "backlog" of issues before dragging these guys in :)  If you volunteer to screen these issues, please comment on which issues you've checked out.  Thanks!

**Comment by wyld-sw** [comment]
Feature Request SF32 (checkargs should support arrays) has been addressed (8778a551d7300502bd3f6ff0277d1ea3a4469e6c) and is now closed.
