### ISSUE TITLE
API Documentation Project

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#329]
I'm putting this issue in mostly as a forum for those who are interested in hearing progress updates or who have feedback about the process.  I've been doing commits over the past few weeks towards this effort already.

The effort in question is to implement Doxygen documentation for the entire MUCK code base, and to format the code to use spaces instead the weird hybrid space/tab thing that's going on now.  I'm also tidying up things here and there, but all cosmetic; there are no actual 'code changes' with this effort, however TODO messages are left anywhere that I see a mess that needs to be cleaned up.

My update as of 3/1: It's been awhile since my last PR for this effort, but that is because I'm working on commands.h.  Commands.h is a TON of functions, scattered all over the code, and the header actually has several .c files that exist just to implement commands.h features (create.c, wiz.c, set.c for example) so its a lot of work.

I've been working on it several hours each day, and actually I'm probably only about 60% done at this point.  This thing is a monster.  So chances are it will be another week or so before I have another PR, and it will be a doozy.  I probably should have thought of a way to split this work up better, but I didn't really know what I was getting into until I got into it ...  I will try to avoid mammoth PR's in the future, but I'll go ahead and apologize for this one :)

**Comment by nyanster** [comment]
> The effort in question is to implement Doxygen documentation for the entire MUCK code base, and to format the code to use spaces instead the weird hybrid space/tab thing that's going on now. I'm also tidying up things here and there, but all cosmetic; there are no actual 'code changes' with this effort, however TODO messages are left anywhere that I see a mess that needs to be cleaned up.

Why spaces?  They don't provide the semantic information tabs do.  It's far easier to to convert tabs to spaces than spaces to tabs, since tabs provide knowledge spaces don't: with spaces, you experience a **loss of information**.  An initial tab is a level of indentation, but spaces could mean anything depending on the context.  (especially as many style guides use spaces for alignment: if you use spaces to indent and then spaces after to align...  you can't tell the boundary between one and the other.  I think indentation should be both human-readable and machine-readable, myself)
As Fuzzball has a very strong Unixy background, one may as well use a Unix-like code style (which uses tabs) though that certainly isn't required and isn't as strong a point as the one above.  Though, this might not be the right spot for me to argue this (my bad!) as there's an issue for this already:
https://github.com/fuzzball-muck/fuzzball/issues/185
> My update as of 3/1: It's been awhile since my last PR for this effort, but that is because I'm working on commands.h. Commands.h is a TON of functions, scattered all over the code, and the header actually has several .c files that exist just to implement commands.h features (create.c, wiz.c, set.c for example) so its a lot of work.
> 
> I've been working on it several hours each day, and actually I'm probably only about 60% done at this point. This thing is a monster. So chances are it will be another week or so before I have another PR, and it will be a doozy. I probably should have thought of a way to split this work up better, but I didn't really know what I was getting into until I got into it ... I will try to avoid mammoth PR's in the future, but I'll go ahead and apologize for this one :)

Woah ;w;  that is a lot of work, as I imagined it was.  Maybe split it up by .c file instead of .h file?  I guess not, by now.

**Comment by tanabi** [comment]
> Why spaces? They don't provide the semantic information tabs do. It's far easier to to convert tabs to spaces than spaces to tabs, since tabs provide knowledge spaces don't: with spaces, you experience a **loss of information**. An initial tab is a level of indentation, but spaces could mean anything depending on the context. (especially as many style guides use spaces for alignment: if you use spaces to indent and then spaces after to align... you can't tell the boundary between one and the other. I think indentation should be both human-readable and machine-readable, myself)
> As Fuzzball has a very strong Unixy background, one may as well use a Unix-like code style (which uses tabs) though that certainly isn't required and isn't as strong a point as the one above. Though, this might not be the right spot for me to argue this (my bad!) as there's an issue for this already:
> #185

To be honest, it didn't even occur to me to use tabs -- I've been a professional programmer since 1998 and I think the last time I worked on a project using tabs is the early 2000's.  For the past 10+ years, all projects both professional and open source that I've worked on have used spaces.  Probably because with "tab emulation" that is supported in practically every editor (even vi), there's not a lot of call to use tab characters.

The problem with tabs is that it makes some assumption of tab sizing.  So when I open fuzzball's code, i actually get a loss of information since I'm pretty sure fuzzball's code expects an 8 character tab and mine is set to 4 characters (which is again pretty common these days).  When I look at the code, it's jumbled all over the place, doesn't even look vaguely right.

While I can certainly tweak my editor settings to correct this problem, using spaces avoids all ambiguity and also makes it so its clear how its supposed to look for all future developers.  Further, it is easier to make 'custom spacing' where needed (i.e. when you get really big gnarly if statements -- which should be avoided, yes, but sometimes cannot be avoided).

I'll ultimately concede to whatever the group prefers, however, the current mix of tab and space is most definitely the *wrong* solution.  One or the other.

**Comment by nyanster** [comment]
> To be honest, it didn't even occur to me to use tabs -- I've been a professional programmer since 1998 and I think the last time I worked on a project using tabs is the early 2000's. For the past 10+ years, all projects both professional and open source that I've worked on have used spaces. Probably because with "tab emulation" that is supported in practically every editor (even vi), there's not a lot of call to use tab characters.

Interesting!  Though there is a use, which is making code easier for more people to read.
> The problem with tabs is that it makes some assumption of tab sizing. So when I open fuzzball's code, i actually get a loss of information since I'm pretty sure fuzzball's code expects an 8 character tab and mine is set to 4 characters (which is again pretty common these days). When I look at the code, it's jumbled all over the place, doesn't even look vaguely right.

Actually, it is possible to use tabs without assuming tab sizes.  If it ends up jumbled, it means it wasn't used properly.  **Proper** here means tabs for indentation, spaces for non-indentation alignment: this means that regardless of tab side, things stay aligned, and everyone gets to benefit by being free to choose their fave tab size when reading the code.
I agree that things are are wrong if they're looking jumbled for _anyone_, and I was actually planning to experiment with this by looking at different files run through expand, after I made this commit:
https://github.com/fuzzball-muck/fuzzball/commit/3dc93ec94bec23feb9ef31778dd21b876fd5403e
It wasn't meant to be formatting-related, but I realised some formatting errors became easier to correct when I got rid of some spaces.  (though, as said in the commit comment, I want to figure out what to do with the tabs between the code and comments)
https://man.openbsd.org/expand
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/expand.html
Basically you can tell it to convert all tabs in a file to any number of spaces you ask it to, so it can greatly help in debugging tab/space/style-related stuff.
> While I can certainly tweak my editor settings to correct this problem, using spaces avoids all ambiguity and also makes it so its clear how its supposed to look for all future developers. Further, it is easier to make 'custom spacing' where needed (i.e. when you get really big gnarly if statements -- which should be avoided, yes, but sometimes cannot be avoided).

I don't ask anyone to use editor settings other than their favorites: my goal is entire customisability for readers.  I don't understand what ambiguity tab usage brings, though, since things will look the same for all developers, except for how far right on the screen code is.
> I'll ultimately concede to whatever the group prefers, however, the current mix of tab and space is most definitely the _wrong_ solution. One or the other.

True, for indentation.

**Comment by nyanster** [comment]
As an example of what I mean about indentation versus alignment...
https://github.com/nyanster/fuzzball/pull/1/commits/fa3ea87e144af3e0e9c0ec89ac481e56e7eb209d
https://github.com/nyanster/fuzzball/pull/1
https://github.com/nyanster/fuzzball/blob/fa3ea87e144af3e0e9c0ec89ac481e56e7eb209d/include/dbsearch.h
Try putting it through expand.  The comments always stay aligned.  But the indentation can be moved as far left or right as a reader wants.

**Comment by tanabi** [comment]
I only have about 10 more commands to do, woo, so I'll have a PR in any day now.  I think after this is done I'll try nyanster's suggestion and work by .c file instead of .h file ... should be less mammoth PR's that way.

**Comment by tanabi** [comment]
Finished commands.h and then switched to working based on .c files...

....the next .c file to work on is compile.c which is an utter monster.  Fuzzball hates me :)

**Comment by tanabi** [comment]
Just an update -- slowly working through compile.c.  I'm about 75% complete on it I think.  Just getting a basic understanding of what this thing does has been challenging, and I've had to go back and revise comments as I figure it out, but the light is there at the end of the tunnel.

**Comment by tanabi** [comment]
Finished compile.c tonight.  Looks like crt_malloc.c is next (I already did create.c).  Looks relatively easy, though I think most things will be relatively easy compared to compile.c.

Doing a wc -l, I see compile.c is the biggest with the next biggest being interface.c.  All the other file sizes are reasonable-ish.  I have a lot of small files between where I am and interface.c so I am looking forward to some smooth sailing and easy commits :)

**Comment by nyanster** [comment]
> Finished compile.c tonight. Looks like crt_malloc.c is next (I already did create.c). Looks relatively easy, though I think most things will be relatively easy compared to compile.c.
> 
> Doing a wc -l, I see compile.c is the biggest with the next biggest being interface.c. All the other file sizes are reasonable-ish. I have a lot of small files between where I am and interface.c so I am looking forward to some smooth sailing and easy commits :)

If you're doing it in any order, I think crt_malloc.c could be done later because it's one of the dev configure options rather than a core part of Fuzzball.  I think it's the enable memprof option.
Either way. :P

**Comment by tanabi** [comment]
> If you're doing it in any order, I think crt_malloc.c could be done later because it's one of the dev configure options rather than a core part of Fuzzball. I think it's the enable memprof option.
> Either way. :P

I'm doing it alphabetical to preserve my sanity and to make sure I cover everything.  I'm aware this isn't exactly what you'd call "main line code" in there, but I still think it needs to get done.  And at only ~ 900 lines or so (if I remember right) it won't take me long to do.  It has a lot of overlap with fbstring actually because many of those methods are replaced by crt_malloc.c when the memprof option is set.

**Comment by wyld-sw** [comment]
I've thought that the crt_malloc functionality could be easily replicated by use of valgrind - I don't think it's available on Windows, though. Maybe something to consider going forward.

**Comment by nyanster** [comment]
> I've thought that the crt_malloc functionality could be easily replicated by use of valgrind - I don't think it's available on Windows, though. Maybe something to consider going forward.
> 
> Certainly good to include the current code in the doc project :)

Fuzzball shouldn't be held back by Windows~
:P

**Comment by wyld-sw** [comment]
And it won't be. But we do support it (WSL notwithstanding), so I thought I'd mention it. I believe `@memory` is not compiled in by default on Windows anyway.

**Comment by tanabi** [comment]
> I've thought that the crt_malloc functionality could be easily replicated by use of valgrind - I don't think it's available on Windows, though. Maybe something to consider going forward.
> 
> Certainly good to include the current code in the doc project :)

Windows probably has its own memory profiler.  I'll confess I know nothing about it; I've used valgrind before but never tried to do profiling on windows.

I think, generally speaking, if we wish to do memory profiling on FB we should probably use valgrind.  However, at this point, there's no particular reason to remove crt_malloc and it provides the potential function of assisting with Windows memory profiling so there's no hurt in keeping it for now.

But if it ever becomes painful or obsolete, I think it is an easy choice to remove it as the utility it provides a modern development environment is limited at best.

**Comment by tanabi** [comment]
crt_malloc is done ... on to db.c

db.c is a middle of the road monster in terms of lines of code.  High end of average.  I'm sure there will be a lot to poke at :P

**Comment by tanabi** [comment]
db.c is done .. apparently took me 4 days!  Next is debugger.c. At 986 lines long, its pretty average in size.  A quick skim of the code makes it look pretty densely packed.  Once more into the breach!

**Comment by tanabi** [comment]
debugger.c is done ... on to diskbase.c

diskbase is a small one (534 lines) so hopefully this will be an easy one.

**Comment by nyanster** [comment]
I still have to catch up on your past three. :B
@tanabi , when you come across functions that seem to re-implement or replace stuff from C's standard library, may I ask for you to note that in their Doxygen comments?  With a special greppable keyword maybe, or just plain English describing it.  I know you already did for one or two, which I'm now thankful for.

Reminded, because, just this morning, I was reading some of fb6's code, and I saw _the developer implemented strftime() entirely on his own_ and I was amazed. (and not amazed in a good way!)  Looked into it because MPI ftime was behaving oddly on some MUCKs I was using (%n and %t weren't working)
I know I've seen stuff like this before:
https://github.com/fuzzball-muck/fuzzball/issues/233
(my fix there was broken at the time but I have a better one in mind, for that specific one...)

I think it'd be a nice idea to not implement the C standard library in Fuzzball, when it's possible to not do so.

**Comment by tanabi** [comment]
> I think it'd be a nice idea to not implement the C standard library in Fuzzball, when it's possible to not do so.

Yeah, whenever I notice this, I take note.  The really unfortunate thing is most of these are the C library with a little twist -- such as weird NULL handling or the like -- so there's usually some "gotchya" to dealing with these.  Resolvable, but one has to be very careful.

**Comment by tanabi** [comment]
I've been silently lately because I went to a convention.  I'm back and and resuming work on this!

**Comment by nyanster** [comment]
> I've been silently lately because I went to a convention. I'm back and and resuming work on this!

Was it fun?

Blah, we really need an IRC channel, Jabber (XMPP) channel, or MUCK for fast conversation and mixed on-topic off-topic conversation, huh. :3
I'll make an issue for this since this is something that's already been discussed. :D

**Comment by wyld-sw** [comment]
I just invited both of you to a Slack workspace, in case that's a good method for you.

**Comment by nyanster** [comment]
> I just invited both of you to a Slack workspace, in case that's a good method for you.

Unfortunately, Slack does not support my OS (FreeBSD).  It is also closed-source, meaning that's an issue likely to happen for others, too.
But, thank you for the invite, though! :D

**Comment by nyanster** [comment]
Issue made:
https://github.com/fuzzball-muck/fuzzball/issues/379
Discussion of communication could/should happen there. :B

**Comment by nyanster** [comment]
@wyld-sw 
unclose this pls :3  I don't think @tanabi is done documenting the API

**Comment by wyld-sw** [comment]
I guess I'm used to a different UX for action buttons. Regardless, sorry for the confusion!

**Comment by tanabi** [comment]
edit.c is in the works now.

**Comment by tanabi** [comment]
Almost done with edit.c ... how unexpectedly complex :P

**Comment by tanabi** [comment]
edit.c is done .... events.c is next.  Seems like a shorty!

**Comment by tanabi** [comment]
events.c was indeed a shorty ... done.  On to fbmath.c!  Also kind of a shorty but I probably won't finish that tonight anyway.

**Comment by tanabi** [comment]
fbmath.c was pleasantly easy, rolling on to fbsignal.c

**Comment by tanabi** [comment]
fbsignal.c is done, fbtime.c is next (fbstrings I did already)

**Comment by tanabi** [comment]
fbtime.c is done.  Strap yourself in, its time to do game.c

**Comment by tanabi** [comment]
Almost done with game.c ... I'm not putting a lot of effort into the mega switch statement beyond fixing the formatting cause @wyld-sw and I wanna tear that crap out.  I'll probably have it done tomorrow.

**Comment by tanabi** [comment]
game.c is done ... rolling on to hashtab.c!

**Comment by tanabi** [comment]
hashtab.c didn't take much to do.  interface.c is next .... *shudder*

**Comment by tanabi** [comment]
I'm still alive, though interface.c is a monster.  I'm about 50% done.

**Comment by tanabi** [comment]
I'm so  close to done with interface.c -- about 80% or so according to the scroll bar -- but there's a million little functions so it is taking me forever to finish this last stretch.

**Comment by tanabi** [comment]
I'm still alive.  This thing just has soooo .... maaany .... little .... functions :P

**Comment by tanabi** [comment]
STILL toiling away at this ... wow this is taking me forever.  Sorry, I do like 4 or so functions a night, but there's so many damn functions.

**Comment by wyld-sw** [comment]
No worries at all! interface.c is one of the biggest files we've got (compile.c is bigger, but has huge functions). The work certainly is appreciated. I'm sure you've already found several ways to clean up, split up, or consolidate the logic there so it's easier to review going forward.

**Comment by tanabi** [comment]
interface.c is finally done.  interface_ssl.c is next, and it is like, 200 lines.  Thank goodness :)

**Comment by tanabi** [comment]
interface_ssl.c is done but I didn't bother committing it separately.  Working on interp.c ... haven't even made it through the header yet, it is hyper dense with stuff I have to research and figure out.  But progress!

**Comment by tanabi** [comment]
I haven't commented in awhile because I got sidetracked working on other MUCK related items (MUF for Hope + work on #306 ) ... I have accomplished something though!  I just finished documenting all the defines, externs, and structures in interp.h ... this was a surprisingly massive amount of work requiring a lot of research to figure out what each thing did, but I think I have a pretty accurate depiction.

Now its on to the .c file.  Maybe I'll have this finished in a month or two at this rate ;)

**Comment by tanabi** [comment]
I've been paused on this because I've had some MUF work to do on my home MUCK.  I'll be back to this soon.  But I'm still alive.

**Comment by tanabi** [comment]
I'm still alive!  Finally finished interp.c.  log.c is next!

**Comment by tanabi** [comment]
log.c is done, on to look.c

**Comment by tanabi** [comment]
I already did look.c and forgot about it, so match.c is up next

**Comment by tanabi** [comment]
match.c is done.  mcp.c is partially done, but has some more to do, so I will finish that file next.

**Comment by tanabi** [comment]
I'm still alive... mcp.c is about 85% done, just a lot of little functions in there.

**Comment by tanabi** [comment]
mcpgui is done, mcppkg is next!

**Comment by tanabi** [comment]
mcppkgs is done, moving on to mfuns!  Sounds m-fun to me!

**Comment by tanabi** [comment]
I'm almost done with mfuns ... next time I get a chance to sit down with it, I should finish it.

**Comment by tanabi** [comment]
mfuns is done, mfuns2 is next!

**Comment by tanabi** [comment]
Finished mfuns2.  Will do mkversion I guess ?  I dunno if I need to document that.  move.c if not!

**Comment by wyld-sw** [comment]
Was mkversion/version.c/version.tpl removed from the repo when we changed the version scheme? If so, might be an easy decision :)

**Comment by tanabi** [comment]
mkversion is a binary and may be something left over ... so i'm working on move.c

**Comment by tanabi** [comment]
move.c is done, on to msgparse.c!

**Comment by tanabi** [comment]
Jeez I can't believe msgparse is taking me a month!  Granted I had about 2 weeks where I couldn't work on much, but still.  I'm almost done with it.  I'm still alive, really!

**Comment by tanabi** [comment]
I'm still alive!  Still working on msgparse.c ... almost done though

**Comment by tanabi** [comment]
msgparse.c is done!  Looks like mufevent.c is next.  I'm over halfway done (since I did some files, initially, out of alphabetical order ... I'm not sure what the total percent complete actually is, but, it's definitely more than half!)

**Comment by tanabi** [comment]
mufevent is done!  I'm now diving into MUF prims.  How ~horrifying~ exciting!  p_array.c is next

**Comment by wyld-sw** [comment]
p_connects has been documented!

**Comment by tanabi** [comment]
p_array is done!  I'll hit p_db.c next unless @wyld-sw wants it? ... I think we had an indecisive email conversation about it. :D

**Comment by wyld-sw** [comment]
I’ll take it!

**Comment by tanabi** [comment]
Okay!  p_error is mine then.

**Comment by tanabi** [comment]
p_error is done.  @wyld-sw I'll take p_float next.

**Comment by tanabi** [comment]
p_float is done.  @wyld-sw I'll take p_math next.

**Comment by wyld-sw** [comment]
p_db is done and awaiting approval. (MOVETO may need special attention later). @tanabi, I'll take p_mcp.

**Comment by wyld-sw** [comment]
Actually... @tanabi, you've got more experience with MCP than I do, so it might be better for the project if you documented the 14 primitives in p_mcp. I can take p_misc, if you agree!

**Comment by tanabi** [comment]
@wyld-sw p_misc is yours!  I will look at p_db right away

**Comment by tanabi** [comment]
p_math is done, doing p_mcp next.

**Comment by tanabi** [comment]
I had injured my elbow (just tendonitis, nothing "serious) though part of my recovery was to avoid unnecessary typing / motion / etc.  I'm finally getting back in action enough to resume work here, yay!

**Comment by tanabi** [comment]
p_mcp is done.  Claiming p_props @wyld-sw

**Comment by wyld-sw** [comment]
Sounds good to me. p_misc is almost done too!

**Comment by tanabi** [comment]
p_props is done ... claiming p_regex @wyld-sw

**Comment by wyld-sw** [comment]
p_misc is done. p_stack is next for me! @tanabi

**Comment by tanabi** [comment]
Awesome!  I'm almost done with p_regex

**Comment by tanabi** [comment]
p_regex is done, @wyld-sw I am doing p_strings next

**Comment by tanabi** [comment]
p_strings is done.  pennies.c is already documented.  @wyld-sw I'll take player.c next!  I think we're getting towards the end -- a lot of these last files are already documented.

**Comment by tanabi** [comment]
player.c is done!  @wyld-sw taking predicates.c

**Comment by wyld-sw** [comment]
p_stack is finally done - sorry for the huge delay. Also sorry for the irrelevant commits in my PR - I'll remember to sync my fork next time!

@tanabi, I can take prochelp.c

**Comment by tanabi** [comment]
@wyld-sw I'm on resolver.c then!  We're almost done.

**Comment by tanabi** [comment]
@wyld-sw timequeue.c is next for me ... looks like timequeue.c and prochelp.c are the last 2 files to document!!  Almost done!!

**Comment by wyld-sw** [comment]
@tanabi prochelp.c is done! (after a false start with last night's commit).

**Comment by tanabi** [comment]
FINISHED IT!!!

Before I can close this ticket, I want to make sure the docs build alright, so I will check that and make sure they look okay before calling it done :)

**Comment by tanabi** [comment]
In case anyone is wondering what's going on here ...

doxygen came back with many, many warnings and I'm going through and fixing all of them.  I'm around 75% complete or so I think.  This will be ready very soon, I just want to make sure the docs built start off on the right foot and aren't flooded with warnings -- especially since I have dreams of autobuilding and publishing them somewhere at some point :)

**Comment by tanabi** [comment]
I declare this done!!  Commit incoming.  I will put in a seperate issue to make a documentation artifact for use on the web.
