### ISSUE TITLE
AppVeyor build artifacts missing important things

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#330]
After
https://github.com/fuzzball-muck/fuzzball/pull/328
https://github.com/fuzzball-muck/fuzzball/commit/4d95345b1bf4ad2b311322ca0d3054392c6b3ba9
the Windows builds don't come with documentation. ```makefile.win``` is likely the appropriate file to fix this in, but I don't know how to do this.

**Comment by nyanster** [comment]
Windows builds also don't come with minimaldb after:
https://github.com/fuzzball-muck/fuzzball/commit/1d3be899e7c4a1042009addd3cf9a206056c7989
https://github.com/fuzzball-muck/fuzzball/pull/346

**Comment by nyanster** [comment]
@wyld-sw 
Do you think it's a good idea to have Windows builds come with source?  The reason why this stuff happens is that somewhere (appveyor.yml I think, not makefile.win) soooo much stuff gets deleted.

**Comment by nyanster** [comment]
I'd like to point out that our only evidence of these things is from the AppVeyor build artifacts: it's entirely possible if someone compiled Fuzzball on Windows themselves, nothing would be missing.

**Comment by nyanster** [comment]
though, that'd still be important if we ever get Fuzzball packaged for Windows
But yeah, I think the AppVeyor builds artifacts shouldn't delete as much as they do.

**Comment by wyld-sw** [comment]
I tend to agree. The website points to the artifacts page currently, I think.

**Comment by tanabi** [comment]
@nyanster @wyld-sw May as well include the source.  I think from a license standpoint it is also good to keep the source with the executables if at all possible.

It also enables a windows user to potentially later build their own binary from what they know is the source base their MUCK comes from if they ever need to -- this is a very unlikely use case, but its a possible one.

**Comment by wyld-sw** [comment]
Agreed. At one point certain decisions were made because "Windows users typically don't have their own compiler". Which is likely true, but shouldn't hinder the other 1%.

**Comment by tanabi** [comment]
@wyld-sw Microsoft now provides a free compiler that is good enough to build the MUCK, so certainly back in the day of MSVC costing money this was true.  These days, Windows users are not accustomed to building things and it is certainly a convenience to provide them with binaries -- but it is a lot less "necessary" than it used to be.

**Comment by nyanster** [comment]
> @wyld-sw Microsoft now provides a free compiler that is good enough to build the MUCK, so certainly back in the day of MSVC costing money this was true. These days, Windows users are not accustomed to building things and it is certainly a convenience to provide them with binaries -- but it is a lot less "necessary" than it used to be.

Ah!  I don't mean to stop providing binaries.  Just to remove nothing from the source, to have the source come with the binaries.  Maybe as it is, or maybe moved into a separate directory.  But somewhere in the AppVeyor .zip

**Comment by tanabi** [comment]
> 
> Ah! I don't mean to stop providing binaries. Just to remove nothing from the source, to have the source come with the binaries. Maybe as it is, or maybe moved into a separate directory. But somewhere in the AppVeyor .zip

@nyanster yeah I understand that -- my point was more towards back in "the day" the source code for a windows program was pretty much worthless to most people anyway.  Nowadays that's not the case, anyone can download a free MSVC compiler and build it.  But we should continue with the binaries.  Long story short, I'm agreeing with you 100% here. :)

**Comment by wyld-sw** [comment]
I just committed a change to place the "dbs" subfolder inside the Windows build. Technically that's probably blasphemy - since it usually is outside the game directory. I agree that we can probably put more inside the build, including src and include - are there things we should exclude, or just try to give them everything?

Also, I'm thinking that the lack of a Windows-friendly prochelp was the reason why we had the *.txt help files directly in game/data/. I know it's not ideal - but given the current help file format, are we OK with copying the *.txt back where they were?

**Comment by nyanster** [comment]
> I just committed a change to place the "dbs" subfolder inside the Windows build. Technically that's probably blasphemy - since it usually is outside the game directory. I agree that we can probably put more inside the build, including src and include - are there things we should exclude, or just try to give them everything?

Giving them absolutely everything is the best option.  I don't see a reason to strip anything.

> Also, I'm thinking that the lack of a Windows-friendly prochelp was the reason why we had the *.txt help files directly in game/data/. I know it's not ideal - but given the current help file format, are we OK with copying the *.txt back where they were?

I'm not okay with that.
Can't the Windows Makefile copy them correctly?  On the Unix build, make is what copies them from docs/ to game/data/, and it should be the same on Windows.  If not, I can put instructions in README_WINDOWS.md about needing to copy the help files manually.

**Comment by wyld-sw** [comment]
I think that the .zip file should only have files that the Windows build needs. I'm certain that many of the files in the tarball qualify, but not all.

What we had been doing is getting around the lack of prochelp on Windows. Moving the txt files broke the Windows build, but we can certainly copy them from the docs folder.

**Comment by nyanster** [comment]
> I think that the .zip file should only have files that the Windows build needs (I'm not going to bother omitting unix-only source files). I'm certain that many of the files in the tarball qualify, but not all.

It's just a hassle stripping stuff out. :P  An unnecessary one.  We could also strip Unix release tarballs of the .yml and .yaml files, but we don't.

> What we had been doing is getting around the lack of prochelp on Windows. Moving the txt files broke the Windows build, but we can certainly copy them from the docs folder.

Now that I think of it, we just need to add docs/ to the folder, just like dbs/ was just added.  Then whatever is in the Windows build process would be able to copy them, with a fix to the makefile.

**Comment by wyld-sw** [comment]
That's a great solution, @nyanster.

**Comment by wyld-sw** [comment]
src, include, and docs are now present in the artifact.
the appveyor process copies the *.txt help files. makefile.win was also a valid option, though this preserves the expectation that they would already be in the zip file.

Closing this issue. Please feel free to continue commenting.

**Comment by nyanster** [comment]
https://github.com/fuzzball-muck/fuzzball/commit/373a4f0f3fb16e6445e2cf7cdb7e2d91907da42b and https://github.com/fuzzball-muck/fuzzball/commit/cf2a391fe26d1746d827ecf4432e20bb009d058c look good to me, with one nitpick:
The info helpfiles like mpi-intro, etc are not included in the build artifact's data/info/ folder (neither is the info/ folder there at all)

**Comment by wyld-sw** [comment]
Good catch; I've put those files in docs/info for ease of copying, and updated GH pages. On a related note, I've updated fuzzball.org to link to GH pages.

**Comment by nyanster** [comment]
> Good catch; I've put those files in docs/info for ease of copying, and updated GH pages. On a related note, I've updated fuzzball.org to link to GH pages.

I think your commits muddle the intention of the docs folder.  We already had this problem solved in the unix build and makefile, and the same steps could've been done for the windows one.
