### ISSUE TITLE
Kill Kill ... and Rob

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#344]
There are two server commands that have never made any sense and are, at best, used for mischief and at worst just never used at all.

'rob' allows a user to steal pennies from another user if that user hasn't had the good sense to ```@lock me=me```.  It is primarily used by kids who read the help files and then just want to go around being a nuisance to people. :)  I know that's what I used it for in my young and stupid days!

'kill' allows you to pay money to sweep a player home, basically.  It is startlingly complicated, with at least 3 tune parameters dedicated to it and its own flag.  Usually MUCKs require both participants in a 'kill' to be set KILL_OK for it to work.  I have never seen anyone actually do this in 30-some years of MUCKing and I'm pretty confident in saying nobody uses this command.

HOWEVER ...  Just in case these commands are still desirable, we will provide backwards compatibility in the form of MUF implementations.  Admins can choose to install these commands if they wish and they will mimic the C versions very closely.

This task will be to:

* Write MUF versions of rob and kill -- do this *first* so we are sure they are available before removing the command.
* Remove rob and kill
* Remove kill's tune parameters
* KEEP KILL_OK ... Much as I'd like to get rid of the flag, I think that would cause lots of compatibility issues.  However, we can now use KILL_OK for something else and potentially rename it in the future.
* Either relocate do_give (the only other thing in rob.c) to look.c so it "lives with" do_score, or move do_score to rob.c and rename rob.c to something more descriptive like "value.c" or "pennies.c" or the like.

@tanabi has volunteered to do the MUF portion.  Probably he and @wyld-sw will play rock-paper-scissors to see who removes the C code :)

**Comment by nyanster** [comment]
Sounds OK with me!  Though I assume there may be some minor uses for kill in a RPG-themed MUCKs and on MUCKs without sweep.  But those seem minor, and you're writing replacements, so this seems good. :3
Reminds me of how I want to add a sysparm to have pages cost pennies again, since that's something I want to experiment with when I run a MUCK, to explore the social effects.  (that sysparm would always be off by default!  or with a cost of 0, since it'd likely be an int sysparm)

**Comment by tanabi** [comment]
@nyanster I would think any RPG-themed MUCKs would have their own 'combat system' ... The 'kill' feature as implemented on the server doesn't seem terribly conducive to RP.  But yes, certainly, we will be making replacements so anyone out there who surprises me and actually uses these commands will be covered.  Not taking away features is very important; ultimately we cannot make assumptions about what our users do, even if they're probably really good assumptions.

**Comment by nyanster** [comment]
> Not taking away features is very important; ultimately we cannot make assumptions about what our users do, even if they're probably really good assumptions.

True!  Though, on the topic of the slightly-crazy idea of removing features, @wyld-sw and I have thought of maybe making a toggle for MCP GUI in preparation for removing it.

**Comment by aidanPB** [comment]
If I recall correctly, `rob` is also how a player's use messages (`@succ`, `@fail`, `@osucc`, and `@ofail`) get triggered. This "side-effect" is probably the reason for any non-nuisance uses (and probably many nuisance uses!) of `rob`.
Agreed that the `kill` builtin isn't that useful to MUCK-based RPGs, though the effect provided as a MUF primitive or in a standard library might be quite welcome.

**Comment by tanabi** [comment]
@aidanPB The funny thing is, if you read the "help" docs for rob, it says just that -- use it to test your messages.  HOWEVER!  In the C code, you'll find that if you try to rob yourself it short circuits and doesn't let you try it.  At some point in the past, what you said was correct (as evidenced by the documentation), but in modern FB it doesn't work that way any more.

**Comment by tanabi** [comment]
> > Not taking away features is very important; ultimately we cannot make assumptions about what our users do, even if they're probably really good assumptions.
> 
> True! Though, on the topic of the slightly-crazy idea of removing features, @wyld-sw and I have thought of maybe making a toggle for MCP GUI in preparation for removing it.

I'm curious if any client other than trebuchet supports MCP GUI.  Maybe do that little bit of research before removing the feature.  However, I'm largely in agreement with this idea as well.  And if Trebuchet is the only supporter, then I say off with its head :)

**Comment by nyanster** [comment]
> I'm curious if any client other than trebuchet supports MCP GUI. Maybe do that little bit of research before removing the feature. However, I'm largely in agreement with this idea as well. And if Trebuchet is the only supporter, then I say off with its head :)

As far as I know, Trebuchet is the only one.
@revarbat 
Do you know of any other MCP GUI clients?

**Comment by tanabi** [comment]
> > I'm curious if any client other than trebuchet supports MCP GUI. Maybe do that little bit of research before removing the feature. However, I'm largely in agreement with this idea as well. And if Trebuchet is the only supporter, then I say off with its head :)
> 
> As far as I know, Trebuchet is the only one.
> @revarbat
> Do you know of any other MCP GUI clients?

There's MMCP which I don't know if thats the same thing -- this claims Trebuchet doesn't support it, so I would say its probably not the same thing.  MCP may be largely dead.  https://en.wikipedia.org/wiki/MUD_client

**Comment by nyanster** [comment]
> There's MMCP which I don't know if thats the same thing -- this claims Trebuchet doesn't support it, so I would say its probably not the same thing. MCP may be largely dead. https://en.wikipedia.org/wiki/MUD_client

No idea what MMCP is: what is it?
MCP itself I'd like to keep, though.  I think it has potential.  And doesn't Hope Island use MCP for weather data?

**Comment by nyanster** [comment]
Ah, the answer to my own question:
https://tintin.sourceforge.io/protocols/mmcp/

**Comment by tanabi** [comment]
Looks like tkMOO (which I've never heard of) supports MCP.  http://www.awns.com/tkMOO-light/

It is, in fact, the reference implementation it looks like: http://www.awns.com/mcp/

MMCP turns out to be "Mud Master Chat Protocol".  MCCP is "Mud Client Compression Protocol".  While similar names to MCP, they are unrelated.

zMUD claims to support it.  http://www.zuggsoft.com/zmud/zmudinfo.htm

And yeah, Hope does use MCP, and I want to keep MCP.  But I think MCP as a protocol is largely unused.

**Comment by aidanPB** [comment]
> @aidanPB The funny thing is, if you read the "help" docs for rob, it says just that -- use it to test your messages. HOWEVER! In the C code, you'll find that if you try to rob yourself it short circuits and doesn't let you try it. At some point in the past, what you said was correct (as evidenced by the documentation), but in modern FB it doesn't work that way any more.

I haven't read the C to verify this, but presumably the messages are still triggered when somebody else robs (or fails to rob) you. That's what I was referring to.

> I'm curious if any client other than trebuchet supports MCP GUI. Maybe do that little bit of research before removing the feature. However, I'm largely in agreement with this idea as well. And if Trebuchet is the only supporter, then I say off with its head :)

If native MCP GUI support gets axed, I might take a stab at writing a library for it. Even though it doesn't natively support MCP at all, MUSHclient is sufficiently scriptable/programmable that someone could write a plugin for it that provides MCP GUI support.

**Comment by wyld-sw** [comment]
Oops, that was me, two years, ago, adding that inability to rob yourself. Silly me thinking about the semantics, and not the useful side effects!

I can revert, or we can just support the upcoming MUF version.

**Comment by nyanster** [comment]
So the C and MUF versions behave _the same_, it'd probably be a good idea to add that self-rob functionality back.

**Comment by nyanster** [comment]
And edit it back without reverting!  I don't want two years of lost commits ;w;

**Comment by wyld-sw** [comment]
I think the point is that the C version will be removed. And only the one commit will be reverted. It'll probably show up in the log as a new commit, nothing to worry about :)

**Comment by wyld-sw** [comment]
@tanabi, your docs mention you'd rather fix the documentation over putting the "rob yourself" of it all back in. I'm willing to do either - what are you planning to build in to the MUF rob? I'll make it match that.

**Comment by tanabi** [comment]
> @tanabi, your docs mention you'd rather fix the documentation over putting the "rob yourself" of it all back in. I'm willing to do either - what are you planning to build in to the MUF rob? I'll make it match that.

@wyld-sw  I think from the responses we've got, the "rob yourself" semantic has a value, so we should have the MUF work as-documented rather than the C version.

**Comment by tanabi** [comment]
> If native MCP GUI support gets axed, I might take a stab at writing a library for it. Even though it doesn't natively support MCP at all, MUSHclient is sufficiently scriptable/programmable that someone could write a plugin for it that provides MCP GUI support.

@aidanPB I think if there's a genuine interest in reviving MCP GUI, then we should keep the feature in the MUCK.  My general stance is I don't like to take away a feature because you never know who might be using it.  In the case of MCP-GUI, we know people who use Trebuchet MUCK client *might* be using it, and even so it just supports a very limited amount of commands.

However, if you were to add support to a major MU* client, it could turn into an MCP GUI renaissance which would be cool.  Guess it depends how serious you are about that :)

**Comment by nyanster** [comment]
tbh if there were to be a GUI renaissance, a new MCP package would be the better option than the Windows95-modeled MCP GUI package
GUI **does** intrigue me, though.

**Comment by tanabi** [comment]
@nyanster Fair point.  I think you've won me over to full agreement on axing MCP-GUI.

**Comment by wyld-sw** [comment]
Is there value in adding a #define for it, defaulted to off, for a cycle - or should we just rip it out?

**Comment by tanabi** [comment]
@wyld-sw I vote rip it, it would be an awful lot of code to temporarily disable.  Due to the nature of GIT and the relatively isolated nature of the code, we can very easily re-integrate it if someone comes out of the wood-works and needs it.

**Comment by nyanster** [comment]
> Is there value in adding a #define for it, defaulted to off, for a cycle - or should we just rip it out without waiting?

> @wyld-sw I vote rip it, it would be an awful lot of code to temporarily disable. Due to the nature of GIT and the relatively isolated nature of the code, we can very easily re-integrate it if someone comes out of the wood-works and needs it.

I'm fine either way.  I personally think disabling before removing is pretty safe, though, and was originally what I agreed with @wyld-sw on in an email.  I myself likely won't be doing the disabling or removing, though. :B  So don't let me hold you back!

**Comment by wyld-sw** [comment]
I'll make a separate issue on MCP GUI, just to track progress and timelines. But rob/kill, consider them gone! (I'll close this when I get around to that change)

**Comment by tanabi** [comment]
@wyld-sw don't close it til we have the MUF replacements. :)  I will try to program them up tonight.  Rob will take me about 5 minutes.  Kill is slightly more nuanced but won't take too long either.

**Comment by wyld-sw** [comment]
Yeah, I'm assuming you'll get it this before i do :)

**Comment by tanabi** [comment]
> Yeah, I'm assuming you'll get it this before i do :)

True.  I could do the C side as well easily enough, but I think @ register is probably a more immediate use of my time so I will tackle that as well.  We'll see who gets to the C part first, unless you have a particularly strong desire to own it :)

**Comment by wyld-sw** [comment]
Either way is fine. I can do the C code after the MUFs are available if you haven't done it already. Just let me know.

**Comment by tanabi** [comment]
> Either way is fine. I can do the C code after the MUFs are available if you haven't done it already. Just let me know.

Aye, cap'n!

**Comment by tanabi** [comment]
@wyld-sw cmd-kill and cmd-rob are now in the fuzzball MUF repo as a PR.  We're good to go here for removing these commands.

**Comment by revarbat** [comment]
No, I don't know of any clients that support MCP-GUI.  I rather heavily designed parts of it to use Tk, and honestly at this point, TCL/Tk is a dead, write-only language.  I once looked at rewriting Trebuchet in Python, but the MCP-GUI library was one of the larger reasons I was put off the task.

**Comment by revarbat** [comment]
My only real reason to want to keep MCP-GUI around is for @tunegui and the lsedit gui editor.

**Comment by tanabi** [comment]
@revarbat I actually made a python library to support MCP:

https://github.com/tanabi/pyfuzzball

However it probably wouldn't work great for your use case.  Its really only made for scripts that want to interact with the MUCK (for instance, it would work well for a python replacement of ups-notify.sh)

**Comment by nyanster** [comment]
> No, I don't know of any clients that support MCP-GUI. I rather heavily designed parts of it to use Tk, and honestly at this point, TCL/Tk is a dead, write-only language. I once looked at rewriting Trebuchet in Python, but the MCP-GUI library was one of the larger reasons I was put off the task.

Ah, I see...

> My only real reason to want to keep MCP-GUI around is for @tunegui and the lsedit gui editor.

Couldn't a graphical MUCK client do a GUI lsedit with ```dns-org-mud-moo-simpleedit```?
But, true, I wouldn't know how to replace @tunegui (which I haven't heard of until now!  I'll look into it.  I'll play with both) which I assume is different.

**Comment by revarbat** [comment]
Oh, I already wrote a python MCP library for MufSim, my MUF/MUV editor/compiler/debugger/muck semi-emulator.  https://pypi.org/project/mudclientprotocol/  It's the MCP-GUI package itself that is really obnoxious.

**Comment by nyanster** [comment]
> Oh, I already wrote a python MCP library for MufSim, my MUF/MUV editor/compiler/debugger/muck semi-emulator. https://pypi.org/project/mudclientprotocol/ It's the MCP-GUI package itself that is really obnoxious.

> mcp-cord

Oooh.  Exciting.  Gonna refer to
https://github.com/fuzzball-muck/fuzzball/issues/302
So the reverse refer shows up there and I don't lose this...

**Comment by tanabi** [comment]
> Oh, I already wrote a python MCP library for MufSim, my MUF/MUV editor/compiler/debugger/muck semi-emulator. It's the MCP-GUI package itself that is really obnoxious.
> 
> MufSim's github: https://github.com/revarbat/mufsim
> MCP's PyPi: https://pypi.org/project/mudclientprotocol/

Aww man, I wish I knew about that, I wasted so many bloody days on mine and I really didn't want to make it ;)  And look at you, on pypi and everything.  I actually did google for a library but I clearly wasn't searching for the right thing.

**Comment by tanabi** [comment]
... though my library has full documentation, so, I'll give myself credit for that one ;)

**Comment by revarbat** [comment]
> I actually did google for a library but I clearly wasn't searching for the right thing.

Yeah, searching for MCP on PyPi lists a lot of libraries used with MCP microcontrollers.

**Comment by revarbat** [comment]
The real reason to keep MCP in general is the simpleedit package, especially for editing MUF programs with @mcpedit. Though it does have problems with truncating long MUF programs.  Mostly hit this issue with the 4000 line long cmd-page, as I recall.

**Comment by wyld-sw** [comment]
Closing this as an issue (rob and kill have been removed), but feel free to keep discussing. Will make a specific issue about MCP GUI - or someone else can, if I get distracted by work.

**Comment by revarbat** [comment]
Oh, MCP-GUI is also used for the bulletin board GUI, if I remember correctly.
