### ISSUE TITLE
Maybe use GitHub pages

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#347]
After
https://github.com/fuzzball-muck/muckman/issues/2
I realised we could do the same thing here.

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
If we select "master branch /docs folder" our html and text documentation will be readable in a browser.  Importantly the three html files.

**Comment by wyld-sw** [comment]
May need an index.html page (or similar) in order for it to work.

**Comment by nyanster** [comment]
> May need an index.html page (or similar) in order for it to work.

Perhaps!  We can write one after enabling it, though.  It might support autoindexing.

**Comment by nyanster** [comment]
Ah.  No autoindex.  I'll write something short and easy.

**Comment by nyanster** [comment]
https://github.com/fuzzball-muck/fuzzball/commit/e1963f2ce17d45da48ed95e031783f1c7c101641
https://github.com/fuzzball-muck/fuzzball/commit/16a7a5c83e0ead43a0369159b8040cfe3f3f5456
https://github.com/fuzzball-muck/fuzzball/pull/348
https://github.com/fuzzball-muck/fuzzball/pull/349
Done.
