### ISSUE TITLE
Document YIELD and OVERT.

### ISSUE THREAD

**Issue by aidanPB** [fuzzball-muck/fuzzball#35]
I could've sworn I saw reasonably complete documentation for what the YIELD and OVERT flags did, once, but I can't find it any more. The best I've been able to come up with is a [couple of comments](https://github.com/fuzzball-muck/fuzzball/blob/master/src/match.c#L538) in the middle of src/match.c. They're certainly not documented in the online help with the other user-visible flags, which is something that needs fixing ASAP.

**Comment by wyld-sw** [comment]
Thanks for the heads-up. I've added the same entry for both YIELD and OVERT in the online help, pulled from the fb6.11 changelog. There are many other places in the help where flags are listed, and these entries should be more complete after a full documentation audit.
