### ISSUE TITLE
Yield and Overt on Things

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#351]
I have a question (when you read this, Wyld, you could put the Question label on this issue)
Yield and Overt are only allowed on Rooms and Things.  However, the documentation only describes their effect on Rooms, and I don't grok any special meaning for those flags on Things from reading the code I've quickly grepped through.
Does anyone know what Yield and Overt mean for Things?

**Comment by wyld-sw** [comment]
I'm not sure about Things. I'll need to check in the code to be sure, but it might just be a documentation error.

**Comment by nyanster** [comment]
There IS some code that involves making sure only Rooms and Things can be set Y/O, so there is some code related.  I just don't see it having a real effect.

**Comment by wyld-sw** [comment]
I have no doubt about that; just it may be that the THING part isn’t needed. Stay tuned!

**Comment by wyld-sw** [comment]
The main logic for those flags seem to be in a couple of lines in match.c - and they both reference locations. So I'm pretty sure they just have a function on rooms at this point.

**Comment by aidanPB** [comment]
A Thing can be the location of a Player, if the Thing is set `VEHICLE`. So `YIELD` at least _seems_ like it might be useful/meaningful on Things. `OVERT` is pretty difficult to imagine having any relevancy on Things, though.

**Comment by nyanster** [comment]
> A Thing can be the location of a Player, if the Thing is set `VEHICLE`. So `YIELD` at least _seems_ like it might be useful/meaningful on Things. `OVERT` is pretty difficult to imagine having any relevancy on Things, though.

@aidanPB 
Oh!  Good point, thank you!!

**Comment by nyanster** [comment]
TODO note to self: can vehicles go inside vehicles?
in any case, may as well allow both of them if one's allowed and it has the same sorta meaning
(except, when I make Obscured work on a program, there'll be no point to have a Y flag allowed on programs)

**Comment by tanabi** [comment]
> TODO note to self: can vehicles go inside vehicles?
> in any case, may as well allow both of them if one's allowed and it has the same sorta meaning
> (except, when I make Obscured work on a program, there'll be no point to have a Y flag allowed on programs)

Please feel free to test to be sure, but I have seen a number of places in the C code that appear to support vehicles in vehicles, so I think it is possible.  However, just because one random bit of MUCK C code has support for it doesn't mean it actually works.

**Comment by wyld-sw** [comment]
Thanks @aidanPB! I always forget about the basic thing-vehicles that are recognized.

**Comment by wyld-sw** [comment]
Removed tp_match_yield with 94c2d04.

**Comment by nyanster** [comment]
> Removed tp_enable_match_yield with [04e18d3](https://github.com/fuzzball-muck/fuzzball/commit/04e18d3869866202bbd040fcb592e6a6ebbc626d).

Oh wow, already!  Well, thank you! :D  I guess I'd better get to working on the dbref command and toward the Obscured flag.  (and on changesfb7...)
