### ISSUE TITLE
Give: Sometimes it IS necessary

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#353]
I am experimenting with some MUF that costs money.  As a wizard, I need to give myself more money because I've run out of pennies.  This used to work.  However, now:

```
give me=1000  
That seems unnecessary.
```

While I agree that may seem unnecessary for a player to do that to themselves, wizards should be unrestricted.  @wyld-sw stop messing with these semantics ;)

There are workarounds but .... that seems unnecessary :)

**Comment by tanabi** [comment]
Anyone who needs a workaround, this will work:

```
@muf me @ 1000 addpennies
```

but I still think this should be fixed and probably a grep for "This seems unnecessary" done to make sure there's not other use cases that are blocked.

**Comment by wyld-sw** [comment]
Pretty sure it was just rob, kill, and give. I can remove the checks in the morning, if there are no PRs to do it.

**Comment by wyld-sw** [comment]
Due to the wording of that message, it may not have just been a whim. But I really don’t remember. Still a good idea to revert the change to give.

**Comment by tanabi** [comment]
> Pretty sure it was just rob, kill, and give. I can remove the checks in the morning, if there are no PRs to do it.

Don't bother fixing kill or rob of course.  Kill doesn't have this message, incidentally, as I just went through it again line by line to make cmd-kill -- so it may just be rob and give.

**Comment by wyld-sw** [comment]
Necessity re-necessarized.
