### ISSUE TITLE
A place/way for devs and users to communicate

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#379]
There are things that'd be nice:

1. A way for developers and users to quickly chat
2. A place where both on-topic and off-topic and mixing topics are good (as currently, we often use issues or pull requests to discuss many, many topics rather than sorting them into their own issues)
3. A developer MUCK, sorta like what M\*U\*S\*H is to PennMUSH, or less likely, what LambdaMOO (MOO) is to LambdaMOO (server)

Our options are:

1. Ideally: our own MUCK.  This was actually started before but me and @wyld-sw weren't using it much so I believe it's down now.  To do this, we'd need to discuss how we'd handle upgrades and updates, and how often we'd do it, and how we'd do it while still keeping the MUCK usable
2. An IRC channel.  Easy, fast, accessible.  Rizon works very well, and has an official webclient that's very newb-friendly.  Anthrochat, Furnet, or freenode might also work.  I think this might be a good idea even after a dev MUCK is made.  But it's the best stopgap for before a dev MUCK is made, for sure.
3. A Jabber (XMPP) group chat.  Far more modern than IRC.  One notable con: unlike IRC, and unlike MUCKs with guests enabled, this requires an account to use.  There's no guest/unregisterednick equivalent.

Right now we all communicate by GitHub, and some of us communicate individual-to-individual via email (no mailing lists (yet))

**Comment by wyld-sw** [comment]
There is currently a Slack workspace, with a few developers already there (hasn't been used for a while). I know it's closed-source; I wonder if https://github.com/Snegovikufa/TeamWords or one of its forks would work. I'm certainly open to another method.

Also, a dev muck is a good idea. Possibly even one for demo purposes.

**Comment by tanabi** [comment]
I'm most in favor of a demo MUCK.  I would be happy to host it, I have a VM out there I'm already using for other stuff (or I can spin up a VM just for the MUCK if other devs need to have shell on it).  I use digital ocean, really good quality and cheap.

I don't want to use slack cause I use that for work and it gets weird when you log into multiple things with it .... and honestly I don't want *another* window open just to talk to you guys.  No offense but I would simply never show up there if I have to be on a chat protocol I don't otherwise use.  :)  I'm already running a MUCK client pretty much all the time, it would be no  big deal for me to log in there as well.

**Comment by wyld-sw** [comment]
That sounds like a good solution, @tanabi. Thanks for the offer! I agree that we should figure out a sensible approach for updates, but if you'd like to spin up an instance of FB7 while we figure that out, that would be great! Thanks again!

**Comment by nyanster** [comment]
> There is currently a Slack workspace, with a few developers already there (hasn't been used for a while). I know it's closed-source; I wonder if https://github.com/Snegovikufa/TeamWords or one of its forks would work. I'm certainly open to another method.

I am unlikely to use Slack. xP

> Also, a dev muck is a good idea. Possibly even one for demo purposes.

Dev and demo, yup.  Sounds good.  It's easy to imagine a OOC world structured somewhat like Realms MUCK is ICly structured: with various demo/realms/zones with different purposes all branching off a single nexus.  So areas meant to demonstrate features could be an separate from areas where people just chat.

> I'm most in favor of a demo MUCK. I would be happy to host it, I have a VM out there I'm already using for other stuff (or I can spin up a VM just for the MUCK if other devs need to have shell on it). I use digital ocean, really good quality and cheap.

I think @wyld-sw already has a spot to run a MUCK, as he ran one before on the fuzzball.org domain.  I'm not sure about the details.
but ayyyy, yeah, I've also used DigitalOcean before, it's good.  I've enjoyed my experience with them (other than that of the BSDs, they only have FreeBSD and not OpenBSD :P )

> I don't want to use slack cause I use that for work and it gets weird when you log into multiple things with it .... and honestly I don't want _another_ window open just to talk to you guys. No offense but I would simply never show up there if I have to be on a chat protocol I don't otherwise use. :) I'm already running a MUCK client pretty much all the time, it would be no big deal for me to log in there as well.

\*nod\*
You don't have an IRC client window already open? :P  hhhehehe

But yeah, all the options I listed in the issue's OP are fine with me, so whatever works with you guys is good.  I do think a MUCK is the best option, for while IRC on its own is slightly better for pure chat purposes than a MUCK is, we may as well consolidate pure chat with the dev MUCK we will probably be having no matter what.

I'm fine with this issue staying open to discuss said future dev MUCK, or having it closed for a new issue to take that role.  Either way. :D  I'm happy I finally made this issue rather than just doing this through email :B  now this info and ideas are public

**Comment by nyanster** [comment]
As for updates, the biggest question is: update with every release, and be the first MUCK to do so?  At the current pace, that'd be very slow.  Or update with every commit (unlikely) or update once a night from master?
I apologise for not having done much in the past on the devmuck we tried xP  The devmuck WAS useful for me playing with the ! command and uptime commands, though.

and I do have things I am planning to do soon (tm) as for code, unrelatedly

**Comment by tanabi** [comment]
> As for updates, the biggest question is: update with every release, and be the first MUCK to do so? At the current pace, that'd be very slow. Or update with every commit (unlikely) or update once a night from master? The person in control of the machine would have to take daily backups, then, or set up a cron job to do so.
> I apologise for not having done much in the past on the devmuck we tried xP The devmuck WAS useful for me playing with the ! command and uptime commands, though.
> 
> more interestingly will be how to keep the devmuck's db in sync with the advancedb/moderndb/whateverdb even as those dbs change in the git repo
> 
> and I do have things I am planning to do soon (tm) as for code, unrelatedly

I will host this on my existing machine (unless @wyld-sw  wants to do it, though he already told me to do it).  If folks want shell to it later, I can always move it pretty easy.

Here's some thoughts.  A python script (or whatever language -- I would do it in python cause that's my go-to for this kind of thing, but just as long as its easy to deal with) could be used to concatenate databases.  It would have to be smart enough to renumber the second DB.  The second DB could have a marker object that specifies what the first 'new' ref in that DB is.

So you would do like ```python3 dbcat.py advancedb.muf std-db.new > std-db.really-new``` or similar and it would smartly do the concatenation.  This should be ~fairly~ simple.  All refs lower than the marker object would be deleted in std-db.new; we would start the db with advancedb.muf then concatinate it with std-db.new starting with the marker object and re-numbering as we go.

As for code updates, I think the simple thing would be to have the code be a git pull of the source.  If there are updates, build, install, and restart the test MUCK.  The cron could do this every hour just to make it easy, or every day so its more predictable.

**Comment by tanabi** [comment]
Almost ready ... any preference as to which db to use?  I usually just use advancedb but I don't really care.

**Comment by wyld-sw** [comment]
I would suggest advancedb for now.

**Comment by nyanster** [comment]
I agree with using advancedb, as it's likely to be the one that evolves into a new db.

**Comment by tanabi** [comment]
> I agree with using advancedb, as it's likely to be the one that evolves into a new db.

I have an idea.... let's do that!

**Comment by tanabi** [comment]
Okay ... MUCK is here:

preview.tigerdile.com
port 4201
Secure port 4202

Wyld, point muck.fuzzball.org to IP 104.236.44.181 or use CNAME preview.tigerdile.com

Registration is OFF so you can use 'create username password' at the title screen to make your guy.  I haven't done any setup other than making the Marker Object for future dbcat-ing.

**Comment by tanabi** [comment]
@wyld-sw don't close this until I do the auto-update script.  I will do that tomorrow.  We should probably have some loose policies about wizard bits and MUCKER bits.  I would recommend only people who have submitted a PR can be wizards and pretty much anyone can have an M3 (though they must ask for it).

Also thinking maybe we make a grep'd version of the command log available on the web.  Or maybe a MUF that listens to all the rooms and records things in some way.  The idea being that our discussions here continue to exist, our discussions there are farts in the wind.  Not sure how much it matters but something to consider.

**Comment by wyld-sw** [comment]
Ok, DNS should be set up!

**Comment by tanabi** [comment]
@wyld-sw nyanster requested we use a real cert for this.  I actually get real certs for free, but I need the owner of fuzzball.org (presumably you) to assist.  It emails certain addresses @ fuzzball.org to verify ownership.  The easiest way to do this would be interactively, where I make the cert while you're on a MUCK where I can ask you questions.  After this is done we can close this one.

**Comment by tanabi** [comment]
(as a note, the auto-restart / rebuild works and has already happened at least once for realsies!  It checks for updates every hour)

**Comment by nyanster** [comment]
> After this is done we can close this one.

After it's done and the devMUCK (particularly the connection info) is documented somewhere. ;3  Preferably both in README.md and https://www.fuzzball.org/
I can do the former, of course, but only @wyld-sw can do the latter.

**Comment by tanabi** [comment]
We have ordered the cert.  I probably won't install it til tonight but (my part) is almost done.

**Comment by tanabi** [comment]
Real cert is in.  I can never remember the order of concat's needed to make a pem so hopefully its right :D  Let me know if its not.

**Comment by nyanster** [comment]
> Real cert is in. I can never remember the order of concat's needed to make a pem so hopefully its right :D Let me know if its not.

Can confirm certificate is alright, and all valid.  Worked with OpenBSD nc, Firefox, and Chrome.

**Comment by tanabi** [comment]
Okay.  @wyld-sw you can close this, optionally you can add the MUCK to fuzzball.org website as well, but this is all set.

**Comment by wyld-sw** [comment]
Brief information added to fuzzball.org, let me know if there needs to be more. I'll eventually get around to presenting the links a different way too.
