### ISSUE TITLE
status command does not work in advancedb

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#389]
On the devmuck, I noticed I couldn't use ```status``` to set my status.  It's because MPI ```store``` didn't have permission to set the prop on me.  @tanabi suggested it's because the command should be blessed, but isn't.
I wonder how long its been like this: the status command works on HLM, which presumably has the same/similar code.

**Comment by wyld-sw** [comment]
Probably since property blessing was introduced in FB6. A lot of MPI that used to "just work" needed to work with blessed props. I can update the database if no one beats me to it.

**Comment by wyld-sw** [comment]
Done!

**Comment by nyanster** [comment]
Okay!
https://github.com/fuzzball-muck/fuzzball/commit/776a948e3d94905349f5217a731efc68c89ef42a
Linking this commit to record it.
