### ISSUE TITLE
spoof doesn't work in advancedb

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#392]
Tested on muck.fuzzball.org (port 4202 for you readers out there. unsecure connections at port 4201)
```
spoof uwu
Programmer Error.  Please tell Keeper what you typed, and the following message.
cmd-spoof.muf(#72), line 130; CALL: Program not compilable.
System stack backtrace:
  0) cmd-spoof.muf(#72) line 130, in notify_and_store(:
130:     1 swap "saypose" notify_exclude_ignorers (notify_exclude}  Honor say #ignore Natasha@HLM 20 January 2003 )
  1) cmd-spoof.muf(#72) line 327, in default-spoof(:
327:         spoof-tattletale
  2) cmd-spoof.muf(#72) line 912, in spoof(:
912:     else
  3) cmd-spoof.muf(#72) line 928, in spoof-main(:
928:         dup int? not if
*done*
```
And with no arguments:
```
spoof
Programmer Error.  Please tell Keeper what you typed, and the following message.
cmd-spoof.muf(#72), line 300; PMATCH: Empty string argument.
System stack backtrace:
  0) cmd-spoof.muf(#72) line 300, in do-pmatch(:
300:         .pmatch
  1) cmd-spoof.muf(#72) line 307, in matches-player-name(:
307:         do-pmatch ok?
  2) cmd-spoof.muf(#72) line 323, in default-spoof(:
323:     dup matches-player-name ok? if
  3) cmd-spoof.muf(#72) line 912, in spoof(:
912:     else
  4) cmd-spoof.muf(#72) line 928, in spoof-main(:
928:         dup int? not if
*done*
```
However, spoof works on Here Lie Monsters.

Before 7.00b2 comes out, we really should test that every db works, and every command in every db works.  That can be its own issue, if that'll help.

**Comment by nyanster** [comment]
I'm not entirely sure how milestones work, but this could be set to a "workingdbs" milestone, and a "bug" label

**Comment by wyld-sw** [comment]
lib-ignore had a mismatched parenthesis, causing it to fail its compile.

I'll add code to cmd-spoof so that calling it with no arguments does nothing. Other options are an error message, or "( )".

**Comment by nyanster** [comment]
> lib-ignore had a mismatched parenthesis, causing it to fail its compile.

Okidoki!
> I'll add code to cmd-spoof so that calling it with no arguments does nothing. Other options are an error message, or "( )".

On hlm it does ```(  )```

**Comment by wyld-sw** [comment]
We can do that. Seems a bit like having `say` output nothing with no arguments, but I can see a case for spoof at least.

**Comment by nyanster** [comment]
I don't see the case for it, hence the "just for reference" :B Well, actually, a potential case is the clear the ```spoof #recent``` buffer.  So I guess I see something!  What do you see?

**Comment by wyld-sw** [comment]
Hmm, other than changing notify's to use stoplights, HLMs code is identical to ours. Briefly reading through the logic, it may behave differently if there are certain properties set on the trigger action. Maybe HLM's spoof action has those?

Certainly still need to fix the pmatch crash.

**Comment by wyld-sw** [comment]
I didn't see your "just for reference" since you added it after the initial post. :B  Certainly `#recent` is one case, and I guess to convey suspense, but that can be done with `...`. ASCII art? I got nothing. Mainly it's better than how the builtin say works, for sure. :)

**Comment by wyld-sw** [comment]
Settled on having spoof do nothing if there are no arguments.

**Comment by tanabi** [comment]
@wyld-sw Not to be a pain in the rear on a closed issue, but shouldn't no arguments trigger a help message?  That would be more consistent with other commands that require arguments.

**Comment by wyld-sw** [comment]
That was the third option! Commit incoming, good idea.
