### ISSUE TITLE
Better providing contact info

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#396]
I've noticed there's not really a real place in the tarball/repo that lists all the websites available (the fuzzball website is linked in README.md, but the GitHub repository **isn't**.  Though, users could find the GitHub repository via the website) nor the feedback email address (though that's available in configure.ac...)

I think adding a CONTACT file, or re-organising README.md a little would be nice.  It'd also be a spot to put in the connection info for the dev MUCK.

But!  I want to ask you guys what option you guys prefer:

- create CONTACT file
- re-organise README.md

I can do either of those. :3

**Comment by tanabi** [comment]
I prefer re-organizing README.md ... I don't like scattering things around too much personally.

**Comment by wyld-sw** [comment]
Added repo URL and feedback email to README.md
