### ISSUE TITLE
MUCK Auto-Restart Script

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#397]
This is something I want for Hope Island but its generally useful.

A script, which can be triggered by cron, to auto restart the MUCK.  Some kind of restart.sh replacement or cron script are both acceptable solutions, or a restart.sh wrapper.  Open to more clever thoughts as well.

**Comment by nyanster** [comment]
To restart it for what purpose?  I'm trying to understand.  What's restart.sh btw?  Do you mean fb-restart?  If so, why does it need a wrapper, if fb-restart can be used without arguments?

**Comment by tanabi** [comment]
> To restart it for what purpose? I'm trying to understand. What's restart.sh btw? Do you mean fb-restart? If so, why does it need a wrapper, if fb-restart can be used without arguments?

So Hope Island crashes sometimes cause reasons.  Usually me or @wyld-sw reasons.  We want it to come back up again when it crashes without requiring getting Sheridan over there to poke it with a stick.

**Comment by nyanster** [comment]
> > To restart it for what purpose? I'm trying to understand. What's restart.sh btw? Do you mean fb-restart? If so, why does it need a wrapper, if fb-restart can be used without arguments?
> 
> So Hope Island crashes sometimes cause reasons. Usually me or @wyld-sw reasons. We want it to come back up again when it crashes without requiring getting Sheridan over there to poke it with a stick.

Ahaaa, to start it after it crasheson its own...  I see, now.  I'll think about this.
IIRC, you could just have cron run fb-restart every few minutes, since it doesn't start a new server if a MUCK is already running.
https://github.com/fuzzball-muck/fuzzball/blob/master/game/restart.in#L94
I (or you) would want to confirm this before doing this, though.  I'm currently playing Morrowind, so I won't right now but can later. xP

**Comment by nyanster** [comment]
> Ahaaa, to start it after it crashes on its own... I see, now. I'll think about this.
> IIRC, you could just have cron run fb-restart every few minutes, since it doesn't start a new server if a MUCK is already running.
> https://github.com/fuzzball-muck/fuzzball/blob/master/game/restart.in#L94
> I (or you) would want to confirm this before doing this, though. I'm currently playing Morrowind, so I won't right now but can later. xP

note to self since I'm not on my usual computer: examine making aborted restart attempts return a non-zero value (it's possible, but I want to figure out the best combo of error numbers, especially since fbmuck can return its own numbers here, if it runs)

**Comment by nyanster** [comment]
Oops, I really didn't do this one as soon as I said I would!  It was very quick though, I ran through fb-restart with sh -x and sh -xv and read every line:
When a MUCK is already running, re-running fb-restart checks for that already-running MUCK, and if one is already running, it goes no further than its checks.
The checks aren't destructive in any way, and don't seem to have any side effects.  (well, other than the last-accessed, i.e. last-read time being changed on a file which is read, fbmuck.pid.  I don't think this affects fuzzball in any way, though)

Therefore:
@tanabi , you can feel free to just have fb-restart in cron, to run every five minutes or so (or even every one minute) and there'll be no downside.  I checked it with ```time``` too and found minimal impact.  It's a fast, short check.
This is assuming only one MUCK is running on the machine.  I know when multiple are running, things differ, and I didn't check that.

**Comment by tanabi** [comment]
Well that was easy! :)
