### ISSUE TITLE
Fix Memory Leak in MUF Editor

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#406]
While documenting edit.c, I found a memory leak.  This will be documented as a TODO in my code, but as it is a memory leak, I thought it serious enough to warrant a ticket.

In edit.c, in the 'editor' function, there is a block of code that looks like this:

```
            if (word[1] &&
                (word[1][0] == '.'
                 || (word[1][0] >= '0' && word[1][0] <= '9'))) {
                notify(player, "Invalid macro name.");
                return;
            }
```
A couple lines above that, you will see:

```
        word[i] = alloc_string(buf);
```

As you can see in the first code block, we are using word[1] which is an allocated string but we are not de-allocating it before returning.  'word' is not static so it is never cleaned up.

Elsewhere in the same function, before returning, you'll see a block of code similar to:

```
            for (; i >= 0; i--) {
                if (word[i])
                    free((void *) word[i]);
            }
```

Use code similar to that to do the cleanup (the if(word[i]) and casting of word is not necessary and may have already been removed elsewhere in this code ... my working copy is a little old).

**Comment by wyld-sw** [comment]
Fixed in 503e5e4.
