### ISSUE TITLE
at-objedit not working on dev MUCK

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#410]
```
@objedit me
Programmer Error.  Please tell Keeper what you typed, and the following message.
lib-optionsgui.muf(#16), line 1350; CALL: PUBLIC or WIZCALL function not found. (2)
System stack backtrace:
  0) lib-optionsgui.muf(#16) line 1350, in gui_options_process(dscr=9, caller_ctx=1{"target":#166}, save_cb='#57'saveall, title="Object Editor: Sava(#166)", optionsinfo=25{0:10{...} 1:7{...} 2:9{...} 3:9{...} 4:7{...} 5:7{...} 6:7{...} 7:10{...}_}:
1350:             menu_options_process
  1) cmd-@objeditgui.muf(#57) line 952, in main(args="me", targ=#166, context=1{"target":#166}:
952: ;
*done*
```

Not entirely relatedly:
I was asking someone what MCP-GUI programs she knew about, and she mentioned one I'd never heard of before.  Two, actually.  at-objedit and at-tunegui
She said she uses at-objedit allll the time.  Very often, at least.  So this is something we need to think about if/when we remove MCP-GUI or discuss that.

**Comment by nyanster** [comment]
I was allowed to link her screenshots:
objedit:
http://haven.bunny.blue/BunnyHaven/GUI.jpg
tunegui:
http://haven.bunny.blue/BunnyHaven/GUI%202.jpg

**Comment by wyld-sw** [comment]
@ objedit now works. In a local MUCK, it took re-compiling $lib/optionsmenu. On the actual dev MUCK, that didn't work - but @ uncompile did.

Certainly something to watch out for, and might indicate a subtle glitch in how libraries (lib-optionsgui) interact with other libraries (lib-optionsmenu). Then again, it may be simple.

**Comment by nyanster** [comment]
> @ objedit now works. In a local MUCK, it took re-compiling $lib/optionsmenu. On the actual dev MUCK, that didn't work - but @ uncompile did.
> 
> Certainly something to watch out for, and might indicate a subtle glitch in how libraries (lib-optionsgui) interact with other libraries (lib-optionsmenu). Then again, it may be simple.

Should you re-upload the advancedb after $lib/optionsmenu is re-compiled?  Or does that not make sense? (i.e. am I misunderstanding something)

Does this mean advancedb won't always work out of the box, as for this?

**Comment by nyanster** [comment]
> @ objedit now works. In a local MUCK, it took re-compiling $lib/optionsmenu. On the actual dev MUCK, that didn't work - but @ uncompile did.
> 
> Certainly something to watch out for, and might indicate a subtle glitch in how libraries (lib-optionsgui) interact with other libraries (lib-optionsmenu). Then again, it may be simple.

doesn't work, again >w>
```
@objedit me
Programmer Error.  Please tell Keeper what you typed, and the following message.
lib-optionsgui.muf(#16), line 1350; CALL: PUBLIC or WIZCALL function not found. (2)
```

**Comment by wyld-sw** [comment]
`@objedit` seems to work in the dev muck currently. If there's something still broken, we can re-open this.
