### ISSUE TITLE
page #mail not working on dev MUCK

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#421]
```
page #mail Tanabi=test
I don't recognize the player named "Tanabi"
page #mail Wyld=test
I don't recognize the player named "Wyld"
```

**Comment by nyanster** [comment]
I'll also note I don't have a wiz bit right now, which is what I originally meant to page @tanabi about. xP
I was trying to use the exclamation mark to bypass actions for unrelated things

**Comment by nyanster** [comment]
After @wyld-sw logged in, we could both send and read page #mail to each other, but I couldn't send page mail to @tanabi , still.

**Comment by nyanster** [comment]
Wyld_Too (Wyld's new mortal character) also couldn't page #mail Tanabi.

**Comment by nyanster** [comment]
page is also affected
```
page Wyld=owo
I don't recognize the player named "Wyld"
```

**Comment by tanabi** [comment]
This was because cmd-page doesn't have a W bit.  Why it matters to match player names is uncertain but probably due to cmd-page's complexity.  It may have its own pmatch mechanism of some sort.

**Comment by wyld-sw** [comment]
page now has a W in advancedb.

998e62b731af4c2de9dd5667af90cd0e9e364758
