### ISSUE TITLE
Provide MUF Primitives to Introspect Terminal Size

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#424]
So this is very much of a wish list item.  I'd love to be able to determine the window size in rows/columns so I can make more cool ASCII graphics.

This may be possible with telnet protocol.

https://tools.ietf.org/html/rfc1073

There's other hints on google that this may be doable.  However, I dunno how many MUCK clients support this kind of stuff.  Can't hurt to try and see what we can do, though.

Also add support for this to the MPI ```{right:....} {left:...}  {center:....}``` functions.

**Comment by wyld-sw** [comment]
I forget if we've already talked about this, but it might also be possible with the SSH protocol.

https://www.ietf.org/rfc/rfc4254.txt (6.7. Window Dimension Change Message)

**Comment by tanabi** [comment]
I felt really motivated to do this one tonight, even though it's not on the roadmap yet.  I've done the telnet protocol stuff -- and it actually works!  Or "works".  Telnetting with Linux command line works 100%.  tf will send the window size initial but doesn't update it if you resize the window.  I haven't tested with other clients yet, nor have I gone through and made the primitives/MPI macros yet, however that should be the easy stuff.

I'll try to finish this up and then, once on the test MUCK, we can have people try it out with different clients and see what happens.

**Comment by tanabi** [comment]
In addition to support on the MPI `{right:....} {left:...}  {center:....}` functions...
I'll also make MPI prims `{width}` and `{height}`.
With MUF prim equivalents `WIDTH` and `HEIGHT`.

Because some clients don't support window sizing correctly, I'll also have MUF prims `SETWIDTH', 'SETHEIGHT' as M3 functions.  I'm not sure we want to have MPI macros to set window size because that just seems like a recipie for griefing.
