### ISSUE TITLE
Keeper's password

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#427]
Looking in advancedb, I'm pretty sure Keeper has a password, even though it's not documented like One's potrzebie.
Does anyone know what it is?  If so, we should document it.
If not, we should give him a new password and document it.

pinging @natmeox because advancedb

**Comment by wyld-sw** [comment]
I believe the intention was that Keeper will never log in, and thus does not need a knowable password.

**Comment by nyanster** [comment]
> I believe the intention was that Keeper will never log in, and thus does not need a knowable password.

Still, he has one, so it should be known. :P
If he had no password at all, that'd be a different matter.

**Comment by wyld-sw** [comment]
advancedb was written for Keeper to not have a knowable password. I am inclined to keep it this way.

**Comment by nyanster** [comment]
His password, just like One's, needs to be changed by the MUCK admin.
Someone in the world does know Keeper's password.  Documenting the password provides an impetus for a MUCK admin to change Keeper's password.

This is different from, say, a GNU/Linux system where root genuinely has no password and can't login.  Keeper has wiz privileges and is capable of logging in.

**Comment by nyanster** [comment]
And an open-source project shouldn't be hiding anything from its users, anyway.

**Comment by wyld-sw** [comment]
We can certainly let folks know that his password was randomized (assuming I remember correctly!).

I'm just mentioning what I think the intention was. I know of no reason to go against that - we don't have the password, but we can certainly @ newpassword Keeper if that's honestly the best approach.

**Comment by nyanster** [comment]
> We can certainly let folks know that his password was randomized (assuming I remember correctly!).

How can anyone believe that, without proof?

> I'm just mentioning what I think the intention was. I know of no reason to go against that - we don't have the password, but we can certainly @ newpassword Keeper if that's honestly the best approach.

The intention of things can remain the same even when he has a new password.  "Hey, Keeper isn't really meant to be logged into.  Change his password once and then don't log into him again." or something like that.  Or a simple "Change Keeper's password too." after "Change One's password."
If MUCK admins want to login as him, a secret password won't stop them, anyway.

**Comment by nyanster** [comment]
https://github.com/fuzzball-muck/fuzzball/pull/430

**Comment by nyanster** [comment]
Resolved by
https://github.com/fuzzball-muck/fuzzball/pull/431
