### ISSUE TITLE
MPI has convtime, MUF doesn't have an equivalent

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#434]
I'm a little sidetracked from the documentation work as I write an RP calendar for my MUCK.  In this work, I've found out that that there's no way to convert a string to a timestamp in MUF.

MPI can do it with convtime, but MUF doesn't seem to have an equivalent.  I'm going to hack around this by running MPI to do the timestamp conversion.  But optimally we'd have a MUF call that just does the same thing.  In a perfect world, even uses the same underlying code, but I'll bet we don't live in a perfect world. :)

**Comment by wyld-sw** [comment]
The primitive CONVTIME has ben added, sharing logic and error message with {convtime}.

Not quite perfect, but hopefully it's a start to approaching feature (and logic) parity between MPI and MUF.

Closing this, but feel free to respond.
