### ISSUE TITLE
Removed recursive comments code breaks existing mucks

### ISSUE THREAD

**Issue by foxbird** [fuzzball-muck/fuzzball#442]
I commented on the commit that breaks things:

https://github.com/fuzzball-muck/fuzzball/commit/7fed0e712ecf4089c10fe4830f216536eb6fa7e0#commitcomment-34038815

It seems that this comment breaks existing MUCKs quite badly. I would recommend reverting this change as you're unlikely to get people to fix all of the MUF programs on a muck (established ones having hundreds if not a thousand). HLM had to revert back to the commit prior to this in order to function again.

**Comment by wyld-sw** [comment]
Reverted. Thanks for the report.
