### ISSUE TITLE
deep_copyinst memory leak

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#444]
Check out this code here:

https://github.com/fuzzball-muck/fuzzball/blob/7cf2169fb4a213d19766a7521a8e6f3c1d0cded7/src/interp.c#L897

If I'm reading this right, if you're deep copying a packed array... it will allocated a packed array in the case ARRAY_PACKED, which will then fall through to the ARRAY_DICTIONARY block where 'nu' will immediately be overwritten with a dictionary, thus leaking the array allocated in ARRAY_PACKED.  

Is there any reason to have this fall through?  Pretty sure there isn't.  I'm not even sure if this code is working right for the case of array_packed since it seems like it would convert the array to a dictionary, thus breaking code.  However, this particular function is used only in very weird cases that few people encounter (MUF's fork uses it, for instance, as does some of the event code) so that's probably why it has never been noticed.

I would recommend first testing 'fork' on a process that has arrays to see what happens to them.  Then adding the break and seeing if the result changes.  Kind of a lot of work for a little problem, but it would put it through the paces.

@wyld-sw  do you have time to take a look?  If not, I'll get to it when I'm done with interp (which could be quite awhile still :P )

**Comment by wyld-sw** [comment]
Confirmed, FORK and DEEP_COPY both converted arrays to dictionaries. Didn't try EVENT_SEND, but I assume it was similar. I added the break and it works as expected now - including for nested arrays.

Good find! Feel free to re-open this if there's still (or I introduced) a bug.

**Comment by tanabi** [comment]
Thanks for doing the test legwork on this!
