### ISSUE TITLE
Date Weirdness

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#451]
In the latest fuzzball, this:

```
@muf "18:30:00 08/15/2019" convtime
```

produces the date in 2020 for some reason.  This:

```
@muf "18:30:00 08/15/19" convtime
```

seems like it works.  I thought we had fixed this date stuff before ?  Did we introduce some problem recently?

**Comment by wyld-sw** [comment]
We added century support to years in {convtime} and the new CONVTIME, but that must have escaped my testing :(. I'll look into it, if you don't beat me to it!

**Comment by wyld-sw** [comment]
I stand corrected; it's still a 2-digit year - and it seems to be reading the first 2 digits (20) as the year in your first example. There may be a way to prevent that - or actually recognize 4-digit years. We may need to code our own strptime for that?

**Comment by wyld-sw** [comment]
Works well, thanks!
