### ISSUE TITLE
ADDPENNIES primitive and GIVE command differ in behavior

### ISSUE THREAD

**Issue by dbenoy** [fuzzball-muck/fuzzball#457]
The ADDPENNIES primative will ensure that thing objects have positive values, but the GIVE command doesn't care.

Perhaps these behaviors should be harmonized. I think they should both prevent negative values, but a value of zero should be fine?

**Comment by dbenoy** [comment]
A value of zero on an object is useful if you want some sort of process to be able to create objects in an unprivileged way, but you don't want users to be able to collect pennies when they recycle the object.

**Comment by tanabi** [comment]
If I'm remembering right, recycle won't 'respect' negative pennies and will 'round' it up to 0 if an object has negative.  Though the MUF recycle command may operate differently as I am sure they use totally different sets of code.

Though I totally agree, these things should not only work the same, but they should share the same underlying code.

**Comment by dbenoy** [comment]
Just gave it a try.

```
> @create test
Object test(#183) created.
> examine test
test(#183)  Owner: Mercury  Value: -1
Type: THING
Created:  Sun Sep 15 14:58:44 2019 EDT
Modified: Sun Sep 15 14:58:44 2019 EDT
Lastused: Sun Sep 15 14:58:44 2019 EDT
Usecount: 0
[ Use 'examine <object>=/' to list root properties. ]
Memory used: 227 bytes
Home: Cave of Awakening
Location: Mercury(#164PWQBC)
No actions attached.
> inventory
You are carrying:
test(#183)
You have 0 pennies.
> @recycle test
Thank you for recycling test (#183).
> inventory
You aren't carrying anything.
You have -1 pennies.
```

**Comment by tanabi** [comment]
Well that's just nasty.  Yeah, we need to fix that :)  This is a pretty easy one.  Would you like to take a whack at it or you want @wyld-sw or myself to do it?

**Comment by dbenoy** [comment]
So how would I go about it?

I've noticed GIVE lets wizards exceed tp_max_pennies when used on players feels like it makes sense.

But it also lets them set player penny amounts to negatives, and it has no checks at all for wizards when giving to thing objects.

```
> @tune max_object_endowment
(int)  max_object_endowment = 100
*done*
> give #187=10000000
You change the value of testobject to 10000000 pennies.
> give #187=-20000000
You change the value of testobject to -10000000 pennies.
> give me=-100
You take 100 pennies from Mercury.
Mercury takes 100 pennies from you!
> inventory
You are carrying:
testobject(#187)
You have -100 pennies.
```

So is this deliberate, or an oversight? I think there's a few ways to look at this:
1) Wizards and wizbit programs should be able to set the pennies to whatever they want, no matter how silly, but @RECYCLE should be prevented from giving negative 'refunds' for thing objects.
2) Everything that modifies a player or thing's pennies value (GIVE, ADDPENNIES, MOVEPENNIES, recycling, etc.) should check that the values stay between 0 and the maximum regarldess of privileges.
3) Everything that modifies penny values should ensure the values remain at 0 or above, but the maximum values can be violated by wizards all they want.

Personally I don't care which, so long as all the different penny modifications behave consistently. I'm slightly partial to option 1 because it would be the best at preserving compatibility, in the case of a MUCK that's doing something strange things with their code, like having an economy that includes walking around with debt.

Also what good is a wizbit if you can't use it to break the rules sometimes :3

**Comment by dbenoy** [comment]
Oops.

**Comment by dbenoy** [comment]
Option 4 I suppose is to continue allowing negative 'refunds' and make it so ADDPENNIES lets you go into negatives.

My pull request will include a fix for when @create makes -1 value objects if @tune object_cost = 0, so theoretically there won't be any negative value thing objects kicking around unless a wizard deliberately makes them that way.

**Comment by tanabi** [comment]
I agree with option [1].  When you ask how to go about doing it, are you asking technically or was that just the preface to the rest of the question? :)

**Comment by dbenoy** [comment]
Because I intend to fix it myself and wanted to know which option :)

**Comment by wyld-sw** [comment]
Pull request merged in; thank you!
