### ISSUE TITLE
User passwords stored using insecure algorithm

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#46]
All user passwords are currently stored according to the following algorithm:

```
base64(md5(password))
```

Using MD5 is, these days, little better than obfuscation, rather than proper security. Combined with a lack of salting, it is trivial to recover user passwords with access to the database.

Salting passwords prior to storage would greatly increase the time to recovery for dictionary and brute-force offline attacks, though with MD5 as the underlying hash, it would still be well within the capability of the average attacker.

Ideally, MD5 would be replaced with a proper key derivation function (bcrypt, PBKDF2, et al.), or at least a multi-round SHA2 digest.

Both of these (salting, algorithm) could be implemented as compile-time options so as not to automatically modify a database in such a way that compatibility is broken with prior versions.

**Comment by kyanha** [comment]
I agree, this is a problem.

I think that bcrypt or whatever obfuscation system should be compiled in by default (so as to always be able to use non-backward-compatible databases), with a God-level tunable parameter to make password storage be non-backward-compatible when '@password' and '@newpassword' are used.

**Comment by wyld-sw** [comment]
Agreed.

**Comment by sypherspace** [comment]
@kyanha is probably referring to `@password` and `@newpassword`. Gotta love Markdown.

**Comment by digitalcircuit** [comment]
On FreeBSD/Linux/etc, there's the [```crypt()``` function](https://www.freebsd.org/cgi/man.cgi?query=crypt&sektion=3 ) which offers a semi-standard way of storing passwords, e.g. the system uses it for user logins and [PHP uses it for password hashing](https://secure.php.net/manual/en/function.password-hash.php ).  This would simplify upgrading to more secure password hashes in the future as the version is stored as part of the hash string, and it helps avoid mistakes in implementation.

I'm not sure about how to handle this on Windows, unfortunately.  Based on some discussion with ```Freenode/AllanJude```, the FreeBSD implementation should be portable to Windows, but I haven't tried that and don't know what complications may arise.

*Aside, any solution here would probably help Quassel, too, where I first encountered the topic - [comment by ```@allanjude``` on ```quassel/quassel``` pull request 110](https://github.com/quassel/quassel/pull/110#issuecomment-227048493 ).*

**Comment by sypherspace** [comment]
The `crypt()` function would probably be the easiest route forward. It would be easy to parse old vs. new passwords in the database: Does the password string start with a `$`? If yes, it's `crypt()`, If no, it's old-style MD5.

**Comment by woggle** [comment]
I wouldn't like to use the system crypt() because the portability of non-DES crypt is variable. (Especially since we support Windows.)

It would probably be easy enough to include a copy of scrypt or PBKDF2_HMAC_SHA512 or Argon2i or something and switch based on a prefix $<code>$ prefix like crypt()s often do these days.

**Comment by kyanha** [comment]
I recommend that a library be chosen that can be updated to support new digest functions, but without losing the ability to authenticate against previously-implemented digests.  Such a library would necessarily have $*CODE*$-style digest selectors, for such agility.

If no currently-available library does such, then importing OpenBSD's crypt() implementation [which does support that style of selector] might be the best available option.

**Comment by tanabi** [comment]
So I've reviewed all these notes, and I think the way to go is as follows:

* Use OpenSSL for crypt functions.  We're already in bed with OpenSSL so doing it this way means we don't have to add a new library.
* When calculating the hash for password comparison, we'll support both methods and use a starting character combination to indicate the new hash mechanism (actually I think just the $ symbol will suffice).
* A new `@tune` parameter will be added, probably tp_legacy_password_hash, and it will default to false.  If it's true, the MUCK will continue to use the legacy hash.  If its false, the MUCK will store all new passwords stored in the new hash format.

I think the use case for tp_legacy_password_hash is incredibly small, but I could see places like SPR potentially wanting to stay backwards compatible until they're 100% sure the latest code works.

**Comment by davidatpurdue** [comment]
Agreed. Thanks!

**Comment by tanabi** [comment]
I ultimately am choosing to go with PBKDF2 using SHA 512 and 1,000 iterations with a 10 byte salt.  I've already written most of it.  OpenSSL supports this out of the box pretty handily.

**Comment by digitalcircuit** [comment]
Since you're defining a new password hash anyways, I would encourage implementing some sort of versioning so you don't have to support multiple methods of determining the hash technique down the road.

You mentioned checking for `$` - it might be as simple as `[up to 8 digits]$`, e.g. `1$`, then later `2$`, etc?

(This brings to mind [Quassel IRC's changes](https://github.com/quassel/quassel/commits/0.14.0/src/core/storage.cpp) to implement [more modern password hashing](https://github.com/quassel/quassel/blob/0.14.0/src/core/storage.cpp#L36) while avoiding introducing difficult to package dependencies.  In Quassel's case, the database was modified to insert an extra hash version entry.)

**Comment by tanabi** [comment]
@digitalcircuit That's a good idea, I'll add that in.  I've seen that in use in other places.
