### ISSUE TITLE
User passwords are stored in command log when using @password/@newpassword

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#47]
User passwords are displayed in cleartext in the command log when using `@password` or `@newpassword`. These should be masked or omitted from the command log.

**Comment by wyld-sw** [comment]
Password areas are now masked when logging @password, @newpassword, and @pcreate commands. This uses a simple approach which will become more generic in future commits.

**Comment by nyanster** [comment]
Nice. :D
But doesn't this commit, the first of the three commits today,
https://github.com/fuzzball-muck/fuzzball/commit/2787d19f95ac6d29882daa570974012275ab025c
Do the same improper thing mentioned in:
https://github.com/fuzzball-muck/fuzzball/pull/232
?
It looks like snprintf is once again using the same variable both as the first and last argument.
If I'm misunderstanding something though, I apologize. (I'm rusty with C, so this is very possible)
