### ISSUE TITLE
REGSPLIT server crash

### ISSUE THREAD

**Issue by dbenoy** [fuzzball-muck/fuzzball#483]
`@muf "a b" "(?= )" 0 regsplit` crashes the server.

**Comment by tanabi** [comment]
Did you faint when you found this one? :D

**Comment by dbenoy** [comment]
I didn't actually look at the fuzzball source yet, but what I expect is going on is that it cuts a piece off, then continues until there's no string left, and since this is generating a 'zero length' match, it just cuts and cuts forever. I encountered a similar thing when I was writing this piece of MUF. Take a look at how I had to write regexp_nozero. A similar solution is probably what's needed in the fuzzball source.

```
(*   regslice ( s s i -- a )                                                 *)
(*     Like the REGSPLIT primitive, except separators are kept. For example: *)
(*       "a b  c-- d" " |--" 0 M-LIB-STRING-regslice                         *)
(*       Result: {"a", " ", "b", " ", "", " ", "c", "--", "", " ", "d"}      *)
(*                                                                           *)
(*     The array will never begin or end with a separator, so it will always *)
(*     have an odd number of elements.                                       *)

: regexp_nozero[ str:text str:pattern int:flags -- list:submatchvals list:submatchidx ]
  text @ pattern @ flags @ regexp
  dup not if exit then
  dup 1 array_cut pop array_vals pop array_vals pop 0 = swap 1 = and if
    (* Matched at the beginning of the string, zero length, so fix it by removing the first character and trying again. *)
    pop pop
    text @ 1 strcut swap pop pattern @ flags @ regexp
    {
      swap foreach
        nip
        dup 0 [] ++ swap 0 ->[]
      repeat
    }list
  then
;

: regslice[ str:text str:pattern int:flags -- list:results ]
  {
    text @ begin
      dup pattern @ flags @ regexp_nozero nip
      dup not if pop break then
      1 array_cut pop array_vals pop array_vals pop
      -rot -- strcut
      (* TODO: Bail here if they didn't specify REG_ALL *)
      rot strcut
    repeat
  }list
;
```

Here's the rest of that MUF if you're interested in peeking at it: https://github.com/dbenoy/mercury-muf/blob/master/m-lib-string.muf

Been doing a boat load of coding in that repository, heh. I decided to make some code to launch a new MUCK and I'm overdoing it so hard.

**Comment by wyld-sw** [comment]
The latest merge (#557) seems to fix this issue. Can you confirm?

**Comment by wyld-sw** [comment]
Closing since it doesn't crash anymore. Feel free to reopen if the fix is incorrect.
