### ISSUE TITLE
ARRAY_FILTER_LOCK has no man page

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#491]
ARRAY_FILTER_LOCK has no man page.

You can copy the docs from ARRAY_FILTER_FLAGS ... the difference is instead of a string of flags, it takes a parsed lock.

**Comment by wyld-sw** [comment]
Hmm. ARRAY_FILTER_LOCK seems to have a man page on environments I'm testing (though it was copied from ARRAY_FILTER_PROP). Could it be that the system you're looking at doesn't update help content when upgrading? Or is it just way too early for me to be helpful? :)

**Comment by tanabi** [comment]
Hrrm, Hope Island doesn't have the man page, but this time instead of assuming the MUCK was set up right I did a grep and I can see ARRAY_FILTER_LOCK is there.  So this is my bad, yeah, it's Hope Island and not Fuzzball.
