### ISSUE TITLE
Incorrect example in man page

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#493]
man array_excludeval gives the following example:

```
 If you want the values, use ARRAY_DIFF or
ARRAY_EXTRACT.  Ie:
    { #5 #10 #15 #10 #20 }list { #10 }list array_diff
```

This is actually wrong -- if you run that, it'll return an empty array.  Instead, it should be:

```
    { #10 }list { #5 #10 #15 #10 #20 }list array_diff
```

The other example works (though it returns a dictionary and not a list)

**Comment by wyld-sw** [comment]
Fixed! 34b950ae1597270f869b460d2a0294754c7271c8
