### ISSUE TITLE
MUCK Crash on @toad

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#495]
I @toaded a player while they were connected (not sure if that is relevant or not) and it crashed the MUCK.  No error that I can find.  This happened "live" on Hope Island, I have not tried it on a test MUCK yet but I wanted to get a bug in as this is kind of a big issue :)

**Comment by tanabi** [comment]
Found it.  Seg fault here in interface.c

```
0x0000555555585647 in announce_disconnect (d=0x555555d4ad80) at interface.c:2349
warning: Source file is more recent than executable.
2349	        snprintf(buf, sizeof(buf), "%s has disconnected.", NAME(player));
```
It's trying to get the player's name after they have been toaded.  Whoops :)

**Comment by tanabi** [comment]
I think this is because we removed the creation of toad objects on @toad if I remember right.  And now we've learned the folly of our ways!

**Comment by wyld-sw** [comment]
I think toad objects are still created, but there’s a tune for recycle_toads that might be set to on. Or I may have dreamt that. Either way, an issue!

**Comment by tanabi** [comment]
I had the line wrong (notice the source file is more recent than executable note).  The real line is this one:

```
0x000055555558568a in announce_disconnect (d=0x555555d52120) at interface.c:2348
2348	    if (player && (!Dark(player)) && (!Dark(loc))) {
```

**Comment by wyld-sw** [comment]
So maybe adding a OkObj(player) would work?

**Comment by tanabi** [comment]
Fixed.
