### ISSUE TITLE
Hope was using sha1hash ?

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#496]
Hrm!  I recall seeing a commit awhile ago removing sha1hash prim ... and Hope Island was using that for its @ pcreate command to generate random passwords.  Why did we remove that again?  Is there a substitute?  I can't quite recall.  I searched issues but don't see a corresponding issue.

**Comment by wyld-sw** [comment]
Oh, sorry. It was only added since we had sha1.c around for @ hashes - which is gone. I may remember a conversation that MD5HASH is sufficient (and the new prim wasn’t exactly needed), but I (or you, I think you have pernissions) can revert!

**Comment by tanabi** [comment]
I swapped hope to use the MD5HASH call.
