### ISSUE TITLE
Incorrect man page

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#500]
man + mentions a tune parameter that, as far as I can tell, no longer exists.  If it does exist, it isn't honored, because prim_add doesn't use it:

```
+ ( n1 n2 -- i )
  
  This adds two numbers, n1 + n2.  If both numbers are integers, an integer
will be returned.  If one of them is a floating point number, then a float
will be returned.  You can also use this on a dbref or a variable number,
so long as the second argument is an integer.  In those cases, this will
return a dbref or variable number, respectively.
  
  With sysparm muf_string_math, also concatenates two strings.
```

This should be re-written to just say it will concatenate if both operands are strings and not mention the sysparm.

**Comment by wyld-sw** [comment]
I think mufman.raw was updated when that sysparm (previously a #define) was removed.

**Comment by tanabi** [comment]
You're right.  Sorry about that -- I need to stop relying on Hope's man pages to be accurate, I will try to remember to check the raw files before opening an issue :)
