### ISSUE TITLE
Make Fuzzball Docker image

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#529]
For two purposes;

Firstly, it will make it a lot easier to test.

Secondly, we can put it on Dockerhub and make another very easy way for people to run Fuzzball.

**Comment by tanabi** [comment]
@wyld-sw How far did you get with this?  Still want me to take a wack?

**Comment by wyld-sw** [comment]
I’m close, but I’m sure you could do if more elegantly. Have at it!

**Comment by tanabi** [comment]
Don't sell yourself short :)  But I'll take a wack at it.  We can compare notes at the end.

**Comment by tanabi** [comment]
I have been super busy lately, but wanted to update this -- I have a docker-compose + Dockerfile that works.  However, doesn't support Let's Encrypt or the set up of an initial DB yet (though it will run an already installed MUCK in the docker container).  It's not a lot more work, I just have to sit down and do it, then we can have Docker builds, woo!

**Comment by wyld-sw** [comment]
Very nice!

**Comment by tanabi** [comment]
Some notes to self:

* This now successfully intializes a new MUCK if there isn't an existing MUCK game directory.
* Ports and path are taken from environment correctly.

TODO:

* Document how this works
* Make a build process with Makefile
* Figure out how to push to Dockerhub
* Make SSL work with 3 options
  * Existing SSL files
  * Generate self-signed
  * Use Let's Encrypt -- I have been trying to get this to work but its a challenge, its pretty complex when you want to do this without a web site, and even worse if your MUCK isn't exposed to the internet (like my dev server)

**Comment by tanabi** [comment]
I've made the makefile process.  Now sifting through how to do the SSL portion.

**Comment by tanabi** [comment]
I'm making the decision to not directly support Let's Encrypt.  I will, however, indirectly support it and provide some helpful documentation.

The problem is, Let's Encrypt requires either (a) a web port be open and accessible to the internet or (b) some DNS stuff.  (a) is prohibitive to do in a docker container for a number of reasons and (b) is simply not possible to do since every DNS provider has a differnet API and some have none.  Therefore, it is not practical to automate this.

However, I can make it easy to set up Let's Encrypt outside of docker and have the container pick up the certs.  So this is what i will do!  I will also make it easy for the container to make self-signed certs which I think is acceptable for most people.

**Comment by tanabi** [comment]
I did all the scripting here, just have to test it and document it.  I think the way I did it is slightly suboptimal but it leaves the door open for several different approaches to certs -- I'll have all those approaches documented -- so it should be okay.  We can always refine the process as we go forward and see what people actually use here.

Once I test and document, the last step is figuring out how to automate the docker build and push to dockerhub.

**Comment by tanabi** [comment]
Hrm, I have found a weakness in my dockerfile, but I think I will deal with it later.

The OS version of the docker base container in the Dockerfile has to match the version of the machine doing the compile.  If they don't match, you get a glibc error.

I can fix that later though, I'll make an improvement ticket.  For v1.0 this is an acceptable limitation I think.

**Comment by tanabi** [comment]
Testing is done.  I will make some documentation, then figure out the build/push to dockerhub.  Arg this has taken a long time :)

**Comment by tanabi** [comment]
I wrote all the documentation -- I need to test my documentation (make sure all the commands and examples work) then I have something that can be checked in.

There's still the matter of hte build to get it into docker hub -- I have wheels in motion with Wyld to get that set up

**Comment by tanabi** [comment]
My instructions check out.  Looking into getting it into dockerhub now but I went ahead nd put in a PR for it.  Don't close this ticket until it is in docker hub though

**Comment by tanabi** [comment]
We are live on dockerhub!  https://hub.docker.com/r/fbmuck/fbmuck

Safe to close this ticket after merge.
