### ISSUE TITLE
TinyMUCK Wiki Page

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#538]
https://en.wikipedia.org/wiki/TinyMUCK

There's a link to the old sourceforge on the Wiki for TinyMUCK.  We might want to update this wiki in a way that preserves the history but also links the new github project.  Maybe even elaborates a little on the fuzzball versions.

Wiki is very standards fussy so if someone else has experience contributing, my preference would be to let them do it rather than me ;)  I am very not hip to wiki standards.

**Comment by aidanPB** [comment]
Part of Wikpedia's standards-fussiness is the whole "original research"
thing, which gets very fuzzy indeed with open-source projects. It might be
best to raise the issue on the article's Talk page and let someone who has
never contributed to the code deal with it.

**Comment by rayanth** [comment]
To be fair, the `COMPILING` file (in 6.18, released 5/3/2020) still references the old SourceForge site, too, at the bottom:

```
Alternatively, you can submit all of this information to the fbmuck
project bug tracker at http://www.sf.net/projects/fbmuck .
```

 Also, the "Moved to" URL ON the SourceForge site (at the top) is an invalid link, containing a comma instead of a period.

**Comment by wyld-sw** [comment]
Thanks for the report. I’ve found a way to update the SF summary with a valid URL.

**Comment by wyld-sw** [comment]
The 6.18 tarball now references github as the point of contact.

**Comment by tanabi** [comment]
The external links has a link to the correct website, and sourceforge references the correct new repo, so I'm going to consider this done enough to close.
