### ISSUE TITLE
reload SSL context when cert files change

### ISSUE THREAD

**Issue by wyld-sw** [fuzzball-muck/fuzzball#543]
Consider calling reconfigure_ssl (or similar) when the server detects that the certificate files have been modified.

Thanks to DinoEx@Anthopomorphia for the idea.

**Comment by eigenfire** [comment]
Please include logic that rejects the new cert if there's something about it that's invalid, and continues to run with the old cert. This would be an easy way to crash your everything in a fat-finger event.

**Comment by dinoex** [comment]
Working patch for fbmuck-6.18 as sample:

[interface.c.patch.txt](https://github.com/fuzzball-muck/fuzzball/files/5355508/interface.c.patch.txt)

**Comment by tanabi** [comment]
This looks like it probably works.  Sorry for sitting on this so long @dinoex !  I'll try to get this merged in soon.

**Comment by tanabi** [comment]
I have patched this in and updated it to the FB7 coding standards.  I haven't thoroughly tested it yet, so no merge yet, but this is almost done.  Sorry for the long wait.

**Comment by tanabi** [comment]
This is done, pending code review.  Please note I added a tune param that defaults to false called auto_reload_certs ... it has to be set to true to enable this behavior.

**Comment by tanabi** [comment]
I think I should probably rename it to ssl_auto_reload_certs to be more in line with coding standards, I will do that ....
