### ISSUE TITLE
compiler warnings about nested comments

### ISSUE THREAD

**Issue by dinoex** [fuzzball-muck/fuzzball#544]
cc -O2 -pipe -g -O2 -std=gnu99 -fwrapv -I../include  -I/usr/local/include  -c array.c
In file included from array.c:22:
../include/interface.h:121:29: warning: '/*' within block comment [-Wcomment]
                            /*   usually same as descriptor, exists to
                            ^
1 warning generated.

**Comment by tanabi** [comment]
Ack, my bad.  I'll have a fix up in a sec.  Thanks!
