### ISSUE TITLE
Unable to launch MUCK on privileged port even when launching as root and dropping privileges

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#56]
Compiled with `MUD_ID` and `MUD_GID` set in `include/config.h`. MUCK is configured to listen on port 23 for unencrypted connections. Launch fails with the following error recorded in `logs/fbmuck.err`:

`binding stream socket: Permission denied`

**Comment by sypherspace** [comment]
Confirmed by changing service port to 2323 and restarting. MUCK functions normally when not attached to a privileged port. Notably, attempting to add via `setcap cap_net_bind_service=+ep /usr/local/bin/fbmuck` does not help the issue.

**Comment by kyanha** [comment]
Here's the strace output.  setuid() is happening long before the database is even being checked, but the bind() has been relocated to happen after.

Needless to say, this is precisely the reason why the bind() must happen before, and I don't know when the order got messed with.  (MUD_ID was added specifically because SPR wanted to bind to port 23, but they got concerned with running the entire process as root.)

The call to setcap probably wouldn't work unless running with -nodetach.  I believe it's because the positive privilege typically doesn't get inherited by the detaching execve().

[output.txt](https://github.com/fuzzball-muck/fuzzball/files/737062/output.txt)

**Comment by sypherspace** [comment]
For a while after migrating from the original server to the current Linode solution, we were in fact running the MUCK under a normal user, with setcap applied to allow listening on 23/tcp. We only changed to running as root (as we currently do) while trying to determine what was causing the lockup issue reported under #40 . I suspect the reason that setcap is not currently working is the change in effective UID/GID. Previously, we ran without MUD_ID/MUD_GID configured, and started the MUCK via systemd unit under the normal user's context.

All of this is to say that I have no way of knowing when this stopped functioning as intended, or if it ever did.

**Comment by kyanha** [comment]
I remember writing the support for it because Snout wanted to run it as root on Ultrix, which didn't have setcap.  Ah well.  It seems that the patch wasn't applied to Sourceforge, so I'm fixing it now.

I'm failing with git tonight so instead, I'm just going to give you interface.c as I've edited it.  Please try this and let me know how it goes?

[interface.c](https://github.com/fuzzball-muck/fuzzball/files/737577/interface.c.txt)

**Comment by sypherspace** [comment]
That allows the MUCK to launch and bind to port 23, I'm able to connect and execute commands, commands are logged properly. Database dumping, however, seems broken. I attempted to dump the database, and everything seems fine, aside from the defunct forked process.

```# ps -ef | grep fbmuck | grep -v grep
fuzzball 11243     1 99 15:07 ?        00:03:45 /usr/local/bin/fbmuck -gamedir /opt/fuzzball/spr/game -dbin /opt/fuzzball/spr/game/data/std-db.db -dbout /opt/fuzzball/spr/game/data/std-db.new -sport 23551 23 2323
fuzzball 11519 11243  1 15:07 ?        00:00:02 [fbmuck] <defunct>```

On the MUCK itself:

```@dump
Sorry, there is already a dump currently in progress.```

**Comment by kyanha** [comment]
Can you try sending a SIGCHLD to the parent process in that circumstance?  We might have a race condition here.

**Comment by sypherspace** [comment]
Replicated the issue, sent `SIGCHLD` to parent process with no effect or change in behavior.

**Comment by woggle** [comment]
Is `pselect_signal_mask` being set to include SIGCHLD from the code in `fbsignal.c`? (It's supposed to capture the original signal mask, which I would hope would not include SIGCHLD...)

**Comment by kyanha** [comment]
@wyld-sw told me on FM that it works when the pselect code isn't used.

But here's the relevant quote regarding SIGCHLD from sigaction(2) on my CentOS 6 VM:

```
POSIX.1-1990 disallowed setting the action for SIGCHLD to SIG_IGN.  POSIX.1-2001 allows this possibility, so that ignoring SIGCHLD can be used to prevent the  creation  of zombies (see wait(2)).  Nevertheless, the historical BSD and System V behaviours for ignoring SIGCHLD differ, so that the only completely portable method of ensuring that terminated children do not become zombies is to catch the SIGCHLD signal and perform a wait(2) or similar.
```

**Comment by kyanha** [comment]
Additional issue: fbmuck.err fills up with "new_connection: invalid argument", and the muck fails to listen for SSL connections.

Resolution:  in interface.c:listen_bound_sockets(), the loop body should read:

```
for (int i = 0; i < numports; i++) {
    listen(sock[i], 5);
    listen(ssl_sock[i], 5);
}
```

**Comment by kyanha** [comment]
FYI, it got broken out into a separate loop, with i counting up to ssl_numports.  @sypherspace, could you test please?

**Comment by sypherspace** [comment]
IPv4 connections function as expected for both cleartext and encrypted ports. Database dumps function as expected. However, large quantities of log messages reading as follows are still being generated.

`new_connection: Invalid argument`

```
# grep 'new_connection: Invalid argument' fbmuck.err | wc -l ; date
14938461
Fri Feb  3 22:25:05 UTC 2017
# grep 'new_connection: Invalid argument' fbmuck.err | wc -l ; date
15488883
Fri Feb  3 22:25:09 UTC 2017
# grep 'new_connection: Invalid argument' fbmuck.err | wc -l ; date
16424097
Fri Feb  3 22:25:15 UTC 2017
```

**Comment by wyld-sw** [comment]
Latest commit should listen to IPv6 sockets, encrypted or plaintext. @sypherspace - test again, please?

**Comment by sypherspace** [comment]
That did not seem to have an effect. Same log data generation, same non-listen on IPv6.

```
# ss -lt
State       Recv-Q Send-Q                        Local Address:Port                            Peer Address:Port
LISTEN      0      5                                         *:2323                                       *:*
LISTEN      0      128                                       *:ssh                                        *:*
LISTEN      0      128                                       *:39350                                      *:*
LISTEN      0      5                                         *:telnet                                     *:*
LISTEN      0      20                                127.0.0.1:smtp                                       *:*
LISTEN      0      5                                         *:23551                                      *:*
LISTEN      0      128                                       *:sunrpc                                     *:*
LISTEN      0      128                                      :::ssh                                       :::*
LISTEN      0      20                                      ::1:smtp                                      :::*
LISTEN      0      128                                      :::58310                                     :::*
LISTEN      0      128                                      :::sunrpc                                    :::*
```

```
# ls -l fbmuck.err ; date
-rw------- 1 root root 219971862 Feb  4 03:32 fbmuck.err
Sat Feb  4 03:32:13 UTC 2017
# ls -l fbmuck.err ; date
-rw------- 1 root root 226596480 Feb  4 03:32 fbmuck.err
Sat Feb  4 03:32:14 UTC 2017
# ls -l fbmuck.err ; date
-rw------- 1 root root 233427810 Feb  4 03:32 fbmuck.err
Sat Feb  4 03:32:16 UTC 2017
```

**Comment by kyanha** [comment]
Please replace function `listen_bound_sockets()` in interface.c with this one:

```
static void listen_bound_sockets()
{
    if(ipv4_enabled) {

        for (int i = 0; i < numsocks; i++) {
            listen(sock[i], 5);
        }

#ifdef USE_SSL
        for (int i = 0; i < ssl_numsocks; i++) {
            listen(ssl_sock[i], 5);
        }
#endif /* defined(USE_SSL) */
    }

#ifdef USE_IPV6
    if(ipv6_enabled) {

        for (int i = 0; i < numsocks_v6; i++) {
            listen(sock_v6[i], 5);
        }
#ifdef USE_SSL
        for (int i = 0; i < ssl_numsocks_v6; i++) {
            listen(ssl_sock_v6[i], 5);
        }
#endif /* defined(USE_SSL) */
    }
#endif /* defined(USE_IPV6) */
}
```

**Comment by kyanha** [comment]
Created pull request #60 for this.

@wyld-sw said he was getting ready for a week in Texas for work, so this may need to be applied manually by @sypherspace for testing until @wyld-sw gets back.

**Comment by wyld-sw** [comment]
Fix committed.

**Comment by sypherspace** [comment]
> "One thing leads to another..." - One Thing Leads To Another, The Fixx

logs/status is now filling up with `2017-02-04T12:59:43: forked DB dump task exited with status 0`

**Comment by wyld-sw** [comment]
Merging this with #66. Current initialization order creates log files than cannot be written to.

**Comment by aidanPB** [comment]
Exiting with status zero usually means "completed successfully"; it might be a waste of space, but I would assume that those log entries aren't indicating any execution problem. (That said, I've never actually *looked* at logs/status myself; feel free to correct me if you're sure that they're not "all is well" messages.)

**Comment by sypherspace** [comment]
> That said, I've never actually looked at logs/status myself; feel free to correct me if you're sure that they're not "all is well" messages.

In this instance, it was (quite literally) billions of lines of `forked DB dump task exited with status 0` filling up the entire filesystem.

`logs/status` is quite useful for many things, especially when the admin (me) is an idiot on a testing box and forgot that a file must actually exist to be useful:

```
2017-09-10T15:16:56: Could not load certificate file data/server.pem
2017-09-10T15:17:28: SHUTDOWN: via SIGNAL
```
