### ISSUE TITLE
COPYOBJ considerations

### ISSUE THREAD

**Issue by wyld-sw** [fuzzball-muck/fuzzball#573]
COPYOBJ completely clones the given thing.

Is it a concern that wizard props are cloned as well? If so, should this happen only if the program's effective MUCKER level is 4? (or in the case of the `@clone` command, only for wizards?)

The cloned object also shares the same timestamps and use count, but this may not have been intended. Should these have "new object" values?

A concern from sourceforge stated that COPYOBJ being available for M1 may allow the user to get around any quotas. Thoughts?

**Comment by tanabi** [comment]
Thoughts:

- Wizard props should only be cloned if the program is M4 / Wizbit
- They should have new timestamps and use count
- COPYOBJ should be the same MUCKER level as making an object (newroom, etc.) which is MUCKER3
-

**Comment by wyld-sw** [comment]
These prims are available below M3, but only allow creating one object per program run. Is that still OK?

**Comment by tanabi** [comment]
Yeah, I think the rules should match :)  You're right, there's that nuance that I forgot about.  I'd be fine with copyobj behaving identically.

**Comment by wyld-sw** [comment]
Ok, so I had this thought that prim_copyobj should work similarly to do_clone. I'd like to see if I can use the same function for both. Here is where they seem to differ, though:

| Logic | `@clone` | COPYOBJ |
| --- | --- | --- |
| value of the new thing | MIN(old thing's value, tp_max_object_endowment) | old thing's value if M3+, otherwise 0 |
| home of the new thing | player's location if controls() succeeds, otherwise player | same as old thing (regardless of permissions) |

Questions:
- Should these even work the same?
- Can/should any differences in logic also be tied to the same logic that copies wizard props? (thinking about a boolean that's sent into a slightly-altered copy_prop)

**Comment by wyld-sw** [comment]
Going with `@clone` logic for the time being. But let me know if it needs to be changed.

**Comment by wyld-sw** [comment]
Please check out the new pull request #596.

I don't think it breaks anything! Huzzah!

`@clone` and COPYOBJ should now use the same logic in the actual clone. This means:
- COPYOBJ creates an object with new timestamps, homes it to the player's location or player, and caps its value to tp_max_object_endowment.
- `@clone` creates an object with all flags copied, and interacts with DISKBASE.
- both only copy hidden properties if the player is a Wizard or the program's mucker level is 4.

I hope this doesn't interfere with any `@clone` MUF's logic.

This allowed us to get rid of some (un)helper functions, which made tp_verbose_clone mostly unused, so that's gone. In another bit of meddling, tp_verbose_examine is gone (examine now always shows the type/flags line)

And, as much as I don't think it breaks anything, please test!

**Comment by tanabi** [comment]
Your logic selection makes sense to me.  I'll check out your PR in a moment.

**Comment by tanabi** [comment]
Well done!
