### ISSUE TITLE
ACK!  basedb no longer loads

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#574]
I was testing the Docker build and was finding fbmuck couldn't load the 'basedb' anymore.  It looks like its failing load on the header when I'm digging into strace ... however we don't have very good error reporting on load failures so I'm not sure how its failing.

advancedb still works.

Since basedb is the one we suggest people use in the README files, we should probably make sure it works.  Or remove it and update the README files if we're not supporting it anymore.  I'm honestly not sure what the difference between base and advanced is, so maybe it's time to discard one of them?

**Comment by wyld-sw** [comment]
This was my fault. It's trying to load one more sysparm from the header than currently exists (the 158 in line 4 should be 157).

advancedb has many more programs, including enhanced versions of whisper, page, lib-editor, and gen-mesgboard. Those last two now support GUI operations as well. It also has Keeper.

basedb does have cmd-fetch, cmd-put, and con-census. That last one MIGHT be a companion to `@whengraph`, but it runs on connect, disconnect, and startup.

I would be in favor of just packaging a "starterdb" (a renamed advancedb). We could refine that one over time but also add new ones if needed.

Thoughts?

**Comment by tanabi** [comment]
I would be cool with just using a starterdb ... I get why we have minimal.db, that makes a lot of sense to me, but I never really understood base vs. advanced ... why would you prefer base exactly?

I'd love community input on this but I doubt we'll get it.  It would certainly decrease our 'workload' and suceptability towards bugs to remove the extra DB ... and actually probably reduce user confusion ... so probably a good idea.

**Comment by wyld-sw** [comment]
starterdb now has replaced advancedb - and basedb has been archived.
