### ISSUE TITLE
Restarting advancedb throws all sorts of errors.

### ISSUE THREAD

**Issue by twooeena** [fuzzball-muck/fuzzball#575]
Hi! I'm very, very new to this, but please bear with me because I'm willing to learn.
So I've installed/built a MUCK server from advancedb.db. Running the server as-is (as reccomended in the READMEs) gives me a number of errors, all of which I don't know if the server can run properly through them. After running restart.exe, my command line displays these three errors:
`Object "quit(#139E)" has an invalid object as one of its link destinations!
Object "status;stat(#142E)" has an invalid object as one of its link destinations!
Object "time;date;uptime;nextsav;ns(#147E)" hs an invalid object as one of its link destinations!`
Additionally, a file named muf-errors was created containing a number of error logs as well.
`08/31/20 16:43:47: Keeper(#153) [cmd-watchfor.muf(#80)] Keeper(#153) Error in line 332: Unrecognized word case.
08/31/20 17:05:29: Keeper(#153) [cmd-watchfor.muf(#80)] Keeper(#153) Error in line 332: Unrecognized word case.
08/31/20 17:06:09: Keeper(#153) [lib-strings.muf(#23)] Keeper(#153) Error in line 31: Unrecognized compiler directive.
08/31/20 21:47:24: Keeper(#153) [cmd-watchfor.muf(#80)] Keeper(#153) Error in line 332: Unrecognized word case.
08/31/20 21:47:39: Keeper(#153) [lib-strings.muf(#23)] Keeper(#153) Error in line 31: Unrecognized compiler directive.
08/31/20 21:51:13: Keeper(#153) [cmd-watchfor.muf(#80)] Keeper(#153) Error in line 332: Unrecognized word case.
`
But most worryingly, connecting to the server meets me with these worrying alerts:
`Program not compilable. Cannot run.
WARNING!  The DB appears to be corrupt!  Please repair immediately!`
I then entered "programs" to try to figure out what program was not compatible, and I encountered even more angry tesx, in red this time.
`Programmer Error.  Please tell Keeper what you typed, and the following message.
cmd-programs.muf(#61), line 11; CALL: Program not compilable.
System stack backtrace:
  0) cmd-programs.muf(#61) line 11, in main():
 11:     STRparse pop  ( strX strY )`
This is all just too much for a baby wizard to be able to parse. These might not be bugs at all, or may have been logged previously, but I just don't know how to parse them. Will the server run despite them? Is there a "stable" release of a database preinstalled with programs? (minimal.db worked fine, but I haven't learned how to install programs onto it yet)
Thanks for the assistance.

**Comment by tanabi** [comment]
Hi there;

A surface look at this suggests maybe you're using a version of the MUCK that is older than the advanceDB can use?

First question, what operating system are you using?

Second question, did you compile from source or use some kind of pre-built binary?

**Comment by wyld-sw** [comment]
I've added a link to Winfuzz 7 beta on fuzzball.org; hopefully it'll help. Please let us know if there are still problems with this version of the server.

**Comment by twooeena** [comment]
I believe I'm using the prebuilt package from AppVeyor on Windows 10. I'll try compiling from the winfuzz 7 beta when I get home. Thanks for your help -.-

**Comment by tanabi** [comment]
@twooeena We, admittedly, don't really support the Winfuzz version much because we haven't had a lot of demand for it lately.  If you're still having problems after building the latest one, we'll dig into it because there could be breakages we haven't noticed.

Its good to know someone out there actually uses it, been a lot of debate over dropping support for it altogether, and hearing folks use it / need it really helps weigh in on what we do!

**Comment by tanabi** [comment]
So I tried it out in a VM and the program simply doesn't work in Windows 10 for "compatibility reasons".  So there's something wrong with our build.

This is going to take some digging on our part to resolve.  None of us have a windows dev environment I don't think, so ... its not exactly a small effort to fix!  In the meantime, I can offer you a few alternative suggestions instead of doing a dual boot :) 

Option 1: we're working on a Docker release.  I could accelerate the work here a bit and let you beta test that.  In the future, this is our planned format for release.

Option 2: You could use VirtualBox to run a Linux VM, way better than dual booting

Option 3: You can run a DigitalOcean VM.  It's $5 / mo and plenty for hosting a MUCK.  https://www.digitalocean.com

Option 4: If you want to pay us $5 /mo, Wyld and I have thought about setting up a service hosting MUCKs for people.  We could set up and manage your server side and then you can focus on the creative.

If any of these options appeal to you, let me know.  In the meantime, @wyld-sw and I will draw straws to see who gets to debug the Windows release ;D

**Comment by twooeena** [comment]
Huh. For now, I think I'm going to set up a Linux virtual machine. I'm really trying to use this project as a learning experience. In the future though, when I'm ready to beta test, I would totally be interested in a MUCK hosting service.

**Comment by twooeena** [comment]
Update: Installing a Linux VM worked like a charm and the compiling process seemed to go smoothly for the most part. However, after running `/usr/local/sbin/fb-restart`, I find that no bin folder/server executable has been created during the build process. Which step do I need to troubleshoot to fix this?
(Also if there's a better venue to ask these kinds of questions other than the Github issues forum feel free to lat me know.)

**Comment by tanabi** [comment]
Did you do:

```
sudo make install
```
to install the binaries?  If it built, you should have an 'fbmuck' binary in the src directory.  make install should install them.  If not, I might have to do a screen share or something to see what's wrong. I've been doing this stuff for so long, it is really hard for me to remember the newbie pitfalls :)

Github issues are fine :)  Pretty much anyone who could answer your questions is probably paying attention to this venue.

**Comment by twooeena** [comment]
Yes, I did... Running that again and looking through the output gives me this.

> for d in src; do \
	cd ${d} && make install; \
done
make[1]: Entering directory '/home/aglassman/fuzzball/src'
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/sbin
/usr/bin/install -c fbmuck fb-resolver prochelp /usr/local/bin
/usr/bin/install -c -d /usr/local/share/doc/fbmuck
make help
make[2]: Entering directory '/home/aglassman/fuzzball/src'
cd ../docs && ../src/prochelp ../src/mpihelp.raw mpihelp.txt mpihelp.html > /dev/null
cd ../docs && ../src/prochelp ../src/mufman.raw man.txt mufman.html > /dev/null
cd ../docs && ../src/prochelp ../src/muckhelp.raw help.txt muckhelp.html > /dev/null
cd ../docs && /usr/bin/install -c -m 644 help.txt man.txt mpihelp.txt ../game/data
/usr/bin/install -c -d ../game/data/info
cd ../docs && /usr/bin/install -c -m 644 mpi-intro mpi-intro2 muf-tutorial changesfb7 ../game/data/info
cd ../docs && /usr/bin/install -c -m 644 man.txt help.txt mpihelp.txt mpihelp.html mufman.html muckhelp.html /usr/local/share/doc/fbmuck
make[2]: Leaving directory '/home/aglassman/fuzzball/src'
/usr/bin/install -c ../game/restart /usr/local/sbin/fb-restart

Which look to me like the src folder was built correctly in compile but the bin stuff is being put in various /usr/ folders instead of under fuzzball, which seems to point to defining the file path incorrectly somewhere. Running the fbmuck file that was placed in usr/local/bin in particular gives arguments that indicate it's the executable that should be in fuzzball/bin.
After pointing exec_prefix in restart to that folder instead and rebuilding, running restart produces a pid file in the right place and produces the right logs and stuff. So the question is now, I guess, how do I get the bin files in the right place?

**Comment by wyld-sw** [comment]
All I can think of right now is that there was an issue with the `—prefix` argument to `configure`. I’ll keep thinking, but congrats on getting it running!

**Comment by twooeena** [comment]
Ah. The answer to that is "What prefix argument?" After a bit of reading into ./configure --help, everything has now been installed correctly. Thank you ^_^
