### ISSUE TITLE
FTBFS with Diskbase

### ISSUE THREAD

**Issue by bjbdragon** [fuzzball-muck/fuzzball#579]
I get the following error when compiling. I've defined DISKBASE because I'm planning on running on a Raspberry Pi.
/home/tom/src/fuzzball/src/p_db.c:4402: undefined reference to `global_dumper_pid'

It looks like it needs some ifndef guards there because global_dumper_pid isn't defined.

**Comment by tanabi** [comment]
@bjbdragon We'll take a look at this bug, but you don't need diskbase to run on a Pi.  I can tell from direct experience that a stock build of fuzzball will work fine with a Pi, even if you're running a few other things like a webserver and a DB.

**Comment by tanabi** [comment]
@bjbdragon This was an easy one so I went ahead and pushed up a fix.  The latest master should compile with diskbase.

I'd warn you that nobody really uses diskbase anymore, that's ~so~ early 90s, so I wouldn't be surprised if there were other breakages in it.  So buyer beware :)  Consider just running a normal build and see if it works for you before diving into diskbase.  You can always change it later.
