### ISSUE TITLE
STYLE.md

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#584]
The purpose of this ticket is to write the coding style documentation.  Since I did all the formatting of the code base in its current incarnation, it only makes sense for me to write this. :)

**Comment by tanabi** [comment]
Almost done with this.  There's a surprising lot to it :P

**Comment by tanabi** [comment]
First draft written.

**Comment by wyld-sw** [comment]
Very nice! I especially like the part about threading. I'll merge this in as a first draft, and I'm sure we can chip away at it over the next few months. I can't find much to change about it at this point.

**Comment by wyld-sw** [comment]
Re-opened in case we want to track changes. Feel free to close if you want, though!

**Comment by tanabi** [comment]
Nah we can close it, I like seeing the milestone move :)
