### ISSUE TITLE
Log failed login attempts

### ISSUE THREAD

**Issue by f0x1de** [fuzzball-muck/fuzzball#588]
Could we add a (possibly configurable) feature to log failed logins? Valuable data would include:

1. Date/Time
2. Connection source IP (and reverse DNS if enabled) and TLS yes/no
3. Username attempted

**Comment by wyld-sw** [comment]
Sorry, hit a button by accident. Re-opened, and a good idea!

**Comment by tanabi** [comment]
This should be easy, and I'm kind of surprised it doesn't already do this, but I admit I rarely look at the server logs.

**Comment by tanabi** [comment]
As an added note, I don't see a particular reason to make this configurable, I think it is very reasonable for this to just always get logged.  Really why wouldn't you want this?

**Comment by f0x1de** [comment]
Some people don't want their stuff to change, I dunno!

**Comment by tanabi** [comment]
@wyld-sw Propose we put this in 7.1 since it really should be about 5 minutes to add.

**Comment by wyld-sw** [comment]
Agreed!

**Comment by wyld-sw** [comment]
There does seem to be a FAILED CONNECT message in `logs/status` that mentions the username and the descriptor number. Assuming I didn't misread that, should we put IP/DNS/TLS in both this and the FAILED CREATE messages?

**Comment by f0x1de** [comment]
That would be perfect.

**Comment by wyld-sw** [comment]
Before I commit this, I want to make sure these messages will work for you.

Here are the possibilities for the messages. IP address is replaced by hostname when available.
```
yyyy-MM-ddddTHH:mm:ss: FAILED CONNECT: 'NotAPlayer', descriptor 11, from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: FAILED CONNECT: 'NotAPlayer', descriptor 11, securely from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: CONNECTED: One(1), descriptor 11, from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: CONNECTED: One(1), descriptor 11, securely from 69.174.157.204

yyyy-MM-ddddTHH:mm:ss: FAILED CREATE: 'NotAPlayer', descriptor 11, from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: FAILED CREATE: 'NotAPlayer', descriptor 11, securely from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: CREATED: NewPlayer(118), descriptor 11, from 69.174.157.204
yyyy-MM-ddddTHH:mm:ss: CREATED: NewPlayer(118), descriptor 11, securely from 69.174.157.204
```

**Comment by f0x1de** [comment]
Looks great to me!

**Comment by wyld-sw** [comment]
Pull request at #595.
