### ISSUE TITLE
Docker Build Independent of Machine OS Version

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#590]
Okay so right now I am doing the MUCK compile outside of docker then copying the compiled binary into the dockerfile.  This makes the docker build more simple and faster, but it means the docker FROM statement's operating system has to match the builder or the library versions won't match up.

It is probably better to 'suck it up' and build the binary inside the container.  It means we have to install gcc, etc. in the container and then remove it (to save disk space) or maybe use a base container with dev tools pre-installed.  The latter is probably a better idea than the former, I'm sure there is a base image with build tools on it.

However, in the short term, this doesn't matter, we will document it as an oddity and just be careful that hte versions match.

**Comment by wyld-sw** [comment]
Agreed. This is some great work, and we can refine it later.

**Comment by tanabi** [comment]
I should also automate the docker build as part of this -- right now it will only push to dockerhub when I do it manually.

**Comment by skylerbunny** [comment]
I'm pretty sure I have a workable fix to this, using a multistage Dockerfile, as I proved it out building and running on OS X. Other things the branch I have could potentially do, in addition, is:

- make fbmuck run directly under tinit, so the container respects fbmuck's kill signals natively
- put in an option to use SIGUSR2 instead of the default SIGKILL in the docker build configs
- improved documentation in general

Let me know if you'd like the branch.

**Comment by tanabi** [comment]
@skylerbunny I'd love to see your branch.  Mine does do a few things that I'm not sure yours does -- it auto sets up a fresh MUCK if data files don't exist and it can auto-generate a self-signed cert again if it doesn't already exist.  But, regardless, I could probably merge my stuff into yours (assuming you haven't already covered these cases).  I'm not the best docker guy so I'd bet however you're doing it is smarter than what I had in mind :)

**Comment by skylerbunny** [comment]
I think I need permission to push a branch; I don't think I have it. I attempted earlier and got the equivalent of a 'permission denied'.

**Comment by tanabi** [comment]
@skylerbunny You can do a fork, push the branch up there, and then do a pull request so I can dig into it.  Or @wyld-sw can give you perms to push up a branch temporarily ... we usually work off our own forks and do PR's though, but I don't want to put you through too much trouble.  The contribution is extremely helpful!

**Comment by skylerbunny** [comment]
Oh, right, I forgot it works that way. I'll do the fork on my own and toss up a PR. Thanks!

**Comment by tanabi** [comment]
@skylerbunny I'll be looking out for it then :)  Thanks again.
