### ISSUE TITLE
fbmuck segfaulting on character login

### ISSUE THREAD

**Issue by f0x1de** [fuzzball-muck/fuzzball#592]
Tested on SPR and my own test MUCK.

No available log data aside from the systemd unit log.

```
Feb 01 20:46:46 tassmoj-new systemd[1]: Starting Fuzzball MUCK Server (spr)...
Feb 01 20:46:46 tassmoj-new systemd[1]: Started Fuzzball MUCK Server (spr).
Feb 01 20:46:54 tassmoj-new systemd[1]: fuzzball@spr.service: Main process exited, code=dumped, status=11/SEGV
Feb 01 20:46:54 tassmoj-new systemd[1]: fuzzball@spr.service: Failed with result 'core-dump'.
Feb 01 20:46:59 tassmoj-new systemd[1]: fuzzball@spr.service: Scheduled restart job, restart counter is at 1.
Feb 01 20:46:59 tassmoj-new systemd[1]: Stopped Fuzzball MUCK Server (spr).
Feb 01 20:46:59 tassmoj-new systemd[1]: Starting Fuzzball MUCK Server (spr)...
Feb 01 20:46:59 tassmoj-new systemd[1]: Started Fuzzball MUCK Server (spr).
```

**Comment by tanabi** [comment]
@wyld-sw If your PR fixes this, go ahead and merge it -- i have been crazy crazy crazy today and I won't get to look at this until ... maybe not even until tomorrow.

**Comment by wyld-sw** [comment]
Yikes. My PR fixed a segfault with WHO on the login screen. I'll try to replicate it!

**Comment by tanabi** [comment]
> Yikes. My PR fixed a segfault with WHO on the login screen. I'll try to replicate it!

Yeah, please feel free to merge whatever you need to in order to get SPR unblocked.  If you don't have it figured out in about 4-ish hours I'll take a whack at it :)

**Comment by wyld-sw** [comment]
It does make sense that the segfaults are related. Just really weird it didn't happen in my dev environment.

@f0x1de Please try with the latest code, and sorry for the trouble!

**Comment by f0x1de** [comment]
I should have clarified that I always test SPR stuff on a test replica first, so SPR is just fine. :) Sorry for freaking you out!

**Comment by tanabi** [comment]
@f0x1de yeah I was pretty sure you were doing it on a test instance.  Still, SPR is our 'biggest customer' in terms of FB 7 so we try to take care of you quick as we can when you get issues :)  Though TBH any time a MUCK owner using FB 7 comes out of the wood work with a problem we try to jump pretty quick so anyone out there running smaller MUCKs reading this -- we love you too and file your bugs, we'll treat them urgently <3

**Comment by f0x1de** [comment]
Seems good now!

**Comment by wyld-sw** [comment]
Awesome, thanks for your help!
