### ISSUE TITLE
muck.fuzzball.org cert

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#597]
I got a notification that this cert is going to expire in 30 days.  This is the cert the test MUCK uses.

I'm inclined to switch this to a self-signed cert with an expiration of like 20 years just to never have to think about it again :)  My MUCK client actually isn't smart enough to check validity of the cert so to me it wouldn't matter.  I'm pretty sure we bought a real cert because certain former contributors were vocal about it.

However, if we want to keep using a legit cert, I will purchase this with as many years as it will let me (I think 3 is the max).  It'll only be like $15 to do so.

@wyld-sw do you care one way or another?  The test MUCK seems like it is rarely used anymore.

**Comment by wyld-sw** [comment]
Maybe make it a self-signed cert until we need it to be more?

I'd eventually like to see the test MUCK used more, but I'm not sure how we could back that into our process. Something to think about, eventually.

**Comment by tanabi** [comment]
@wyld-sw Yeah it would be cool to make it run automated tests, which should be pretty doable with the setup I have built that rebuilds it. It actually wouldn't be that hard.

Anyway, I'll switch it to a self signed cert and we can worry about it more later :)

**Comment by conwsh** [comment]
I actually have a script set up for SPR that uses LetsEncrypt and auto-cycles the cert every 90 days.

I think I was bored that day...

**Comment by tanabi** [comment]
I switched this to self-signed and checked to see how often it is used.  Answer: not often (though people do sometimes show up ... maybe once every 3 or 4 months :D )  I will consider the amount of effort I put into this sufficient and move on to the next thing.  I think we should change this down the road to use docker in which case we can set up LetsEncrypt, but I don't have a docker host prepared yet so we'll wait on that for now.
