### ISSUE TITLE
Is Unix Download Instruction in Recursive Loop?

### ISSUE THREAD

**Issue by TogarUshindi** [fuzzball-muck/fuzzball#599]
README.md instructs:
> Unix: download from the Fuzzball homepage

but Fuzzball.org instructs:

> Server Software: Source via GitHub

**Comment by wyld-sw** [comment]
Thanks for the report. We're always trying to improve the documentation. This one's tricky - since we may not always be relying on GitHub (though while we are for the foreseeable future, the website does point there).
