### ISSUE TITLE
morph-hammer.muf including ... something.

### ISSUE THREAD

**Issue by TogarUshindi** [fuzzball-muck/fuzzball#601]
After retrieving morph-hammer.muf from [mufarchive](https://www.mufarchive.com/programs/morph-hammer/83.html), and attempting to compile:
```
Error in line 21: I don't understand what object you want to $include.
Error in line 21: Missing procedure definition.
```
Line 21 is: `$include #7897`

What's #7897? :)

It was made by Triggur, so I thought perhaps it's pointing to an item on FurryMUCK:
```
ex #7897
<garbage> is garbage.
```
Is it pointing to a garbage file perhaps? Or a dbref from another muck?

The source said it came from FBMuf Github so I figured I should ask here.

**Comment by wyld-sw** [comment]
That's a really good guess, that it's pointing to an item on another MUCK. FM, however, has garbage for that dbref as well.

In this version of that program, there are comments saying that the dbref should point to the "cmd-mv-cp" program, which I believe is dbref 60 in starterdb.

"FBMuf Github" may have just been a group of programs that were uploaded once; I remember trying to reach out to MUF Archive to try to harmonize some links, but to no avail. The official fuzzball-muf repo is [here](https://github.com/fuzzball-muck/fuzzball-muf), and I do see it has a different version of morph-edit - though it relies on lib-install, which does have some challenges.

**Comment by TogarUshindi** [comment]
> FM, however, has garbage for that dbref as well.
Ah! You misunderstand! That's where I got that dbref from.

Perhaps I should try changing it to `$include #60` ?

**Comment by wyld-sw** [comment]
Confirmed that #7897 is garbage on FM. It might have been an older copy of the prop cp/mv program.

**Comment by TogarUshindi** [comment]
Ugh, now it's:
```
Error in line 22: I don't understand what object you want to $include.
Error in line 22: Missing procedure definition.
```
Line 22 is `$include $lib/lmgr`
I tried changing it to `$include $lib-lmgr` (dbref #4) and it's still confused.

I hope this doesn't have to do with earlier when I confused line 21 with 22 and installed MUF archive version's lib-lmgr. I used the script which includes all those `@set` commands at the end. Afterward (when it still erred on line 21) I `@rec'ed` the duplicate `lib-lmgr`, but maybe it failed to reset #4's registers. Not sure. Just thinking aloud.

**Comment by TogarUshindi** [comment]
Just tried doing those `@set` commands at the end of the muf script to see what would happen now.
```
I don't understand 'lib-lmgr'.
I don't understand 'lib-lmgr'.
I don't understand '$tmp/prog1'. (a million times)
```

**Comment by wyld-sw** [comment]
Hmm. Starterdb should definitely recognize $lib/lmgr. lib-lmgr would probably not work unless you were in the same area as the program (Keeper's inventory?)

What do you see when you type `@reg lib` ?

**Comment by TogarUshindi** [comment]
```
Registered objects on Room Zero(#0RO):
  lib/alias: lib-alias(#11FLVM3)
  lib/away: lib-away(#23FLVM3)
  lib/bits: lib-bits(#141FLVM3)
  lib/edit: lib-edit(#13FLVM3)
  lib/editor: lib-editor(#18FLVM3)
  lib/ignore: lib-ignore(#16FLVM3)
  lib/lmgr: <garbage>
  lib/match: lib-match(#5FLSHVM3)
  lib/mesg: lib-mesg(#14FLSBHVM3)
  lib/mesgbox: lib-mesgbox(#17FLSBHVM3)
  lib/props: lib-props(#6FLSHVM3)
  lib/reflist: lib-reflist(#15FLSBHVM2)
  lib/stackrng: lib-stackrng(#7FLSHVM3)
  lib/strings: lib-strings(#8FLSHVM2)
  lib/table: lib-table(#9FLSHVM3)
  lib/timestr: lib-timestr(#10FLVM1)
  lib/wf: cmd-watchfor(#25FWLVM3)
Done.
```

Uh-oh! Hah! Okay, so yeah.. looks like it's pointing to my old, recyled duplicate. I just need to re-register it to #4... somehow...

(That's your cue, please. :) Sorry about this!)

**Comment by wyld-sw** [comment]
`@register lib-lmgr=lib/lmgr` SHOULD do it.

**Comment by wyld-sw** [comment]
and if it can't find it, `@register #4=lib/lmgr`

**Comment by wyld-sw** [comment]
If #4 (the original one) is garbage, then please use your new one.

**Comment by TogarUshindi** [comment]
`I don't understand 'lib-lmgr'.`

Same as-- ahhah! Okay. was wondering if I should try that. It's not a global, so maybe just couldn't find it. That makes me think that Triggur's script assumes/requires you to be in the same room as the item.

```
Used to be registered as _reg/lib/lmgr: <garbage>
Now registered as _reg/lib/lmgr: lib-lmgr(#4FLSBHVM3) on Room Zero(#0RO)
```
That seems to have done it.

Now, do I need to run all the following `@set` commands [listed at the end of the script](https://www.mufarchive.com/programs/lib-lmgr/159/view)?

**Comment by TogarUshindi** [comment]
(Judging that the compile still didn't work for line 22 I'm going to guess yes, or some variant)

**Comment by TogarUshindi** [comment]
Looks liked it worked! Dealing with `.pmatch` compiler issues now, but lib-lmgr is back in the game!

I am 1337 haxxor man. 8)

**Comment by TogarUshindi** [comment]
From http://captainpackrat.com/furry/globals.txt ...
```
mv-prop ( d1 s1 d2 s2 -- count )
  Moves prop/propdir from item d1 to item 'd2' renaming it to 's2'.
```

**Comment by wyld-sw** [comment]
I'm seeing mv-prop as a word in #60. Hmm.

**Comment by TogarUshindi** [comment]
Wow, these old programs sure are interconnected, aren't they?

**Comment by tanabi** [comment]
I just want to throw out ther that Triggur MUFs are notoriously hideous :)  I want to stress that it isn't his fault, mind, he wrote these things in a way way older version of fuzzball.  But, it's a little like trying to get a 286 program to work on a Windows 10 machine without an emulator now.

You're better off using another morpher if you can get away with it.  I wrote one years ago but sadly don't have it any more ... one of these days I should make a replacement for it :P 

This all being said, if you get stuck let me know and I can come to your MUCK and sort it out.  I've done it before, I'm sure I can sort it out again :)

**Comment by TogarUshindi** [comment]
Greetings @tanabi !

> You're better off using another morpher if you can get away with it. 

Is there one?

**Comment by tanabi** [comment]
There's several!  Jessy's got one.  Granted, it is a very confusing one :)

http://www.rdwarf.com/users/mink/downloads/desctools.muf.html

This page has a bunch of morph programs listed, though you'd have to chase them down:

http://www.soappuppy.com/muck-info/morphing/

**Comment by tanabi** [comment]
Looks like even on FM there's several morphs... search this list for the word 'morph':

http://www.furrymuck.com/getting-started/programs_list.html
