### ISSUE TITLE
Is SSL really working?

### ISSUE THREAD

**Issue by TogarUshindi** [fuzzball-muck/fuzzball#602]
@wyld-sw Something I noticed.

That one muck you showed me the other day.
```
Player Name           On For Idle   Doing...
Player1                4d 19:51   7m @ 
Player2                4d 20:04   5m @ Being foxy.. what else?
Player3                4d 20:05  53m @ 
3 players are connected.  (Max was 5)
```
They all have `@` marks to show their connection is secure.

However, mine does not. It only shows a `@` for the player's own connection. The other players' connections appear as non-SSL to that player.
```
Name               On for Idle                                           Doing
Player1             00:00   0s@                                               
One                 00:04   4m                                                
Togar               00:04   4m                                                
3 players shown of 3 online (max connected is 7).
```

Perhaps a sign of faulty SSL implementation? Perhaps due to it being self-signed? Or something else perhaps? A fault in the code maybe?

Also noticed the space between idle time and `@` is not present on mine like it is on the other MUCK, and the "Doing" is much farther right.

**Comment by wyld-sw** [comment]
I think the second example has a softcoded `@who` action that overrides the standard WHO action. In starterdb it is #37.

I had never noticed it, but yes, it does look like the code for that program intends to only show @ for the player issuing the command.

**Comment by wyld-sw** [comment]
A case might be able to be made for showing @ for all if you're a Wizard, at least.

**Comment by TogarUshindi** [comment]
A case for making it visible to other players to that it allows other players to point out it's missing, and they might want to look into securing their connection. Sort of a way of saying "Hey, your shoe's untied. Might want to lace it." It's good information! Let's both parties know they're secure.

Just a note, on the other MUCK, I'm obviously not a wiz and can still see it.

**Comment by wyld-sw** [comment]
Right, since it doesn't have that version of the softcoded command. I just say that HLM has an update to remove that logic (and thus it shows for all). A future update probably will change it in the starterdb programs, but you can get ahead of it by deleting line 81 and 83 of the program.

You can also remove or rename the `@who` action.

**Comment by TogarUshindi** [comment]
I typically use `WHO` actually, not `@who` :) Whowhowhowhowho

**Comment by wyld-sw** [comment]
If `@who` is present, it is triggered from `WHO`.

**Comment by wyld-sw** [comment]
I'm on your freenode if you'd like to chat more realtime.

**Comment by TogarUshindi** [comment]
> but you can get ahead of it by deleting line 81 and 83 of the program

Which one? `wd`?

**Comment by wyld-sw** [comment]
yes.
