### ISSUE TITLE
Add SMTP Support to MUCK

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#607]
I'm posting this issue for feature visibility more than anything -- I have actually already programmed this!  I just need to test it thoroughly.

For Hope Island, I wanted to make the registration workflow work like this:

* User signs up on website
* Wizards on MUCK get a notification with the registration info, user is put on queue
* Wizards approve or deny character
* Email is sent to user.

The problem is "email is sent to user" ... there's no way for a MUCK to trigger an external action.  Either I have something poll the MUCK, I enable the MUCK to run local commands (Didn't want to do this for security reasons) or I add SMTP support.

It turns out SMTP support can be added with a single .h and .c file.  https://github.com/somnisoft/smtp-client is available with a creative commons license and is designed to just be included in your project.

A problem that may come up during testing is it may need to be forked into its own process.  I will try to fix this by making the timeouts more aggressive because I want the caller to get an error if there is a failure rather than assume success and have emails going nowhere.

I've implemented this with some `@tune` params and the new SMTP_SEND MUF primitive.  It could be used for all kinds of things -- event notifications, monitoring, triggering external processes, etc. - so I think it is a valuable addition.  And if you don't want it, simply don't configure it and it will be dormant.

**Comment by tanabi** [comment]
I think it would be wise, maybe not now, but later to make a SMTP_SEND_ALL to send a message to a list of email addresses.  This would require a process fork for sure so it doesn't lock up the MUCK.  But it would allow for event notifications which is pretty cool I think.

**Comment by wyld-sw** [comment]
I like it! In my mind I was stuck on a solution involving MCP for this, I think making things explicit like this is a good idea.
