### ISSUE TITLE
Editplayer Crashes when Inserting at Line 0 (SF Issue)

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#610]
How to replicate:

1. Type 'editplayer' [enter]
2. Select option 2 - Description
3. Type .i 0
4. Get crash:

Programmer Error. Please tell Wizard what you typed, and the following message.
lib-editor(#16120), line 90; STRNCMP: Non-string argument.

@version
Version: Muck2.2fb6.08 Compiled on: Tue Mar 24 2009 at 19:10:22 PDT

Replicated on FurryMUCK.

Might also be caused by relative addressing:

```
.i
< Insert at line 6 >
.i -1
< Insert at line 5 >
.i -5
Programmer Error. Please tell SpinDizzy what you typed, and the following message.
lib-editor(#14), line 89; STRNCMP: Non-string argument.
```

This program is included with the MUCK (or so the original issue says) so putting it on fuzzball repo instead of the fuzzball MUF repo, but the fix should be done in both.

**Comment by wyld-sw** [comment]
I *think* this needs to be fixed in one of the libraries (lib-edit or lib-editor), but I've forgotten which one :). The negative addressing is kind of a neat feature (but not necessary), but it definitely shouldn't crash.
