### ISSUE TITLE
Issue starting fbmuck 6/7

### ISSUE THREAD

**Issue by foxbird** [fuzzball-muck/fuzzball#62]
Opened from e-mail delivered to me:

From: Obscenity Furr (email redacted)

I've tried both fbmuck 6 and 7 and both cant do anything but print the help screen, trying to run a server just flashes another console, I've tried adding '-freeconsole' but the console still flashes, this time creating 0 byte log files.

The systems I've had the same issue on are Ubuntu Server 16.10 and Windows 10. I've also tried compiling it myself, same issue.

Can you help me out?

**Comment by ObscenityIB** [comment]
Hey, thanks for getting back to me, and a fellow fox too!
For your first question, yes, i have tried the packages from fuzzball.org, but first i cloned the latest git changes and used those, it compiled fine on Ubuntu but getting to the point of doing anything but print the help or do nothing, seems to be impossible.

The windows version from the site had 'restart.in' and was a bash script, so pretty useless, but i copied someone elses ini file and adjusted it to the ports i want to use, restart.exe also just flashes another console with no output.

The status file only tells me what fbmucks pid is, they say nothing else, when i check for that proccess, it doesnt exist, when i check for things listening on the port, there is nothing.


Thats about it from me, what else do you need to know?

**Comment by gneujahr** [comment]
Yep! I do the fox thing well enough it seems.

I've tested out the windows build from the alpha 02 release tag that appveyor built and it seems to have an issue just as you describe. Even with a correct command line it opens a window briefly that immediately disappears right after creating a PID file. So, I took the source from the alpha 02 tag and built it on my machine locally and everything seems to work well. So, there's something wrong with appveyor's windows build. I'd be happy to provide you with a stable alpha 02 release if you like.

As for the Linux side, that'll take some debugging. I imagine you successfully were able to use `configure` to configure it to your system, and `make` to build an executable. I'm not sure where it goes if you `make install` as I've never wanted to get that far. However, you should be able to test it out running directly from the 'game' folder. Here's a quick script I did to build and test:

```
foxbird@FOXTOME:~$ mkdir sandbox
foxbird@FOXTOME:~$ cd sandbox
foxbird@FOXTOME:~/sandbox$ git clone https://github.com/fuzzball-muck/fuzzball.git fuzzball
foxbird@FOXTOME:~/sandbox$ cd fuzzball
foxbird@FOXTOME:~/sandbox/fuzzball$ git tag
v7.0-alpha.1
v7.0-alpha.2
foxbird@FOXTOME:~/sandbox/fuzzball$ git checkout -b alpha2 v7.0-alpha.2
Switched to a new branch 'alpha2'
foxbird@FOXTOME:~/sandbox/fuzzball$ ./configure
 ...
foxbird@FOXTOME:~/sandbox/fuzzball$ make
 ...
foxbird@FOXTOME:~/sandbox/fuzzball$ cd game
foxbird@FOXTOME:~/sandbox/fuzzball/game$ ../src/fbmuck data/minimal.db data/minimal.out 8888
foxbird@FOXTOME:~/sandbox/fuzzball/game$ ps auxw | grep fb
foxbird   7851  0.0  0.0      0     0 ?        Ss    2433   0:00 ../src/fbmuck data/minimal.db data/minimal.out 8888
foxbird   7854  0.0  0.0      0     0 ?        S     2433   0:00 grep --color=auto fb
foxbird@FOXTOME:~/sandbox/fuzzball/game$ telnet localhost 8888
```

The above procedure works just fine on an Ubuntu box I had around. Mind you, that just gets the muck running. If you want to actually run it reliably, you'll want to investigate the `restart` shell script in the game directory, and perhaps even `make install` thing. That will make sure that you do things like swap out database and macros files when it shuts down and such. All very useful.

Let me know how it goes. I'll leave this ticket open here until I can get someone to look at the appveyor builds and why it's not working.

**Comment by foxbird** [comment]
Yep! I do the fox thing well enough it seems.

I've tested out the windows build from the alpha 02 release tag that appveyor built and it seems to have an issue just as you describe. Even with a correct command line it opens a window briefly that immediately disappears right after creating a PID file. So, I took the source from the alpha 02 tag and built it on my machine locally and everything seems to work well. So, there's something wrong with appveyor's windows build. I'd be happy to provide you with a stable alpha 02 release if you like.

As for the Linux side, that'll take some debugging. I imagine you successfully were able to use `configure` to configure it to your system, and `make` to build an executable. I'm not sure where it goes if you `make install` as I've never wanted to get that far. However, you should be able to test it out running directly from the 'game' folder. Here's a quick script I did to build and test:

```
foxbird@FOXTOME:~$ mkdir sandbox
foxbird@FOXTOME:~$ cd sandbox
foxbird@FOXTOME:~/sandbox$ git clone https://github.com/fuzzball-muck/fuzzball.git fuzzball
foxbird@FOXTOME:~/sandbox$ cd fuzzball
foxbird@FOXTOME:~/sandbox/fuzzball$ git tag
v7.0-alpha.1
v7.0-alpha.2
foxbird@FOXTOME:~/sandbox/fuzzball$ git checkout -b alpha2 v7.0-alpha.2
Switched to a new branch 'alpha2'
foxbird@FOXTOME:~/sandbox/fuzzball$ ./configure
 ...
foxbird@FOXTOME:~/sandbox/fuzzball$ make
 ...
foxbird@FOXTOME:~/sandbox/fuzzball$ cd game
foxbird@FOXTOME:~/sandbox/fuzzball/game$ ../src/fbmuck data/minimal.db data/minimal.out 8888
foxbird@FOXTOME:~/sandbox/fuzzball/game$ ps auxw | grep fb
foxbird   7851  0.0  0.0      0     0 ?        Ss    2433   0:00 ../src/fbmuck data/minimal.db data/minimal.out 8888
foxbird   7854  0.0  0.0      0     0 ?        S     2433   0:00 grep --color=auto fb
foxbird@FOXTOME:~/sandbox/fuzzball/game$ telnet localhost 8888
```

The above procedure works just fine on an Ubuntu box I had around. Mind you, that just gets the muck running. If you want to actually run it reliably, you'll want to investigate the `restart` shell script in the game directory, and perhaps even `make install` thing. That will make sure that you do things like swap out database and macros files when it shuts down and such. All very useful.

Let me know how it goes. I'll leave this ticket open here until I can get someone to look at the appveyor builds and why it's not working.

**Comment by ObscenityIB** [comment]
Thanks, ill try again on Ubuntu and get back to you.
Also `make install` is a bad idea, because there is no `uninstall` rule defined, learned that the hard way. Real hassle to remove manually.

**Comment by wyld-sw** [comment]
One option is to specify a --prefix with configure. It will tell make where you'd like it to install.

**Comment by ObscenityIB** [comment]
@foxbird following the steps you did seemed to work, i can connect and use it now, thanks!
