### ISSUE TITLE
cmd-page allows wizard-owned puppets to page (SF issue)

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#637]
A Wizard-owned puppet is allowed by cmd-page to send a
page, whereas a mortal-owned puppet is not. It is
impossible to reply to the puppet, as well.

(Relayed from Genn@FurryMUCK)

**Comment by wyld-sw** [comment]
It seems like the cmd-page included with starters only worked for players. Maybe this was specific to FurryMUCK from decades past.

**Comment by tanabi** [comment]
I'll close this since you can't reproduce it.  :)
