### ISSUE TITLE
Add allowing registration on login screen by @tune

### ISSUE THREAD

**Issue by Kjesris** [fuzzball-muck/fuzzball#662]
Still can't really figure it out :P
i just rather use create on the login screen (on my own muck) instead of having to @pcreate every single user

**Comment by tanabi** [comment]
@Kjesris as a wizard character, type:

`@tune registration=no`

and I think that's all you have to do to enable 'create' on the login screen.

**Comment by Kjesris** [comment]
> @Kjesris as a wizard character, type:
> 
> `@tune registration=no`
> 
> and I think that's all you have to do to enable 'create' on the login screen.

That's hella... unintuitive.
