### ISSUE TITLE
{contents} MPI function does not behave as documented / nonsense exits behavior

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#667]
According to the documentation, the `{contents}` MPI call supports exits.  For instance, you can do:

`{contents:here,exit}` and it will work.

However, this will always return nothing because exits aren't contents.  They have their own linked list that `{contents}` doesn't check.

The solution here is to update the documentation to indicate that exits should be checked with the `{exits}` macro and remove mention of the 'exits' parameter to 'contents'.  'contents' should probably throw an error directing people to use 'exits' if you pass 'exits' as a parameter to it.

**Comment by wyld-sw** [comment]
Solved as suggested via #679.
