### ISSUE TITLE
{force} allows escape character in input

### ISSUE THREAD

**Issue by Loonesbury** [fuzzball-muck/fuzzball#676]
When a player is forced by MPI, the command string isn't sanitized compared to normal client input, so you can get \27's into logfiles and the database. This might not necessarily cause problems, but I'm not sure if it's intended behavior.

To reproduce:
```
@mpi {force:me,@desc me=\[[1;33mhello world}
```

**Comment by tanabi** [comment]
While it isn't intended behavior, I'm also not sure it matters enough to fix?  If it's easy to fix, let's do it, i.e. if we can use some existing sanitization routine.  I *believe* there is such a routine but my memory is a little rusty there.

**Comment by Loonesbury** [comment]
Gotcha, thought I'd ask before just going ahead and doing it.
