### ISSUE TITLE
Appveyor build failing with Conan 2.0

### ISSUE THREAD

**Issue by aidanPB** [fuzzball-muck/fuzzball#684]
Pretty straightforward: Conan 2.0 eliminated the "user" command, so now Appveyor chokes before it even tries to actually build fbmuck. We can alter the `pip install` line to ensure that we use a 1.* version of Conan, or we might be able to just eliminate the `conan user` line entirely.

**Comment by wyld-sw** [comment]
Altered the pip install to use 1.62.0 in #708.
