### ISSUE TITLE
Wizards can GUEST themselves, but can't un-GUEST themselves

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#685]
This one was reported to me, I haven't tried to reproduce it yet due to its 'destructive' nature but I'm sure it's true:

To quote:

....

As a wizard, I set the guest flag on myself, then couldn't remove it.

But maybe should consider not allowing guest flag to be set on a  player who is already wizard.  Or I suppose letting a guest-flagged wizard unguest flag themselves.

...

An untested but possibly big issue is perhaps One could guest themselves and maybe not be able to unguest themselves depending on how the code is written and if the MUCK is compiled with GODPRIV or not.

My feeling is that a wizard should be able to GUEST themselves if they want to (as it may be useful for, say, debugging purposes or otherwise) but should be able to un-GUEST themselves rather than to block them from being GUEST-ed.  This enables the most flexibility and I don't think has any particular downsides.

**Comment by wyld-sw** [comment]
Confirmed, as once you're set G, you can no longer use the `@set` command. Should Wizards bypass the "Guests are not allowed to XXXXX." logic entirely, or just for `@set`?

**Comment by aidanPB** [comment]
I think ideally Wizards should bypass the logic only for setting themselves
!G, even, requiring them to un-GUEST themselves before setting or unsetting
any other flags or properties. That might be more complicated than it's
worth, though.
