### ISSUE TITLE
DESCRDBREF is not a direct replacement for CONDBREF

### ISSUE THREAD

**Issue by Sqrlly** [fuzzball-muck/fuzzball#697]
With FB7 CONDBREF was replaced with an inserver macro of DESCRDBREF.  However con numbers are sequential from 1 up to concount.  Descr numbers may be in any order.  An easy fix is instead changing the macro to replace CONDBREF with 'CONDESCR DESCRDBREF' and that would work cleanly.  I had changed that macro expansion on a fb7 server and the existing code then works.

However due to a server crash a new version of FB7 was compiled and CONDESCR appears to no longer exist (other than as an empty replacement macro).  This makes using CONDBREF impossible.  (Well short of using '#-1 DESCR_ARRAY' and popping out the nth element and discarding the rest of the array, which would be poor practice to be doing in a loop.)

**Comment by wyld-sw** [comment]
You are absolutely right, this case (relying on traditional connection numbers in a loop) does need special handling with the new direction. We recommend using `#-1 firstdescr` and `nextdescr` to navigate the connections in a similar way.

@tanabi contributed a version of the 3who MUF that includes both techniques dependent on server version (the version in starters is just for fb7.1 at this point). Hopefully it helps, and please reach out if we can assist in getting you back up and running at full strength.

[backward compatible 3who](https://github.com/fuzzball-muck/fuzzball-muf/commit/3b0c26ac7b31b8264c82f3b1ebea9d47357ae16a)
[7.1 release with modification notes](https://github.com/fuzzball-muck/fuzzball/releases/tag/v7.1)

@tanabi, if I missed anything that would be helpful here, please let me know.

**Comment by tanabi** [comment]
@Sqrlly @wyld-sw Yeah -- the connection vs . descriptor thing in MUCKs has been a longstanding complication in both the guts of the server and in terms of MUF prims.  For 7.1 we decided to make the breaking change to get rid of the connection stuff and thus simplify some things at the expense of making certain cases more complicated.

It is, however, pretty trivial to make backwards compatible code as you can see from our 3who example.  It is probably possible to fix your macros to work with the new system.  If you'd like me to help, I am super happy to do so, I just helped SPR out with ... actually one of your MUFs converting it to the new system (your `@who` program).

I am totally happy to take on whatever conversion work you need done to minimize the impact to you and your MUCK :)

**Comment by Sqrlly** [comment]
Yes my @WHO is one I'm working on too.  I know how to rewrite it so it works with the descr's.  I use them for lots of stuff like bootme and reconnect.  But I hoped to keep all older programs compiling and working as-is without having to modify them, preferably.  With condescr (and fixing the incorrect condbref macro) I was able to do that.

If not going to provide a function to convert con numbers to descr numbers, you may need to just remove all the con* macros as there's no way they're going to work, and might as well make the programs unable to compile and clearly show what isn't supported rather than getting strange runtime errors that will take time to figure out why.

**Comment by tanabi** [comment]
@Sqrlly The `@who` program does neeed a wiz bit because it looks up hosts :)

So I spoke it over with @wyld-sw and this is kind of a situation where you can't please everyone.  I run a MUCK myself, and when I think of all the weeds that the 'con' prims are in ... I dunno, I think most cases, our internal macros to map the old CON* stuff to DESCR* stuff does a best-case attempt at compatibility.  For the majority of programs, including random stuff like `@bootme` which are common but somewhat rarely used, our internal macros keep them running without crashing.

I'd, personally, rather have a couple weird edge cases (like 3who and your `@who`) bite me than connect to a MUCK with dozens of errors in all kinds of nooks and crannies that might take weeks to find them all.

Making changes like this is always pretty painful, but we do our best to minimize impact.  Very sorry it has caused you grief though.

**Comment by Sqrlly** [comment]
Then I suggest just leaving CONDESCR in there for compatibility (remove the other con* ones as you have).  And stuff like CONDBREF and CONHOST macros include CONDESCR before the DESCR replacement.  That should then leave everything compatible like you want.

**Comment by tanabi** [comment]
@Sqrlly So you're proposing, basically, that CONDESCR would map a number to a number of hops on the descriptor linked list?  That would enable a sequential number of calls which allows the old 0 to CONCOUNT style loop at the expense of being massively inefficient (we'd be navigating the descriptor list many, many times ... If I'm not mistaken, this is O(N^N) though I'm not great at my O's :) ).

I dunno, there's a relative minority of MUFs that use the old school loop architecture vs. MUFs that use random CON* prims in them to do assorted things.  Most of the newer MUFs that do similar things use ONLINE_ARRAY from my surveying around.  The conversion is really super easy to do, too.  I think adding a bad implementation of a deprecated feature to avoid a few relative edge cases is probably not a good idea.

**Comment by Sqrlly** [comment]
Well actually it's 1 to concount/descrcount.  And CONDESCR already existed and worked fine.  And yes, it mapped a connection number (1...N) to it's equiv descr number.  That's all it did.  You could look at how that was coded before it was taken out in fb7.  That would be the only old 'con' function needed and the rest are already mapped over to their equiv descr* function.  And a couple of in-server macros would need to be fixed.

And yes I also agree for writing new muf code or code you're already editing to use the new descr functions.  Documentation for the old primitives can point people to the new ones.  But for programs that already exist, rather than having them suddenly be broken (like happening here), that would allow simple compatibility for the older code.  Not all mucks have coders with 30 years muf experience to track down the issue and recode stuff for them. :-)

**Comment by Sqrlly** [comment]
(Hrmm, I have at least a dozen references to con* functions in WHO alone...  contime, conidle, condbref, condescr, conhost, conuser, concount...  All broken other than maybe concount, across 400+ lines of code, 20+ user functions/words.. all going to have to be revamped because no easy fix...)

**Comment by wyld-sw** [comment]
Maybe instead of #-1 FIRSTDESCR / NEXTDESCR, you can use DESCR_ARRAY ARRAY_REVERSE.

**Comment by Sqrlly** [comment]
Yeah I ended up using the DESCR_ARRAY for fb7+.  Though can't use it for fb5 compatibility because arrays are introduced in fb6.  FIRSTDESCR / NEXTDESCR was so close to using con numbers that had figured I could keep all the main logic the same but just slip descr numbers in instead.  Of course replacing 1 + with a 'next' function.

I do still recommend restoring the CONDESCR primitive and fixing the other macros.  Or removing all the con macros and let those programs using them fail to compile.  @tanabi was worried about all the old programs using con breaking because of that, but they are already broken.  None of the con macros besides concount will work without condescr in there.  Because they're being passed a con number and you can't correctly call a descr function with a con number without converting it first.

And thanks for the help and input too. :-)
