### ISSUE TITLE
Page needs 'W' bit

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#700]
This is a similar issue as #699 and best fixed at the same time.

cmd-page (ref `#101` in the starter DB) needs a W bit.  It's currently just got an M3 and it makes "weird things" happen.  For instance, you get a message like the player doesn't exist if you try to page someone who's asleep, and `p #mail` doesn't work.

`@set #101=w` should fix this.

**Comment by wyld-sw** [comment]
#701 fixes this! Good catch.
