### ISSUE TITLE
`@sweep` fails to detect some say/pose/etc. traps

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#73]
The built-in command `@sweep` is intended to identify say traps on the environment, but it assumes that say traps will be linked to a MUF program. Therefore, it won't detect some secnario like:
```
@create ThingWithSayTrap
@act say=ThingWithSayTrap
@lock say=me&!me
@link say=here
@fail say={null:some MPI that does something with {&arg}}
drop ThingWithSayTrap
@sweep
````

**Comment by wyld-sw** [comment]
@sweep should now report any linked exit matching the name, regardless of destination type.
