### ISSUE TITLE
(minor?) error in standard starter db.

### ISSUE THREAD

**Issue by KETNAR** [fuzzball-muck/fuzzball#732]
_prefs/ws/doing:2:
        [1;35mDoing: [0;35m%[doing]s

^ This causes sanity errors on first load and it gets stripped out as a result.

_prefs/ws/doing:2:[1;35mDoing: [0;35m%[doing]s

^ How it should look.

effected lines.

https://github.com/fuzzball-muck/fuzzball/blob/6c985b6679843122a78b9ef76609171de3614e97/dbs/starterdb/data/starterdb.db#L2515
https://github.com/fuzzball-muck/fuzzball/blob/6c985b6679843122a78b9ef76609171de3614e97/dbs/starterdb/data/starterdb.db#L2516

**Comment by tanabi** [comment]
Oh interesting.  Yeah, that newline is no doubt causing an issue.  That can be a tricky file to edit with its binary content :P

**Comment by KETNAR** [comment]
No problem. I caught it fairly early, and was able to just bring the missing line over from the original db and then back out the errant /r and /t etc and all was well.

Not my first time manually editing one of these, but still a problem as you said.

**Comment by wyld-sw** [comment]
Pull request #733 probably fixes this. Thanks @KETNAR for the report!

**Comment by KETNAR** [comment]
BTW, I finally noticed where errant \r senpi came from.

https://github.com/fuzzball-muck/fuzzball-muf/blob/b701d0421fa554fca074879ab35f3dec45dd4c35/HLM/cmd-whospecies.muf#L299

```
                       |-- Hi there lil' guy!
                       \/
#0 "_prefs/ws/doing"  "\r        \[[1;35mDoing: \[[0;35m%[doing]s" setprop
```

Which .. isn't.. a bug.. exactly? How the muck handles storing it into the DB.. kinda is? maybe? I'm not sure how the case handling for a \r stored by setprop via muf is supposed to go down.

Look, Mucks are voodoo wrapped in mystique soaked in guessoline, and you all are far more familar with where the matches are. :P

The line can be properly stored (without becoming a literal db breaking CR) with a simple..

@set #0=/_prefs/ws/doing:\r       \[[1;35mDoing: \[[0;35m%[doing]s

And it works just fine, carries the line down and indents it as intended, and (so far) has not turned into a db-monching actual \r in-file.

`
Stat  Name____________________  Sex________  Species___________________________
      Keeper[asleep]                         
test  One                       Boop         Baked Potato
       Doing: ==Testing==
---(  )----------------------------------------------------( 1/2 Room Zero )---
`

Not sure how to fix it in the muf itself so it stores cleanly (yet) however.
