### ISSUE TITLE
Problems with the quick start guide/starting FBMuck 7

### ISSUE THREAD

**Issue by Ninjacat64** [fuzzball-muck/fuzzball#740]
I do not have experience running a MUCK server, and I am using the prebuilt package due to the extreme agony and 0% success rate of trying to download and compile someone else's code, downloaded from https://www.fuzzball.org/software/winfuzz-7.zip , running on windows 10, because having to 
After figuring out how to create the restart.ini file (why is this not just included in the distribution? Having to generate it this way seems needlessly obtuse). I was getting Verifying input file...FAILED.
Perhaps it was naïve of me to assume the default setting for restart.ini would function, as it was searching for minimal.db in data\mininal.db, instead of it's actual location; dbs\minimal\data\minimal.db (did someone move mininal.db and forget to change the default settings to match it?)

After that, though I was able to start the server, where it immediately closed immediately afterward, only showing up as a console window displaying LOADING: data\minimal.db and LOADING: data\minimal.db (done), similarly to issue #62, which has apparently been resolved seven years ago? Is this distribution this out of date?
It may be noteworthy that when I tried to install the C++ redistributable, it failed because it said I already have a newer version.

Am I doing something wrong, are the instructions incorrect, or is there something wrong with the program itself?

[restart.txt](https://github.com/user-attachments/files/18105296/restart.txt)
[status.txt](https://github.com/user-attachments/files/18105297/status.txt)

**Comment by tanabi** [comment]
Hi there;

The windows build of the MUCK isn't very well supported anymore; the core maintainers are @wyld-sw and myself and neither of us have a windows development environment which makes it difficult to support the native build.

if you want the easiest possible way to run the MUCK server, I would recommend using docker.  This is the most supported and recommended way to run a platform-independent copy of the MUCK.  https://docs.docker.com/desktop/setup/install/windows-install/

After you have docker downloaded, grab a copy of the repo -- a ZIP file version is fine:

https://github.com/fuzzball-muck/fuzzball/archive/refs/heads/master.zip

Unzip it somewhere, open a command prompt, and navigate to that directory.  Then type:

```
docker-compose up
```

and it should start up :)  It will default to being on port 4201

There may need to be some tweaking to configuration to get it to work right ... my experience with Windows and Docker is more theoretical than practical :)  Here's the documentation for our dockerfile which explains a lot of the configuration.

https://github.com/fuzzball-muck/fuzzball/blob/master/README_DOCKER.md

If you have specific errors or problems feel free to post them here and we'll try to help you through it.

**Comment by Ninjacat64** [comment]
If that version is not functional or supported, then perhaps it should not be the only available build.

I was actually able to start the server successfully by using 
```bat
fbmuck dbs\minimal\data\minimal.db data\minimal.out 4041
```
and just using restart.exe to update the database.

It seems that the problem lies with restart.exe not starting the server properly, and not the server software itself.
If I had to guess, either it's trying to run fbmuck with arguments that don't work, you are using the wrong _spawn function, or you are using it with the wrong "mode" argument.
I feel like this is something I might be able to fix myself, but experience has taught me trying to build anything cloned from git is a fool's errand, my experience with C++ is apparently too limited to understand what is even going on in line 601-630 of restart.cpp, and if you don't care about fixing this, then why should I?
After all, I could get the same result from a batch file.

I'm trying not to be rude here, but I think I might have failed...

**Comment by tanabi** [comment]
We've gone back and forth about if we should continue to have the windows build or not.  There are folks that advocate strongly for keeping it, so ... we're keeping it as it does largely work.  It's no the only available build, though.  As mentioned the docker build is available and works on any platform :)  We encourage its use for those that don't want to do their own build.

I didn't even know Windows used an exe to manage the restarting ... on all other platforms its a bash script.  I'm not surprised its doing it wrong.  I wholeheartedly believe you should be using a batch file instead of a janky probably-hasn't-been-looked-at-in-20-years exe file :)

The restart script does slightly more than just start the program -- it moves the database files around so they're in the right 'position' to be the correct in / out file.  Here's the UNIX script:

https://github.com/fuzzball-muck/fuzzball/blob/master/game/restart.in

It handles a lot of 'weird' cases like dealing with panic databases.  If you want to make a windows restart script, I would be happy to add it to the repo and make it the official way to run the windows port.

**Comment by Ninjacat64** [comment]
My current batch file just runs restart.exe, then launches fbmuck.exe with static functioning arguments.
```bat
restart.exe
fbmuck.exe dbs\pocket\data\pocket.db dbs\pocket\data\pocket.out 4201
``` 
I assume if you want a replacement restart script, you'll want something fancier than that that can do everything on it's own and uses the ini file.

That would probably be something that I could get working eventually, but the main problem for me is, why should I even bother? I don't know how long ago that build was, but the fact nobody as brought this up until now means that apparently nobody cares about this working but me, since they're all using docker or something. (I haven't heard of docker until now, and I may be misunderstanding what it is, but I can't help but be viscerally disgusted by the concept)

Also, learning C++/Batch/whatever in order to fix someone else's problem just doesn't seem very appealing, knowing nobody would ever do the same for me. I have my own coding projects to struggle futilely against.

Who knows, maybe I'll feel better in the morning. Crying over a github comment probably isn't normal, after all.

**Comment by wyld-sw** [comment]
Based on our experience, the Windows-specific components, such as restart.exe, generally run successfully. However, they are currently more dependent on the specific environment than anticipated.

While rewriting restart.exe has been considered, the broader challenge lies in addressing other areas where Windows behaves differently.. Our primary focus is on creating a unified environment that ensures stable and consistent functionality across all features. Docker has been an effective tool in achieving this goal.

If you encounter any issues setting up this environment or have suggestions for improving its use, please don’t hesitate to reach out to us.
