### ISSUE TITLE
TAN (MUF primitive) documentation and implementation disagree about range

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#80]
The MUF primitive TAN's documentation says it only operates within -pi/4 to pi/4.

In fact, TAN checks whether its input is K*pi + pi/2 (for some K) and indicates NaN by returning zero and setting err_isnan? in this case. For other values (except inf/nan), it uses the system tan function.

**Comment by wyld-sw** [comment]
Fixed documentation.
