### ISSUE TITLE
pronoun substitution eats characters from the template string in some cases

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#85]
If you do `@set me=%x:%Nx` then run the MPI `{pronouns:foo%xfoo,me}`, the result is `fooMyNameXoo` instead of `fooMyNamexfoo` or `fooMyNameXfoo`.

**Comment by wyld-sw** [comment]
Committed a change to hopefully solve this, though I'm unsure of the correctness - just that it makes some sense and works in the situations I gave it. Please test.

**Comment by wyld-sw** [comment]
Closing. If this fix broke something else, please let me know.
